package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AreagrupoId generated by hbm2java
 */
@Embeddable
public class AreagrupoId implements java.io.Serializable {

	private BigDecimal idgrupo;
	private byte idarea;

	public AreagrupoId() {
	}

	public AreagrupoId(BigDecimal idgrupo, byte idarea) {
		this.idgrupo = idgrupo;
		this.idarea = idarea;
	}

	@Column(name = "IDGRUPO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(BigDecimal idgrupo) {
		this.idgrupo = idgrupo;
	}

	@Column(name = "IDAREA", nullable = false, precision = 2, scale = 0)
	public byte getIdarea() {
		return this.idarea;
	}

	public void setIdarea(byte idarea) {
		this.idarea = idarea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreagrupoId))
			return false;
		AreagrupoId castOther = (AreagrupoId) other;

		return ((this.getIdgrupo() == castOther.getIdgrupo()) || (this.getIdgrupo() != null
				&& castOther.getIdgrupo() != null && this.getIdgrupo().equals(castOther.getIdgrupo())))
				&& (this.getIdarea() == castOther.getIdarea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdgrupo() == null ? 0 : this.getIdgrupo().hashCode());
		result = 37 * result + this.getIdarea();
		return result;
	}

}
