package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuditoriaId generated by hbm2java
 */
@Embeddable
public class AuditoriaId implements java.io.Serializable {

	private int idMovimiento;
	private Integer idusuario;
	private Integer idtipomovimiento;
	private Date fechainicio;
	private String ipaddress;
	private String referencia;
	private Date fechafin;

	public AuditoriaId() {
	}

	public AuditoriaId(int idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public AuditoriaId(int idMovimiento, Integer idusuario, Integer idtipomovimiento, Date fechainicio,
			String ipaddress, String referencia, Date fechafin) {
		this.idMovimiento = idMovimiento;
		this.idusuario = idusuario;
		this.idtipomovimiento = idtipomovimiento;
		this.fechainicio = fechainicio;
		this.ipaddress = ipaddress;
		this.referencia = referencia;
		this.fechafin = fechafin;
	}

	@Column(name = "ID_MOVIMIENTO", nullable = false, precision = 6, scale = 0)
	public int getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(int idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	@Column(name = "IDUSUARIO", precision = 6, scale = 0)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "IDTIPOMOVIMIENTO", precision = 6, scale = 0)
	public Integer getIdtipomovimiento() {
		return this.idtipomovimiento;
	}

	public void setIdtipomovimiento(Integer idtipomovimiento) {
		this.idtipomovimiento = idtipomovimiento;
	}

	@Column(name = "FECHAINICIO", length = 7)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Column(name = "IPADDRESS", length = 15)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "REFERENCIA", length = 30)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "FECHAFIN", length = 7)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditoriaId))
			return false;
		AuditoriaId castOther = (AuditoriaId) other;

		return (this.getIdMovimiento() == castOther.getIdMovimiento())
				&& ((this.getIdusuario() == castOther.getIdusuario()) || (this.getIdusuario() != null
						&& castOther.getIdusuario() != null && this.getIdusuario().equals(castOther.getIdusuario())))
				&& ((this.getIdtipomovimiento() == castOther.getIdtipomovimiento())
						|| (this.getIdtipomovimiento() != null && castOther.getIdtipomovimiento() != null
								&& this.getIdtipomovimiento().equals(castOther.getIdtipomovimiento())))
				&& ((this.getFechainicio() == castOther.getFechainicio())
						|| (this.getFechainicio() != null && castOther.getFechainicio() != null
								&& this.getFechainicio().equals(castOther.getFechainicio())))
				&& ((this.getIpaddress() == castOther.getIpaddress()) || (this.getIpaddress() != null
						&& castOther.getIpaddress() != null && this.getIpaddress().equals(castOther.getIpaddress())))
				&& ((this.getReferencia() == castOther.getReferencia()) || (this.getReferencia() != null
						&& castOther.getReferencia() != null && this.getReferencia().equals(castOther.getReferencia())))
				&& ((this.getFechafin() == castOther.getFechafin()) || (this.getFechafin() != null
						&& castOther.getFechafin() != null && this.getFechafin().equals(castOther.getFechafin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMovimiento();
		result = 37 * result + (getIdusuario() == null ? 0 : this.getIdusuario().hashCode());
		result = 37 * result + (getIdtipomovimiento() == null ? 0 : this.getIdtipomovimiento().hashCode());
		result = 37 * result + (getFechainicio() == null ? 0 : this.getFechainicio().hashCode());
		result = 37 * result + (getIpaddress() == null ? 0 : this.getIpaddress().hashCode());
		result = 37 * result + (getReferencia() == null ? 0 : this.getReferencia().hashCode());
		result = 37 * result + (getFechafin() == null ? 0 : this.getFechafin().hashCode());
		return result;
	}

}
