package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatatipoventaId generated by hbm2java
 */
@Embeddable
public class CatatipoventaId implements java.io.Serializable {

	private String cvetipoventa;
	private BigDecimal idregiontventa;
	private String descripcion;

	public CatatipoventaId() {
	}

	public CatatipoventaId(String cvetipoventa, BigDecimal idregiontventa) {
		this.cvetipoventa = cvetipoventa;
		this.idregiontventa = idregiontventa;
	}

	public CatatipoventaId(String cvetipoventa, BigDecimal idregiontventa, String descripcion) {
		this.cvetipoventa = cvetipoventa;
		this.idregiontventa = idregiontventa;
		this.descripcion = descripcion;
	}

	@Column(name = "CVETIPOVENTA", nullable = false, length = 3)
	public String getCvetipoventa() {
		return this.cvetipoventa;
	}

	public void setCvetipoventa(String cvetipoventa) {
		this.cvetipoventa = cvetipoventa;
	}

	@Column(name = "IDREGIONTVENTA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdregiontventa() {
		return this.idregiontventa;
	}

	public void setIdregiontventa(BigDecimal idregiontventa) {
		this.idregiontventa = idregiontventa;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatatipoventaId))
			return false;
		CatatipoventaId castOther = (CatatipoventaId) other;

		return ((this.getCvetipoventa() == castOther.getCvetipoventa()) || (this.getCvetipoventa() != null
				&& castOther.getCvetipoventa() != null && this.getCvetipoventa().equals(castOther.getCvetipoventa())))
				&& ((this.getIdregiontventa() == castOther.getIdregiontventa())
						|| (this.getIdregiontventa() != null && castOther.getIdregiontventa() != null
								&& this.getIdregiontventa().equals(castOther.getIdregiontventa())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCvetipoventa() == null ? 0 : this.getCvetipoventa().hashCode());
		result = 37 * result + (getIdregiontventa() == null ? 0 : this.getIdregiontventa().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		return result;
	}

}
