package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatareaId generated by hbm2java
 */
@Embeddable
public class CatareaId implements java.io.Serializable {

	private byte idarea;
	private String descripcion;
	private Boolean activo;

	public CatareaId() {
	}

	public CatareaId(byte idarea) {
		this.idarea = idarea;
	}

	public CatareaId(byte idarea, String descripcion, Boolean activo) {
		this.idarea = idarea;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	@Column(name = "IDAREA", nullable = false, precision = 2, scale = 0)
	public byte getIdarea() {
		return this.idarea;
	}

	public void setIdarea(byte idarea) {
		this.idarea = idarea;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatareaId))
			return false;
		CatareaId castOther = (CatareaId) other;

		return (this.getIdarea() == castOther.getIdarea())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdarea();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
