package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catarea generated by hbm2java
 */
@Entity
@Table(name = "CATAREA", schema = "CERTREG")
public class Catarea implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatareaId id;

	public Catarea() {
	}

	public Catarea(CatareaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idarea", column = @Column(name = "IDAREA", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0) ) })
	public CatareaId getId() {
		return this.id;
	}

	public void setId(CatareaId id) {
		this.id = id;
	}

}
