package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatcsaId generated by hbm2java
 */
@Embeddable
public class CatcsaId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short idcsa;
	private String region;
	private String cveproveedor;
	private String nombre;
	private String razonsocial;
	private String contacto;
	private String direccion;
	private String telefono;
	private String ext;
	private String email;
	private Byte activo;
	private String pais;

	public CatcsaId() {
	}

	public CatcsaId(short idcsa, String region) {
		this.idcsa = idcsa;
		this.region = region;
	}

	public CatcsaId(short idcsa, String region, String cveproveedor, String nombre, String razonsocial, String contacto,
			String direccion, String telefono, String ext, String email, Byte activo, String pais) {
		this.idcsa = idcsa;
		this.region = region;
		this.cveproveedor = cveproveedor;
		this.nombre = nombre;
		this.razonsocial = razonsocial;
		this.contacto = contacto;
		this.direccion = direccion;
		this.telefono = telefono;
		this.ext = ext;
		this.email = email;
		this.activo = activo;
		this.pais = pais;
	}

	@Column(name = "IDCSA", nullable = false, precision = 4, scale = 0)
	public short getIdcsa() {
		return this.idcsa;
	}

	public void setIdcsa(short idcsa) {
		this.idcsa = idcsa;
	}

	@Column(name = "REGION", nullable = false, length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CVEPROVEEDOR", length = 30)
	public String getCveproveedor() {
		return this.cveproveedor;
	}

	public void setCveproveedor(String cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	@Column(name = "NOMBRE", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "RAZONSOCIAL", length = 80)
	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	@Column(name = "CONTACTO", length = 60)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "DIRECCION", length = 160)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO", length = 16)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "EXT", length = 5)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "EMAIL", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	@Column(name = "PAIS", length = 3)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatcsaId))
			return false;
		CatcsaId castOther = (CatcsaId) other;

		return (this.getIdcsa() == castOther.getIdcsa())
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getCveproveedor() == castOther.getCveproveedor())
						|| (this.getCveproveedor() != null && castOther.getCveproveedor() != null
								&& this.getCveproveedor().equals(castOther.getCveproveedor())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getRazonsocial() == castOther.getRazonsocial())
						|| (this.getRazonsocial() != null && castOther.getRazonsocial() != null
								&& this.getRazonsocial().equals(castOther.getRazonsocial())))
				&& ((this.getContacto() == castOther.getContacto()) || (this.getContacto() != null
						&& castOther.getContacto() != null && this.getContacto().equals(castOther.getContacto())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getExt() == castOther.getExt()) || (this.getExt() != null && castOther.getExt() != null
						&& this.getExt().equals(castOther.getExt())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getPais() == castOther.getPais()) || (this.getPais() != null && castOther.getPais() != null
						&& this.getPais().equals(castOther.getPais())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcsa();
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getCveproveedor() == null ? 0 : this.getCveproveedor().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getRazonsocial() == null ? 0 : this.getRazonsocial().hashCode());
		result = 37 * result + (getContacto() == null ? 0 : this.getContacto().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getExt() == null ? 0 : this.getExt().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getPais() == null ? 0 : this.getPais().hashCode());
		return result;
	}

}
