package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatdistribuidorId generated by hbm2java
 */
@Embeddable
public class CatdistribuidorId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short iddistribuidor;
	private String region;
	private String fuerzaventas;
	private String razonsocial;
	private String contacto;
	private String direccion;
	private String telefono;
	private String ext;
	private String email;
	private Byte activo;

	public CatdistribuidorId() {
	}

	public CatdistribuidorId(short iddistribuidor, String region) {
		this.iddistribuidor = iddistribuidor;
		this.region = region;
	}

	public CatdistribuidorId(short iddistribuidor, String region, String fuerzaventas, String razonsocial,
			String contacto, String direccion, String telefono, String ext, String email, Byte activo) {
		this.iddistribuidor = iddistribuidor;
		this.region = region;
		this.fuerzaventas = fuerzaventas;
		this.razonsocial = razonsocial;
		this.contacto = contacto;
		this.direccion = direccion;
		this.telefono = telefono;
		this.ext = ext;
		this.email = email;
		this.activo = activo;
	}

	@Column(name = "IDDISTRIBUIDOR", nullable = false, precision = 4, scale = 0)
	public short getIddistribuidor() {
		return this.iddistribuidor;
	}

	public void setIddistribuidor(short iddistribuidor) {
		this.iddistribuidor = iddistribuidor;
	}

	@Column(name = "REGION", nullable = false, length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "FUERZAVENTAS", length = 30)
	public String getFuerzaventas() {
		return this.fuerzaventas;
	}

	public void setFuerzaventas(String fuerzaventas) {
		this.fuerzaventas = fuerzaventas;
	}

	@Column(name = "RAZONSOCIAL", length = 80)
	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	@Column(name = "CONTACTO", length = 60)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "DIRECCION", length = 160)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO", length = 16)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "EXT", length = 5)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "EMAIL", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatdistribuidorId))
			return false;
		CatdistribuidorId castOther = (CatdistribuidorId) other;

		return (this.getIddistribuidor() == castOther.getIddistribuidor())
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getFuerzaventas() == castOther.getFuerzaventas())
						|| (this.getFuerzaventas() != null && castOther.getFuerzaventas() != null
								&& this.getFuerzaventas().equals(castOther.getFuerzaventas())))
				&& ((this.getRazonsocial() == castOther.getRazonsocial())
						|| (this.getRazonsocial() != null && castOther.getRazonsocial() != null
								&& this.getRazonsocial().equals(castOther.getRazonsocial())))
				&& ((this.getContacto() == castOther.getContacto()) || (this.getContacto() != null
						&& castOther.getContacto() != null && this.getContacto().equals(castOther.getContacto())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getExt() == castOther.getExt()) || (this.getExt() != null && castOther.getExt() != null
						&& this.getExt().equals(castOther.getExt())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIddistribuidor();
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getFuerzaventas() == null ? 0 : this.getFuerzaventas().hashCode());
		result = 37 * result + (getRazonsocial() == null ? 0 : this.getRazonsocial().hashCode());
		result = 37 * result + (getContacto() == null ? 0 : this.getContacto().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getExt() == null ? 0 : this.getExt().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
