package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catestatuskiosko generated by hbm2java
 */
@Entity
@Table(name = "CATESTATUSKIOSKO")
public class Catestatuskiosko implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatestatuskioskoId id;

	public Catestatuskiosko() {
	}

	public Catestatuskiosko(CatestatuskioskoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idestatuskiosko", column = @Column(name = "IDESTATUSKIOSKO", nullable = false, precision = 3, scale = 0) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 300) ),
			@AttributeOverride(name = "descportal", column = @Column(name = "DESCPORTAL", length = 300) ) })
	public CatestatuskioskoId getId() {
		return this.id;
	}

	public void setId(CatestatuskioskoId id) {
		this.id = id;
	}

}
