package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatestatusId generated by hbm2java
 */
@Embeddable
public class CatestatusId implements java.io.Serializable {

	private static final long serialVersionUID = 1L; 
	
	private int idestatus;
	private String descripcion;
	private String idjsp;
	private Byte activo;
	private Short idestatuskiosko;

	public CatestatusId() {
	}

	public CatestatusId(int idestatus) {
		this.idestatus = idestatus;
	}

	public CatestatusId(int idestatus, String descripcion, String idjsp, Byte activo, Short idestatuskiosko) {
		this.idestatus = idestatus;
		this.descripcion = descripcion;
		this.idjsp = idjsp;
		this.activo = activo;
		this.idestatuskiosko = idestatuskiosko;
	}

	@Column(name = "IDESTATUS", nullable = false, precision = 6, scale = 0)
	public int getIdestatus() {
		return this.idestatus;
	}

	public void setIdestatus(int idestatus) {
		this.idestatus = idestatus;
	}

	@Column(name = "DESCRIPCION", length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "IDJSP", length = 5)
	public String getIdjsp() {
		return this.idjsp;
	}

	public void setIdjsp(String idjsp) {
		this.idjsp = idjsp;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	@Column(name = "IDESTATUSKIOSKO", precision = 3, scale = 0)
	public Short getIdestatuskiosko() {
		return this.idestatuskiosko;
	}

	public void setIdestatuskiosko(Short idestatuskiosko) {
		this.idestatuskiosko = idestatuskiosko;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatestatusId))
			return false;
		CatestatusId castOther = (CatestatusId) other;

		return (this.getIdestatus() == castOther.getIdestatus())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getIdjsp() == castOther.getIdjsp()) || (this.getIdjsp() != null
						&& castOther.getIdjsp() != null && this.getIdjsp().equals(castOther.getIdjsp())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getIdestatuskiosko() == castOther.getIdestatuskiosko())
						|| (this.getIdestatuskiosko() != null && castOther.getIdestatuskiosko() != null
								&& this.getIdestatuskiosko().equals(castOther.getIdestatuskiosko())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdestatus();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getIdjsp() == null ? 0 : this.getIdjsp().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getIdestatuskiosko() == null ? 0 : this.getIdestatuskiosko().hashCode());
		return result;
	}

}
