package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catestatus generated by hbm2java
 */
@Entity
@Table(name = "CATESTATUS", schema = "CERTREG")
public class Catestatus implements java.io.Serializable {

	private CatestatusId id;

	public Catestatus() {
	}

	public Catestatus(CatestatusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idestatus", column = @Column(name = "IDESTATUS", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 60) ),
			@AttributeOverride(name = "idjsp", column = @Column(name = "IDJSP", length = 5) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 2, scale = 0) ),
			@AttributeOverride(name = "idestatuskiosko", column = @Column(name = "IDESTATUSKIOSKO", precision = 3, scale = 0) ) })
	public CatestatusId getId() {
		return this.id;
	}

	public void setId(CatestatusId id) {
		this.id = id;
	}

}
