package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatestatusprestamoId generated by hbm2java
 */
@Embeddable
public class CatestatusprestamoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idestatusprestamo;
	private String descripcion;
	private Byte activo;

	public CatestatusprestamoId() {
	}

	public CatestatusprestamoId(int idestatusprestamo) {
		this.idestatusprestamo = idestatusprestamo;
	}

	public CatestatusprestamoId(int idestatusprestamo, String descripcion, Byte activo) {
		this.idestatusprestamo = idestatusprestamo;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	@Column(name = "IDESTATUSPRESTAMO", nullable = false, precision = 6, scale = 0)
	public int getIdestatusprestamo() {
		return this.idestatusprestamo;
	}

	public void setIdestatusprestamo(int idestatusprestamo) {
		this.idestatusprestamo = idestatusprestamo;
	}

	@Column(name = "DESCRIPCION", length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatestatusprestamoId))
			return false;
		CatestatusprestamoId castOther = (CatestatusprestamoId) other;

		return (this.getIdestatusprestamo() == castOther.getIdestatusprestamo())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdestatusprestamo();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
