package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatestatuskioskoId generated by hbm2java
 */
@Embeddable
public class CatestatuskioskoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short idestatuskiosko;
	private String descripcion;
	private String descportal;

	public CatestatuskioskoId() {
	}

	public CatestatuskioskoId(short idestatuskiosko) {
		this.idestatuskiosko = idestatuskiosko;
	}

	public CatestatuskioskoId(short idestatuskiosko, String descripcion, String descportal) {
		this.idestatuskiosko = idestatuskiosko;
		this.descripcion = descripcion;
		this.descportal = descportal;
	}

	@Column(name = "IDESTATUSKIOSKO", nullable = false, precision = 3, scale = 0)
	public short getIdestatuskiosko() {
		return this.idestatuskiosko;
	}

	public void setIdestatuskiosko(short idestatuskiosko) {
		this.idestatuskiosko = idestatuskiosko;
	}

	@Column(name = "DESCRIPCION", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DESCPORTAL", length = 300)
	public String getDescportal() {
		return this.descportal;
	}

	public void setDescportal(String descportal) {
		this.descportal = descportal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatestatuskioskoId))
			return false;
		CatestatuskioskoId castOther = (CatestatuskioskoId) other;

		return (this.getIdestatuskiosko() == castOther.getIdestatuskiosko())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getDescportal() == castOther.getDescportal())
						|| (this.getDescportal() != null && castOther.getDescportal() != null
								&& this.getDescportal().equals(castOther.getDescportal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdestatuskiosko();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getDescportal() == null ? 0 : this.getDescportal().hashCode());
		return result;
	}

}
