package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatfallaId generated by hbm2java
 */
@Embeddable
public class CatfallaId implements java.io.Serializable {

	private short idfalla;
	private String descripcion;
	private Byte activo;
	private String cvemarca;
	private String fallaMarca;

	public CatfallaId() {
	}

	public CatfallaId(short idfalla) {
		this.idfalla = idfalla;
	}

	public CatfallaId(short idfalla, String descripcion, Byte activo, String cvemarca, String fallaMarca) {
		this.idfalla = idfalla;
		this.descripcion = descripcion;
		this.activo = activo;
		this.cvemarca = cvemarca;
		this.fallaMarca = fallaMarca;
	}

	@Column(name = "IDFALLA", nullable = false, precision = 4, scale = 0)
	public short getIdfalla() {
		return this.idfalla;
	}

	public void setIdfalla(short idfalla) {
		this.idfalla = idfalla;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	@Column(name = "CVEMARCA", length = 30)
	public String getCvemarca() {
		return this.cvemarca;
	}

	public void setCvemarca(String cvemarca) {
		this.cvemarca = cvemarca;
	}

	@Column(name = "FALLA_MARCA", length = 50)
	public String getFallaMarca() {
		return this.fallaMarca;
	}

	public void setFallaMarca(String fallaMarca) {
		this.fallaMarca = fallaMarca;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatfallaId))
			return false;
		CatfallaId castOther = (CatfallaId) other;

		return (this.getIdfalla() == castOther.getIdfalla())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getCvemarca() == castOther.getCvemarca()) || (this.getCvemarca() != null
						&& castOther.getCvemarca() != null && this.getCvemarca().equals(castOther.getCvemarca())))
				&& ((this.getFallaMarca() == castOther.getFallaMarca())
						|| (this.getFallaMarca() != null && castOther.getFallaMarca() != null
								&& this.getFallaMarca().equals(castOther.getFallaMarca())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfalla();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getCvemarca() == null ? 0 : this.getCvemarca().hashCode());
		result = 37 * result + (getFallaMarca() == null ? 0 : this.getFallaMarca().hashCode());
		return result;
	}

}
