package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatgrupoId generated by hbm2java
 */
@Embeddable
public class CatgrupoId implements java.io.Serializable {

	private BigDecimal idgrupo;
	private String descripcion;
	private BigDecimal activo;
	private Short permisoNecesario;

	public CatgrupoId() {
	}

	public CatgrupoId(BigDecimal idgrupo) {
		this.idgrupo = idgrupo;
	}

	public CatgrupoId(BigDecimal idgrupo, String descripcion, BigDecimal activo, Short permisoNecesario) {
		this.idgrupo = idgrupo;
		this.descripcion = descripcion;
		this.activo = activo;
		this.permisoNecesario = permisoNecesario;
	}

	@Column(name = "IDGRUPO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(BigDecimal idgrupo) {
		this.idgrupo = idgrupo;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	@Column(name = "PERMISO_NECESARIO", precision = 3, scale = 0)
	public Short getPermisoNecesario() {
		return this.permisoNecesario;
	}

	public void setPermisoNecesario(Short permisoNecesario) {
		this.permisoNecesario = permisoNecesario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatgrupoId))
			return false;
		CatgrupoId castOther = (CatgrupoId) other;

		return ((this.getIdgrupo() == castOther.getIdgrupo()) || (this.getIdgrupo() != null
				&& castOther.getIdgrupo() != null && this.getIdgrupo().equals(castOther.getIdgrupo())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getPermisoNecesario() == castOther.getPermisoNecesario())
						|| (this.getPermisoNecesario() != null && castOther.getPermisoNecesario() != null
								&& this.getPermisoNecesario().equals(castOther.getPermisoNecesario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdgrupo() == null ? 0 : this.getIdgrupo().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getPermisoNecesario() == null ? 0 : this.getPermisoNecesario().hashCode());
		return result;
	}

}
