package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catgrupocalificado generated by hbm2java
 */
@Entity
@Table(name = "CATGRUPOCALIFICADO", schema = "CERTREG")
public class Catgrupocalificado implements java.io.Serializable {

	private CatgrupocalificadoId id;

	public Catgrupocalificado() {
	}

	public Catgrupocalificado(CatgrupocalificadoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idgrupocalificado", column = @Column(name = "IDGRUPOCALIFICADO", nullable = false, precision = 22, scale = 0) ),
			@AttributeOverride(name = "idgrupo", column = @Column(name = "IDGRUPO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "idambito", column = @Column(name = "IDAMBITO", precision = 22, scale = 0) ) })
	public CatgrupocalificadoId getId() {
		return this.id;
	}

	public void setId(CatgrupocalificadoId id) {
		this.id = id;
	}

}
