package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatgrupocalificadoId generated by hbm2java
 */
@Embeddable
public class CatgrupocalificadoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigDecimal idgrupocalificado;
	private BigDecimal idgrupo;
	private BigDecimal idambito;

	public CatgrupocalificadoId() {
	}

	public CatgrupocalificadoId(BigDecimal idgrupocalificado) {
		this.idgrupocalificado = idgrupocalificado;
	}

	public CatgrupocalificadoId(BigDecimal idgrupocalificado, BigDecimal idgrupo, BigDecimal idambito) {
		this.idgrupocalificado = idgrupocalificado;
		this.idgrupo = idgrupo;
		this.idambito = idambito;
	}

	@Column(name = "IDGRUPOCALIFICADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdgrupocalificado() {
		return this.idgrupocalificado;
	}

	public void setIdgrupocalificado(BigDecimal idgrupocalificado) {
		this.idgrupocalificado = idgrupocalificado;
	}

	@Column(name = "IDGRUPO", precision = 22, scale = 0)
	public BigDecimal getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(BigDecimal idgrupo) {
		this.idgrupo = idgrupo;
	}

	@Column(name = "IDAMBITO", precision = 22, scale = 0)
	public BigDecimal getIdambito() {
		return this.idambito;
	}

	public void setIdambito(BigDecimal idambito) {
		this.idambito = idambito;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatgrupocalificadoId))
			return false;
		CatgrupocalificadoId castOther = (CatgrupocalificadoId) other;

		return ((this.getIdgrupocalificado() == castOther.getIdgrupocalificado())
				|| (this.getIdgrupocalificado() != null && castOther.getIdgrupocalificado() != null
						&& this.getIdgrupocalificado().equals(castOther.getIdgrupocalificado())))
				&& ((this.getIdgrupo() == castOther.getIdgrupo()) || (this.getIdgrupo() != null
						&& castOther.getIdgrupo() != null && this.getIdgrupo().equals(castOther.getIdgrupo())))
				&& ((this.getIdambito() == castOther.getIdambito()) || (this.getIdambito() != null
						&& castOther.getIdambito() != null && this.getIdambito().equals(castOther.getIdambito())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdgrupocalificado() == null ? 0 : this.getIdgrupocalificado().hashCode());
		result = 37 * result + (getIdgrupo() == null ? 0 : this.getIdgrupo().hashCode());
		result = 37 * result + (getIdambito() == null ? 0 : this.getIdambito().hashCode());
		return result;
	}

}
