package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catinterfaz generated by hbm2java
 */
@Entity
@Table(name = "CATINTERFAZ", schema = "CERTREG")
public class Catinterfaz implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatinterfazId id;

	public Catinterfaz() {
	}

	public Catinterfaz(CatinterfazId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 40) ),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 40) ),
			@AttributeOverride(name = "direccion", column = @Column(name = "DIRECCION", length = 60) ),
			@AttributeOverride(name = "puerto", column = @Column(name = "PUERTO", length = 4) ),
			@AttributeOverride(name = "nombreArchivo", column = @Column(name = "NOMBRE_ARCHIVO", length = 60) ),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", length = 200) ),
			@AttributeOverride(name = "directorio", column = @Column(name = "DIRECTORIO", length = 60) ),
			@AttributeOverride(name = "cveproveedor", column = @Column(name = "CVEPROVEEDOR", nullable = false, precision = 4, scale = 0) ) })
	public CatinterfazId getId() {
		return this.id;
	}

	public void setId(CatinterfazId id) {
		this.id = id;
	}

}
