package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatinterfazId generated by hbm2java
 */
@Embeddable
public class CatinterfazId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String usuario;
	private String password;
	private String direccion;
	private String puerto;
	private String nombreArchivo;
	private String email;
	private String directorio;
	private short cveproveedor;

	public CatinterfazId() {
	}

	public CatinterfazId(short cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	public CatinterfazId(String usuario, String password, String direccion, String puerto, String nombreArchivo,
			String email, String directorio, short cveproveedor) {
		this.usuario = usuario;
		this.password = password;
		this.direccion = direccion;
		this.puerto = puerto;
		this.nombreArchivo = nombreArchivo;
		this.email = email;
		this.directorio = directorio;
		this.cveproveedor = cveproveedor;
	}

	@Column(name = "USUARIO", length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "PASSWORD", length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "DIRECCION", length = 60)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "PUERTO", length = 4)
	public String getPuerto() {
		return this.puerto;
	}

	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

	@Column(name = "NOMBRE_ARCHIVO", length = 60)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	@Column(name = "EMAIL", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DIRECTORIO", length = 60)
	public String getDirectorio() {
		return this.directorio;
	}

	public void setDirectorio(String directorio) {
		this.directorio = directorio;
	}

	@Column(name = "CVEPROVEEDOR", nullable = false, precision = 4, scale = 0)
	public short getCveproveedor() {
		return this.cveproveedor;
	}

	public void setCveproveedor(short cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatinterfazId))
			return false;
		CatinterfazId castOther = (CatinterfazId) other;

		return ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
				&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getPuerto() == castOther.getPuerto()) || (this.getPuerto() != null
						&& castOther.getPuerto() != null && this.getPuerto().equals(castOther.getPuerto())))
				&& ((this.getNombreArchivo() == castOther.getNombreArchivo())
						|| (this.getNombreArchivo() != null && castOther.getNombreArchivo() != null
								&& this.getNombreArchivo().equals(castOther.getNombreArchivo())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getDirectorio() == castOther.getDirectorio()) || (this.getDirectorio() != null
						&& castOther.getDirectorio() != null && this.getDirectorio().equals(castOther.getDirectorio())))
				&& (this.getCveproveedor() == castOther.getCveproveedor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getPuerto() == null ? 0 : this.getPuerto().hashCode());
		result = 37 * result + (getNombreArchivo() == null ? 0 : this.getNombreArchivo().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getDirectorio() == null ? 0 : this.getDirectorio().hashCode());
		result = 37 * result + this.getCveproveedor();
		return result;
	}

}
