package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatincumplimientoId generated by hbm2java
 */
@Embeddable
public class CatincumplimientoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private byte idincumplimiento;
	private String descripcion;
	private Byte activo;

	public CatincumplimientoId() {
	}

	public CatincumplimientoId(byte idincumplimiento) {
		this.idincumplimiento = idincumplimiento;
	}

	public CatincumplimientoId(byte idincumplimiento, String descripcion, Byte activo) {
		this.idincumplimiento = idincumplimiento;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	@Column(name = "IDINCUMPLIMIENTO", nullable = false, precision = 2, scale = 0)
	public byte getIdincumplimiento() {
		return this.idincumplimiento;
	}

	public void setIdincumplimiento(byte idincumplimiento) {
		this.idincumplimiento = idincumplimiento;
	}

	@Column(name = "DESCRIPCION", length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatincumplimientoId))
			return false;
		CatincumplimientoId castOther = (CatincumplimientoId) other;

		return (this.getIdincumplimiento() == castOther.getIdincumplimiento())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdincumplimiento();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
