package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catmotivocita generated by hbm2java
 */
@Entity
@Table(name = "CATMOTIVOCITA", schema = "CERTREG")
public class Catmotivocita implements java.io.Serializable {

	private CatmotivocitaId id;

	public Catmotivocita() {
	}

	public Catmotivocita(CatmotivocitaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idmotivocita", column = @Column(name = "IDMOTIVOCITA", nullable = false, precision = 22, scale = 0) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ) })
	public CatmotivocitaId getId() {
		return this.id;
	}

	public void setId(CatmotivocitaId id) {
		this.id = id;
	}

}
