package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatpreguntasId generated by hbm2java
 */
@Embeddable
public class CatpreguntasId implements java.io.Serializable {

	private byte idpregunta;
	private String region;
	private String descripcion;

	public CatpreguntasId() {
	}

	public CatpreguntasId(byte idpregunta) {
		this.idpregunta = idpregunta;
	}

	public CatpreguntasId(byte idpregunta, String region, String descripcion) {
		this.idpregunta = idpregunta;
		this.region = region;
		this.descripcion = descripcion;
	}

	@Column(name = "IDPREGUNTA", nullable = false, precision = 2, scale = 0)
	public byte getIdpregunta() {
		return this.idpregunta;
	}

	public void setIdpregunta(byte idpregunta) {
		this.idpregunta = idpregunta;
	}

	@Column(name = "REGION", length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "DESCRIPCION", length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatpreguntasId))
			return false;
		CatpreguntasId castOther = (CatpreguntasId) other;

		return (this.getIdpregunta() == castOther.getIdpregunta())
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpregunta();
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		return result;
	}

}
