package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catproveedor generated by hbm2java
 */
@Entity
@Table(name = "CATPROVEEDOR", schema = "CERTREG")
public class Catproveedor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatproveedorId id;

	public Catproveedor() {
	}

	public Catproveedor(CatproveedorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idproveedor", column = @Column(name = "IDPROVEEDOR", nullable = false, precision = 4, scale = 0) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 60) ),
			@AttributeOverride(name = "contacto", column = @Column(name = "CONTACTO", length = 60) ),
			@AttributeOverride(name = "direccion", column = @Column(name = "DIRECCION", length = 160) ),
			@AttributeOverride(name = "telefono", column = @Column(name = "TELEFONO", length = 16) ),
			@AttributeOverride(name = "ext", column = @Column(name = "EXT", length = 5) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 2) ),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO", length = 2) ) })
	public CatproveedorId getId() {
		return this.id;
	}

	public void setId(CatproveedorId id) {
		this.id = id;
	}

}
