package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatproveedorId generated by hbm2java
 */
@Embeddable
public class CatproveedorId implements java.io.Serializable {

	private short idproveedor;
	private String nombre;
	private String contacto;
	private String direccion;
	private String telefono;
	private String ext;
	private Boolean activo;
	private String region;
	private String tipo;

	public CatproveedorId() {
	}

	public CatproveedorId(short idproveedor) {
		this.idproveedor = idproveedor;
	}

	public CatproveedorId(short idproveedor, String nombre, String contacto, String direccion, String telefono,
			String ext, Boolean activo, String region, String tipo) {
		this.idproveedor = idproveedor;
		this.nombre = nombre;
		this.contacto = contacto;
		this.direccion = direccion;
		this.telefono = telefono;
		this.ext = ext;
		this.activo = activo;
		this.region = region;
		this.tipo = tipo;
	}

	@Column(name = "IDPROVEEDOR", nullable = false, precision = 4, scale = 0)
	public short getIdproveedor() {
		return this.idproveedor;
	}

	public void setIdproveedor(short idproveedor) {
		this.idproveedor = idproveedor;
	}

	@Column(name = "NOMBRE", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CONTACTO", length = 60)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "DIRECCION", length = 160)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO", length = 16)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "EXT", length = 5)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "REGION", length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "TIPO", length = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatproveedorId))
			return false;
		CatproveedorId castOther = (CatproveedorId) other;

		return (this.getIdproveedor() == castOther.getIdproveedor())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getContacto() == castOther.getContacto()) || (this.getContacto() != null
						&& castOther.getContacto() != null && this.getContacto().equals(castOther.getContacto())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getExt() == castOther.getExt()) || (this.getExt() != null && castOther.getExt() != null
						&& this.getExt().equals(castOther.getExt())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproveedor();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getContacto() == null ? 0 : this.getContacto().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getExt() == null ? 0 : this.getExt().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
