package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catproductomarca generated by hbm2java
 */
@Entity
@Table(name = "CATPRODUCTOMARCA", schema = "CERTREG")
public class Catproductomarca implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatproductomarcaId id;

	public Catproductomarca() {
	}

	public Catproductomarca(CatproductomarcaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveproducto", column = @Column(name = "CVEPRODUCTO", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", nullable = false, length = 30) ),
			@AttributeOverride(name = "cvemodelo", column = @Column(name = "CVEMODELO", nullable = false, length = 30) ) })
	public CatproductomarcaId getId() {
		return this.id;
	}

	public void setId(CatproductomarcaId id) {
		this.id = id;
	}

}
