package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catpreguntas generated by hbm2java
 */
@Entity
@Table(name = "CATPREGUNTAS")
public class Catpreguntas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatpreguntasId id;

	public Catpreguntas() {
	}

	public Catpreguntas(CatpreguntasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idpregunta", column = @Column(name = "IDPREGUNTA", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 2) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 60) ) })
	public CatpreguntasId getId() {
		return this.id;
	}

	public void setId(CatpreguntasId id) {
		this.id = id;
	}

}
