package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catrefacciones generated by hbm2java
 */
@Entity
@Table(name = "CATREFACCIONES")
public class Catrefacciones implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatrefaccionesId id;

	public Catrefacciones() {
	}

	public Catrefacciones(CatrefaccionesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveproducto", column = @Column(name = "CVEPRODUCTO", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4) ),
			@AttributeOverride(name = "precio", column = @Column(name = "PRECIO", precision = 6) ),
			@AttributeOverride(name = "existencias", column = @Column(name = "EXISTENCIAS", precision = 6, scale = 0) ) })
	public CatrefaccionesId getId() {
		return this.id;
	}

	public void setId(CatrefaccionesId id) {
		this.id = id;
	}

}
