package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsesporadico generated by hbm2java
 */
@Entity
@Table(name = "CATSESPORADICO")
public class Catsesporadico implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private CatsesporadicoId id;

	public Catsesporadico() {
	}

	public Catsesporadico(CatsesporadicoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveesporadico", column = @Column(name = "CVEESPORADICO", nullable = false, length = 10) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "iva", column = @Column(name = "IVA", precision = 4) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ) })
	public CatsesporadicoId getId() {
		return this.id;
	}

	public void setId(CatsesporadicoId id) {
		this.id = id;
	}

}
