package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsegmentos generated by hbm2java
 */
@Entity
@Table(name = "CATSEGMENTOS", schema = "CERTREG")
public class Catsegmentos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatsegmentosId id;

	public Catsegmentos() {
	}

	public Catsegmentos(CatsegmentosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4) ),
			@AttributeOverride(name = "segmento", column = @Column(name = "SEGMENTO", nullable = false, length = 15) ),
			@AttributeOverride(name = "rangoinicial", column = @Column(name = "RANGOINICIAL", precision = 3, scale = 0) ),
			@AttributeOverride(name = "rangofinal", column = @Column(name = "RANGOFINAL", precision = 3, scale = 0) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 2, scale = 0) ) })
	public CatsegmentosId getId() {
		return this.id;
	}

	public void setId(CatsegmentosId id) {
		this.id = id;
	}

}
