package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsoficinadeventas generated by hbm2java
 */
@Entity
@Table(name = "CATSOFICINADEVENTAS", schema = "CERTREG")
public class Catsoficinadeventas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatsoficinadeventasId id;

	public Catsoficinadeventas() {
	}

	public Catsoficinadeventas(CatsoficinadeventasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4) ),
			@AttributeOverride(name = "cveestado", column = @Column(name = "CVEESTADO", length = 3) ),
			@AttributeOverride(name = "cvepais", column = @Column(name = "CVEPAIS", length = 3) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 50) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 2) ),
			@AttributeOverride(name = "calle", column = @Column(name = "CALLE", length = 60) ),
			@AttributeOverride(name = "numexterior", column = @Column(name = "NUMEXTERIOR", length = 10) ),
			@AttributeOverride(name = "numinterior", column = @Column(name = "NUMINTERIOR", length = 10) ),
			@AttributeOverride(name = "colonia", column = @Column(name = "COLONIA", length = 40) ),
			@AttributeOverride(name = "delegmunicipio", column = @Column(name = "DELEGMUNICIPIO", length = 40) ),
			@AttributeOverride(name = "ciudad", column = @Column(name = "CIUDAD", length = 35) ),
			@AttributeOverride(name = "cp", column = @Column(name = "CP", length = 10) ),
			@AttributeOverride(name = "telefono", column = @Column(name = "TELEFONO", length = 30) ),
			@AttributeOverride(name = "impresora", column = @Column(name = "IMPRESORA", length = 20) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "idambito", column = @Column(name = "IDAMBITO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "cvem2k", column = @Column(name = "CVEM2K", length = 9) ),
			@AttributeOverride(name = "sapactivo", column = @Column(name = "SAPACTIVO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "passwdsap", column = @Column(name = "PASSWDSAP", length = 40) ),
			@AttributeOverride(name = "usuariosap", column = @Column(name = "USUARIOSAP", length = 8) ),
			@AttributeOverride(name = "esporadicodefault", column = @Column(name = "ESPORADICODEFAULT", length = 10) ),
			@AttributeOverride(name = "segmento", column = @Column(name = "SEGMENTO", length = 15) ),
			@AttributeOverride(name = "rangoinicial", column = @Column(name = "RANGOINICIAL", precision = 3, scale = 0) ),
			@AttributeOverride(name = "rangofinal", column = @Column(name = "RANGOFINAL", precision = 3, scale = 0) ),
			@AttributeOverride(name = "consecutivo", column = @Column(name = "CONSECUTIVO", precision = 10, scale = 0) ),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", precision = 2, scale = 0) ),
			@AttributeOverride(name = "foraneo", column = @Column(name = "FORANEO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "diasenviocsa", column = @Column(name = "DIASENVIOCSA", precision = 2, scale = 0) ),
			@AttributeOverride(name = "pilot", column = @Column(name = "PILOT", precision = 1, scale = 0) ),
			@AttributeOverride(name = "diferenciahoraria", column = @Column(name = "DIFERENCIAHORARIA", precision = 1, scale = 0) ),
			@AttributeOverride(name = "diferenciaverano", column = @Column(name = "DIFERENCIAVERANO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "correojefecac", column = @Column(name = "CORREOJEFECAC", length = 50) ),
			@AttributeOverride(name = "almacendefault", column = @Column(name = "ALMACENDEFAULT", length = 10) ) })
	public CatsoficinadeventasId getId() {
		return this.id;
	}

	public void setId(CatsoficinadeventasId id) {
		this.id = id;
	}

}
