package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatscondicionpagoId generated by hbm2java
 */
@Embeddable
public class CatscondicionpagoId implements java.io.Serializable {

	private String cvecondicionpago;
	private String descripcion;
	private BigDecimal activo;

	public CatscondicionpagoId() {
	}

	public CatscondicionpagoId(String cvecondicionpago) {
		this.cvecondicionpago = cvecondicionpago;
	}

	public CatscondicionpagoId(String cvecondicionpago, String descripcion, BigDecimal activo) {
		this.cvecondicionpago = cvecondicionpago;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	@Column(name = "CVECONDICIONPAGO", nullable = false, length = 4)
	public String getCvecondicionpago() {
		return this.cvecondicionpago;
	}

	public void setCvecondicionpago(String cvecondicionpago) {
		this.cvecondicionpago = cvecondicionpago;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatscondicionpagoId))
			return false;
		CatscondicionpagoId castOther = (CatscondicionpagoId) other;

		return ((this.getCvecondicionpago() == castOther.getCvecondicionpago())
				|| (this.getCvecondicionpago() != null && castOther.getCvecondicionpago() != null
						&& this.getCvecondicionpago().equals(castOther.getCvecondicionpago())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCvecondicionpago() == null ? 0 : this.getCvecondicionpago().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
