package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catscategorias generated by hbm2java
 */
@Entity
@Table(name = "CATSCATEGORIAS", schema = "CERTREG")
public class Catscategorias implements java.io.Serializable {

	private CatscategoriasId id;

	public Catscategorias() {
	}

	public Catscategorias(CatscategoriasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvecategorias", column = @Column(name = "CVECATEGORIAS", nullable = false, length = 30) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ) })
	public CatscategoriasId getId() {
		return this.id;
	}

	public void setId(CatscategoriasId id) {
		this.id = id;
	}

}
