package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsmarca generated by hbm2java
 */
@Entity
@Table(name = "CATSMARCA", schema = "CERTREG")
public class Catsmarca implements java.io.Serializable {

	private CatsmarcaId id;

	public Catsmarca() {
	}

	public Catsmarca(CatsmarcaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", nullable = false, length = 30) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "cvemarcam2k", column = @Column(name = "CVEMARCAM2K", length = 8) ),
			@AttributeOverride(name = "diasreparacion", column = @Column(name = "DIASREPARACION", precision = 2, scale = 0) ),
			@AttributeOverride(name = "diasdescuento", column = @Column(name = "DIASDESCUENTO", precision = 2, scale = 0) ),
			@AttributeOverride(name = "aplicagarantia", column = @Column(name = "APLICAGARANTIA", precision = 22, scale = 0) ) })
	public CatsmarcaId getId() {
		return this.id;
	}

	public void setId(CatsmarcaId id) {
		this.id = id;
	}

}
