package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatsoficinadeventasId generated by hbm2java
 */
@Embeddable
public class CatsoficinadeventasId implements java.io.Serializable {

	private String cveoficinadeventas;
	private String cveestado;
	private String cvepais;
	private String nombre;
	private String region;
	private String calle;
	private String numexterior;
	private String numinterior;
	private String colonia;
	private String delegmunicipio;
	private String ciudad;
	private String cp;
	private String telefono;
	private String impresora;
	private BigDecimal activo;
	private BigDecimal idambito;
	private String cvem2k;
	private Boolean sapactivo;
	private String passwdsap;
	private String usuariosap;
	private String esporadicodefault;
	private String segmento;
	private Short rangoinicial;
	private Short rangofinal;
	private Long consecutivo;
	private Byte mes;
	private Boolean foraneo;
	private Byte diasenviocsa;
	private Boolean pilot;
	private Boolean diferenciahoraria;
	private Boolean diferenciaverano;
	private String correojefecac;
	private String almacendefault;

	public CatsoficinadeventasId() {
	}

	public CatsoficinadeventasId(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	public CatsoficinadeventasId(String cveoficinadeventas, String cveestado, String cvepais, String nombre,
			String region, String calle, String numexterior, String numinterior, String colonia, String delegmunicipio,
			String ciudad, String cp, String telefono, String impresora, BigDecimal activo, BigDecimal idambito,
			String cvem2k, Boolean sapactivo, String passwdsap, String usuariosap, String esporadicodefault,
			String segmento, Short rangoinicial, Short rangofinal, Long consecutivo, Byte mes, Boolean foraneo,
			Byte diasenviocsa, Boolean pilot, Boolean diferenciahoraria, Boolean diferenciaverano, String correojefecac,
			String almacendefault) {
		this.cveoficinadeventas = cveoficinadeventas;
		this.cveestado = cveestado;
		this.cvepais = cvepais;
		this.nombre = nombre;
		this.region = region;
		this.calle = calle;
		this.numexterior = numexterior;
		this.numinterior = numinterior;
		this.colonia = colonia;
		this.delegmunicipio = delegmunicipio;
		this.ciudad = ciudad;
		this.cp = cp;
		this.telefono = telefono;
		this.impresora = impresora;
		this.activo = activo;
		this.idambito = idambito;
		this.cvem2k = cvem2k;
		this.sapactivo = sapactivo;
		this.passwdsap = passwdsap;
		this.usuariosap = usuariosap;
		this.esporadicodefault = esporadicodefault;
		this.segmento = segmento;
		this.rangoinicial = rangoinicial;
		this.rangofinal = rangofinal;
		this.consecutivo = consecutivo;
		this.mes = mes;
		this.foraneo = foraneo;
		this.diasenviocsa = diasenviocsa;
		this.pilot = pilot;
		this.diferenciahoraria = diferenciahoraria;
		this.diferenciaverano = diferenciaverano;
		this.correojefecac = correojefecac;
		this.almacendefault = almacendefault;
	}

	@Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4)
	public String getCveoficinadeventas() {
		return this.cveoficinadeventas;
	}

	public void setCveoficinadeventas(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	@Column(name = "CVEESTADO", length = 3)
	public String getCveestado() {
		return this.cveestado;
	}

	public void setCveestado(String cveestado) {
		this.cveestado = cveestado;
	}

	@Column(name = "CVEPAIS", length = 3)
	public String getCvepais() {
		return this.cvepais;
	}

	public void setCvepais(String cvepais) {
		this.cvepais = cvepais;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "REGION", length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CALLE", length = 60)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "NUMEXTERIOR", length = 10)
	public String getNumexterior() {
		return this.numexterior;
	}

	public void setNumexterior(String numexterior) {
		this.numexterior = numexterior;
	}

	@Column(name = "NUMINTERIOR", length = 10)
	public String getNuminterior() {
		return this.numinterior;
	}

	public void setNuminterior(String numinterior) {
		this.numinterior = numinterior;
	}

	@Column(name = "COLONIA", length = 40)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "DELEGMUNICIPIO", length = 40)
	public String getDelegmunicipio() {
		return this.delegmunicipio;
	}

	public void setDelegmunicipio(String delegmunicipio) {
		this.delegmunicipio = delegmunicipio;
	}

	@Column(name = "CIUDAD", length = 35)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "CP", length = 10)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "TELEFONO", length = 30)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "IMPRESORA", length = 20)
	public String getImpresora() {
		return this.impresora;
	}

	public void setImpresora(String impresora) {
		this.impresora = impresora;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	@Column(name = "IDAMBITO", precision = 22, scale = 0)
	public BigDecimal getIdambito() {
		return this.idambito;
	}

	public void setIdambito(BigDecimal idambito) {
		this.idambito = idambito;
	}

	@Column(name = "CVEM2K", length = 9)
	public String getCvem2k() {
		return this.cvem2k;
	}

	public void setCvem2k(String cvem2k) {
		this.cvem2k = cvem2k;
	}

	@Column(name = "SAPACTIVO", precision = 1, scale = 0)
	public Boolean getSapactivo() {
		return this.sapactivo;
	}

	public void setSapactivo(Boolean sapactivo) {
		this.sapactivo = sapactivo;
	}

	@Column(name = "PASSWDSAP", length = 40)
	public String getPasswdsap() {
		return this.passwdsap;
	}

	public void setPasswdsap(String passwdsap) {
		this.passwdsap = passwdsap;
	}

	@Column(name = "USUARIOSAP", length = 8)
	public String getUsuariosap() {
		return this.usuariosap;
	}

	public void setUsuariosap(String usuariosap) {
		this.usuariosap = usuariosap;
	}

	@Column(name = "ESPORADICODEFAULT", length = 10)
	public String getEsporadicodefault() {
		return this.esporadicodefault;
	}

	public void setEsporadicodefault(String esporadicodefault) {
		this.esporadicodefault = esporadicodefault;
	}

	@Column(name = "SEGMENTO", length = 15)
	public String getSegmento() {
		return this.segmento;
	}

	public void setSegmento(String segmento) {
		this.segmento = segmento;
	}

	@Column(name = "RANGOINICIAL", precision = 3, scale = 0)
	public Short getRangoinicial() {
		return this.rangoinicial;
	}

	public void setRangoinicial(Short rangoinicial) {
		this.rangoinicial = rangoinicial;
	}

	@Column(name = "RANGOFINAL", precision = 3, scale = 0)
	public Short getRangofinal() {
		return this.rangofinal;
	}

	public void setRangofinal(Short rangofinal) {
		this.rangofinal = rangofinal;
	}

	@Column(name = "CONSECUTIVO", precision = 10, scale = 0)
	public Long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Long consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "MES", precision = 2, scale = 0)
	public Byte getMes() {
		return this.mes;
	}

	public void setMes(Byte mes) {
		this.mes = mes;
	}

	@Column(name = "FORANEO", precision = 1, scale = 0)
	public Boolean getForaneo() {
		return this.foraneo;
	}

	public void setForaneo(Boolean foraneo) {
		this.foraneo = foraneo;
	}

	@Column(name = "DIASENVIOCSA", precision = 2, scale = 0)
	public Byte getDiasenviocsa() {
		return this.diasenviocsa;
	}

	public void setDiasenviocsa(Byte diasenviocsa) {
		this.diasenviocsa = diasenviocsa;
	}

	@Column(name = "PILOT", precision = 1, scale = 0)
	public Boolean getPilot() {
		return this.pilot;
	}

	public void setPilot(Boolean pilot) {
		this.pilot = pilot;
	}

	@Column(name = "DIFERENCIAHORARIA", precision = 1, scale = 0)
	public Boolean getDiferenciahoraria() {
		return this.diferenciahoraria;
	}

	public void setDiferenciahoraria(Boolean diferenciahoraria) {
		this.diferenciahoraria = diferenciahoraria;
	}

	@Column(name = "DIFERENCIAVERANO", precision = 1, scale = 0)
	public Boolean getDiferenciaverano() {
		return this.diferenciaverano;
	}

	public void setDiferenciaverano(Boolean diferenciaverano) {
		this.diferenciaverano = diferenciaverano;
	}

	@Column(name = "CORREOJEFECAC", length = 50)
	public String getCorreojefecac() {
		return this.correojefecac;
	}

	public void setCorreojefecac(String correojefecac) {
		this.correojefecac = correojefecac;
	}

	@Column(name = "ALMACENDEFAULT", length = 10)
	public String getAlmacendefault() {
		return this.almacendefault;
	}

	public void setAlmacendefault(String almacendefault) {
		this.almacendefault = almacendefault;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatsoficinadeventasId))
			return false;
		CatsoficinadeventasId castOther = (CatsoficinadeventasId) other;

		return ((this.getCveoficinadeventas() == castOther.getCveoficinadeventas())
				|| (this.getCveoficinadeventas() != null && castOther.getCveoficinadeventas() != null
						&& this.getCveoficinadeventas().equals(castOther.getCveoficinadeventas())))
				&& ((this.getCveestado() == castOther.getCveestado()) || (this.getCveestado() != null
						&& castOther.getCveestado() != null && this.getCveestado().equals(castOther.getCveestado())))
				&& ((this.getCvepais() == castOther.getCvepais()) || (this.getCvepais() != null
						&& castOther.getCvepais() != null && this.getCvepais().equals(castOther.getCvepais())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getCalle() == castOther.getCalle()) || (this.getCalle() != null
						&& castOther.getCalle() != null && this.getCalle().equals(castOther.getCalle())))
				&& ((this.getNumexterior() == castOther.getNumexterior())
						|| (this.getNumexterior() != null && castOther.getNumexterior() != null
								&& this.getNumexterior().equals(castOther.getNumexterior())))
				&& ((this.getNuminterior() == castOther.getNuminterior())
						|| (this.getNuminterior() != null && castOther.getNuminterior() != null
								&& this.getNuminterior().equals(castOther.getNuminterior())))
				&& ((this.getColonia() == castOther.getColonia()) || (this.getColonia() != null
						&& castOther.getColonia() != null && this.getColonia().equals(castOther.getColonia())))
				&& ((this.getDelegmunicipio() == castOther.getDelegmunicipio())
						|| (this.getDelegmunicipio() != null && castOther.getDelegmunicipio() != null
								&& this.getDelegmunicipio().equals(castOther.getDelegmunicipio())))
				&& ((this.getCiudad() == castOther.getCiudad()) || (this.getCiudad() != null
						&& castOther.getCiudad() != null && this.getCiudad().equals(castOther.getCiudad())))
				&& ((this.getCp() == castOther.getCp()) || (this.getCp() != null && castOther.getCp() != null
						&& this.getCp().equals(castOther.getCp())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getImpresora() == castOther.getImpresora()) || (this.getImpresora() != null
						&& castOther.getImpresora() != null && this.getImpresora().equals(castOther.getImpresora())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getIdambito() == castOther.getIdambito()) || (this.getIdambito() != null
						&& castOther.getIdambito() != null && this.getIdambito().equals(castOther.getIdambito())))
				&& ((this.getCvem2k() == castOther.getCvem2k()) || (this.getCvem2k() != null
						&& castOther.getCvem2k() != null && this.getCvem2k().equals(castOther.getCvem2k())))
				&& ((this.getSapactivo() == castOther.getSapactivo()) || (this.getSapactivo() != null
						&& castOther.getSapactivo() != null && this.getSapactivo().equals(castOther.getSapactivo())))
				&& ((this.getPasswdsap() == castOther.getPasswdsap()) || (this.getPasswdsap() != null
						&& castOther.getPasswdsap() != null && this.getPasswdsap().equals(castOther.getPasswdsap())))
				&& ((this.getUsuariosap() == castOther.getUsuariosap()) || (this.getUsuariosap() != null
						&& castOther.getUsuariosap() != null && this.getUsuariosap().equals(castOther.getUsuariosap())))
				&& ((this.getEsporadicodefault() == castOther.getEsporadicodefault())
						|| (this.getEsporadicodefault() != null && castOther.getEsporadicodefault() != null
								&& this.getEsporadicodefault().equals(castOther.getEsporadicodefault())))
				&& ((this.getSegmento() == castOther.getSegmento()) || (this.getSegmento() != null
						&& castOther.getSegmento() != null && this.getSegmento().equals(castOther.getSegmento())))
				&& ((this.getRangoinicial() == castOther.getRangoinicial())
						|| (this.getRangoinicial() != null && castOther.getRangoinicial() != null
								&& this.getRangoinicial().equals(castOther.getRangoinicial())))
				&& ((this.getRangofinal() == castOther.getRangofinal()) || (this.getRangofinal() != null
						&& castOther.getRangofinal() != null && this.getRangofinal().equals(castOther.getRangofinal())))
				&& ((this.getConsecutivo() == castOther.getConsecutivo())
						|| (this.getConsecutivo() != null && castOther.getConsecutivo() != null
								&& this.getConsecutivo().equals(castOther.getConsecutivo())))
				&& ((this.getMes() == castOther.getMes()) || (this.getMes() != null && castOther.getMes() != null
						&& this.getMes().equals(castOther.getMes())))
				&& ((this.getForaneo() == castOther.getForaneo()) || (this.getForaneo() != null
						&& castOther.getForaneo() != null && this.getForaneo().equals(castOther.getForaneo())))
				&& ((this.getDiasenviocsa() == castOther.getDiasenviocsa())
						|| (this.getDiasenviocsa() != null && castOther.getDiasenviocsa() != null
								&& this.getDiasenviocsa().equals(castOther.getDiasenviocsa())))
				&& ((this.getPilot() == castOther.getPilot()) || (this.getPilot() != null
						&& castOther.getPilot() != null && this.getPilot().equals(castOther.getPilot())))
				&& ((this.getDiferenciahoraria() == castOther.getDiferenciahoraria())
						|| (this.getDiferenciahoraria() != null && castOther.getDiferenciahoraria() != null
								&& this.getDiferenciahoraria().equals(castOther.getDiferenciahoraria())))
				&& ((this.getDiferenciaverano() == castOther.getDiferenciaverano())
						|| (this.getDiferenciaverano() != null && castOther.getDiferenciaverano() != null
								&& this.getDiferenciaverano().equals(castOther.getDiferenciaverano())))
				&& ((this.getCorreojefecac() == castOther.getCorreojefecac())
						|| (this.getCorreojefecac() != null && castOther.getCorreojefecac() != null
								&& this.getCorreojefecac().equals(castOther.getCorreojefecac())))
				&& ((this.getAlmacendefault() == castOther.getAlmacendefault())
						|| (this.getAlmacendefault() != null && castOther.getAlmacendefault() != null
								&& this.getAlmacendefault().equals(castOther.getAlmacendefault())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveoficinadeventas() == null ? 0 : this.getCveoficinadeventas().hashCode());
		result = 37 * result + (getCveestado() == null ? 0 : this.getCveestado().hashCode());
		result = 37 * result + (getCvepais() == null ? 0 : this.getCvepais().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getCalle() == null ? 0 : this.getCalle().hashCode());
		result = 37 * result + (getNumexterior() == null ? 0 : this.getNumexterior().hashCode());
		result = 37 * result + (getNuminterior() == null ? 0 : this.getNuminterior().hashCode());
		result = 37 * result + (getColonia() == null ? 0 : this.getColonia().hashCode());
		result = 37 * result + (getDelegmunicipio() == null ? 0 : this.getDelegmunicipio().hashCode());
		result = 37 * result + (getCiudad() == null ? 0 : this.getCiudad().hashCode());
		result = 37 * result + (getCp() == null ? 0 : this.getCp().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getImpresora() == null ? 0 : this.getImpresora().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getIdambito() == null ? 0 : this.getIdambito().hashCode());
		result = 37 * result + (getCvem2k() == null ? 0 : this.getCvem2k().hashCode());
		result = 37 * result + (getSapactivo() == null ? 0 : this.getSapactivo().hashCode());
		result = 37 * result + (getPasswdsap() == null ? 0 : this.getPasswdsap().hashCode());
		result = 37 * result + (getUsuariosap() == null ? 0 : this.getUsuariosap().hashCode());
		result = 37 * result + (getEsporadicodefault() == null ? 0 : this.getEsporadicodefault().hashCode());
		result = 37 * result + (getSegmento() == null ? 0 : this.getSegmento().hashCode());
		result = 37 * result + (getRangoinicial() == null ? 0 : this.getRangoinicial().hashCode());
		result = 37 * result + (getRangofinal() == null ? 0 : this.getRangofinal().hashCode());
		result = 37 * result + (getConsecutivo() == null ? 0 : this.getConsecutivo().hashCode());
		result = 37 * result + (getMes() == null ? 0 : this.getMes().hashCode());
		result = 37 * result + (getForaneo() == null ? 0 : this.getForaneo().hashCode());
		result = 37 * result + (getDiasenviocsa() == null ? 0 : this.getDiasenviocsa().hashCode());
		result = 37 * result + (getPilot() == null ? 0 : this.getPilot().hashCode());
		result = 37 * result + (getDiferenciahoraria() == null ? 0 : this.getDiferenciahoraria().hashCode());
		result = 37 * result + (getDiferenciaverano() == null ? 0 : this.getDiferenciaverano().hashCode());
		result = 37 * result + (getCorreojefecac() == null ? 0 : this.getCorreojefecac().hashCode());
		result = 37 * result + (getAlmacendefault() == null ? 0 : this.getAlmacendefault().hashCode());
		return result;
	}

}
