package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsesporadicocondpago generated by hbm2java
 */
@Entity
@Table(name = "CATSESPORADICOCONDPAGO", schema = "CERTREG")
public class Catsesporadicocondpago implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatsesporadicocondpagoId id;

	public Catsesporadicocondpago() {
	}

	public Catsesporadicocondpago(CatsesporadicocondpagoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveesporadico", column = @Column(name = "CVEESPORADICO", nullable = false, length = 10) ),
			@AttributeOverride(name = "cvecondicionpago", column = @Column(name = "CVECONDICIONPAGO", nullable = false, length = 4) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0) ) })
	public CatsesporadicocondpagoId getId() {
		return this.id;
	}

	public void setId(CatsesporadicocondpagoId id) {
		this.id = id;
	}

}
