package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsmotivo generated by hbm2java
 */
@Entity
@Table(name = "CATSMOTIVO", schema = "CERTREG")
public class Catsmotivo implements java.io.Serializable {

	private CatsmotivoId id;

	public Catsmotivo() {
	}

	public Catsmotivo(CatsmotivoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvemotivo", column = @Column(name = "CVEMOTIVO", nullable = false, length = 3) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ) })
	public CatsmotivoId getId() {
		return this.id;
	}

	public void setId(CatsmotivoId id) {
		this.id = id;
	}

}
