package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsmaterial generated by hbm2java
 */
@Entity
@Table(name = "CATSMATERIAL")
public class Catsmaterial implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatsmaterialId id;

	public Catsmaterial() {
	}

	public Catsmaterial(CatsmaterialId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvematerial", column = @Column(name = "CVEMATERIAL", nullable = false, length = 18) ),
			@AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", length = 30) ),
			@AttributeOverride(name = "cvetipoproducto", column = @Column(name = "CVETIPOPRODUCTO", length = 2) ),
			@AttributeOverride(name = "denominacion", column = @Column(name = "DENOMINACION", length = 30) ),
			@AttributeOverride(name = "modelo", column = @Column(name = "MODELO", length = 100) ),
			@AttributeOverride(name = "cvetipomaterial", column = @Column(name = "CVETIPOMATERIAL", length = 9) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "requiereserie", column = @Column(name = "REQUIERESERIE", precision = 1, scale = 0) ),
			@AttributeOverride(name = "requierealmacen", column = @Column(name = "REQUIEREALMACEN", precision = 1, scale = 0) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "tiporotacion", column = @Column(name = "TIPOROTACION", length = 15) ) })
	public CatsmaterialId getId() {
		return this.id;
	}

	public void setId(CatsmaterialId id) {
		this.id = id;
	}

}
