package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catspais generated by hbm2java
 */
@Entity
@Table(name = "CATSPAIS")
public class Catspais implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatspaisId id;

	public Catspais() {
	}

	public Catspais(CatspaisId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvepais", column = @Column(name = "CVEPAIS", nullable = false, length = 3) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "cvepaism2k", column = @Column(name = "CVEPAISM2K", length = 3) ) })
	public CatspaisId getId() {
		return this.id;
	}

	public void setId(CatspaisId id) {
		this.id = id;
	}

}
