package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsubpreguntas generated by hbm2java
 */
@Entity
@Table(name = "CATSUBPREGUNTAS")
public class Catsubpreguntas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatsubpreguntasId id;

	public Catsubpreguntas() {
	}

	public Catsubpreguntas(CatsubpreguntasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idpregunta", column = @Column(name = "IDPREGUNTA", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "idsubpregunta", column = @Column(name = "IDSUBPREGUNTA", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 80) ),
			@AttributeOverride(name = "valormax", column = @Column(name = "VALORMAX", precision = 6, scale = 0) ),
			@AttributeOverride(name = "valormin", column = @Column(name = "VALORMIN", precision = 6, scale = 0) ),
			@AttributeOverride(name = "fechaactiva", column = @Column(name = "FECHAACTIVA", length = 7) ),
			@AttributeOverride(name = "fechaexpira", column = @Column(name = "FECHAEXPIRA", length = 7) ) })
	public CatsubpreguntasId getId() {
		return this.id;
	}

	public void setId(CatsubpreguntasId id) {
		this.id = id;
	}

}
