package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatsegmentosId generated by hbm2java
 */
@Embeddable
public class CatsegmentosId implements java.io.Serializable {

	private String cveoficinadeventas;
	private String segmento;
	private Short rangoinicial;
	private Short rangofinal;
	private Byte activo;

	public CatsegmentosId() {
	}

	public CatsegmentosId(String cveoficinadeventas, String segmento) {
		this.cveoficinadeventas = cveoficinadeventas;
		this.segmento = segmento;
	}

	public CatsegmentosId(String cveoficinadeventas, String segmento, Short rangoinicial, Short rangofinal,
			Byte activo) {
		this.cveoficinadeventas = cveoficinadeventas;
		this.segmento = segmento;
		this.rangoinicial = rangoinicial;
		this.rangofinal = rangofinal;
		this.activo = activo;
	}

	@Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4)
	public String getCveoficinadeventas() {
		return this.cveoficinadeventas;
	}

	public void setCveoficinadeventas(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	@Column(name = "SEGMENTO", nullable = false, length = 15)
	public String getSegmento() {
		return this.segmento;
	}

	public void setSegmento(String segmento) {
		this.segmento = segmento;
	}

	@Column(name = "RANGOINICIAL", precision = 3, scale = 0)
	public Short getRangoinicial() {
		return this.rangoinicial;
	}

	public void setRangoinicial(Short rangoinicial) {
		this.rangoinicial = rangoinicial;
	}

	@Column(name = "RANGOFINAL", precision = 3, scale = 0)
	public Short getRangofinal() {
		return this.rangofinal;
	}

	public void setRangofinal(Short rangofinal) {
		this.rangofinal = rangofinal;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatsegmentosId))
			return false;
		CatsegmentosId castOther = (CatsegmentosId) other;

		return ((this.getCveoficinadeventas() == castOther.getCveoficinadeventas())
				|| (this.getCveoficinadeventas() != null && castOther.getCveoficinadeventas() != null
						&& this.getCveoficinadeventas().equals(castOther.getCveoficinadeventas())))
				&& ((this.getSegmento() == castOther.getSegmento()) || (this.getSegmento() != null
						&& castOther.getSegmento() != null && this.getSegmento().equals(castOther.getSegmento())))
				&& ((this.getRangoinicial() == castOther.getRangoinicial())
						|| (this.getRangoinicial() != null && castOther.getRangoinicial() != null
								&& this.getRangoinicial().equals(castOther.getRangoinicial())))
				&& ((this.getRangofinal() == castOther.getRangofinal()) || (this.getRangofinal() != null
						&& castOther.getRangofinal() != null && this.getRangofinal().equals(castOther.getRangofinal())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveoficinadeventas() == null ? 0 : this.getCveoficinadeventas().hashCode());
		result = 37 * result + (getSegmento() == null ? 0 : this.getSegmento().hashCode());
		result = 37 * result + (getRangoinicial() == null ? 0 : this.getRangoinicial().hashCode());
		result = 37 * result + (getRangofinal() == null ? 0 : this.getRangofinal().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
