package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatsesporadicoId generated by hbm2java
 */
@Embeddable
public class CatsesporadicoId implements java.io.Serializable {

	private String cveesporadico;
	private String descripcion;
	private BigDecimal iva;
	private BigDecimal activo;

	public CatsesporadicoId() {
	}

	public CatsesporadicoId(String cveesporadico) {
		this.cveesporadico = cveesporadico;
	}

	public CatsesporadicoId(String cveesporadico, String descripcion, BigDecimal iva, BigDecimal activo) {
		this.cveesporadico = cveesporadico;
		this.descripcion = descripcion;
		this.iva = iva;
		this.activo = activo;
	}

	@Column(name = "CVEESPORADICO", nullable = false, length = 10)
	public String getCveesporadico() {
		return this.cveesporadico;
	}

	public void setCveesporadico(String cveesporadico) {
		this.cveesporadico = cveesporadico;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "IVA", precision = 4)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatsesporadicoId))
			return false;
		CatsesporadicoId castOther = (CatsesporadicoId) other;

		return ((this.getCveesporadico() == castOther.getCveesporadico())
				|| (this.getCveesporadico() != null && castOther.getCveesporadico() != null
						&& this.getCveesporadico().equals(castOther.getCveesporadico())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getIva() == castOther.getIva()) || (this.getIva() != null && castOther.getIva() != null
						&& this.getIva().equals(castOther.getIva())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveesporadico() == null ? 0 : this.getCveesporadico().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getIva() == null ? 0 : this.getIva().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
