package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatstipoproductoId generated by hbm2java
 */
@Embeddable
public class CatstipoproductoId implements java.io.Serializable {

	private String cvetipoproducto;
	private String descripcion;
	private BigDecimal activo;

	public CatstipoproductoId() {
	}

	public CatstipoproductoId(String cvetipoproducto) {
		this.cvetipoproducto = cvetipoproducto;
	}

	public CatstipoproductoId(String cvetipoproducto, String descripcion, BigDecimal activo) {
		this.cvetipoproducto = cvetipoproducto;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	@Column(name = "CVETIPOPRODUCTO", nullable = false, length = 2)
	public String getCvetipoproducto() {
		return this.cvetipoproducto;
	}

	public void setCvetipoproducto(String cvetipoproducto) {
		this.cvetipoproducto = cvetipoproducto;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatstipoproductoId))
			return false;
		CatstipoproductoId castOther = (CatstipoproductoId) other;

		return ((this.getCvetipoproducto() == castOther.getCvetipoproducto())
				|| (this.getCvetipoproducto() != null && castOther.getCvetipoproducto() != null
						&& this.getCvetipoproducto().equals(castOther.getCvetipoproducto())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCvetipoproducto() == null ? 0 : this.getCvetipoproducto().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
