package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catstipoproducto generated by hbm2java
 */
@Entity
@Table(name = "CATSTIPOPRODUCTO", schema = "CERTREG")
public class Catstipoproducto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatstipoproductoId id;

	public Catstipoproducto() {
	}

	public Catstipoproducto(CatstipoproductoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvetipoproducto", column = @Column(name = "CVETIPOPRODUCTO", nullable = false, length = 2) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ) })
	public CatstipoproductoId getId() {
		return this.id;
	}

	public void setId(CatstipoproductoId id) {
		this.id = id;
	}

}
