package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatsmarcaId generated by hbm2java
 */
@Embeddable
public class CatsmarcaId implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private String cvemarca;
	private String descripcion;
	private BigDecimal activo;
	private String cvemarcam2k;
	private Byte diasreparacion;
	private Byte diasdescuento;
	private BigDecimal aplicagarantia;

	public CatsmarcaId() {
	}

	public CatsmarcaId(String cvemarca) {
		this.cvemarca = cvemarca;
	}

	public CatsmarcaId(String cvemarca, String descripcion, BigDecimal activo, String cvemarcam2k, Byte diasreparacion,
			Byte diasdescuento, BigDecimal aplicagarantia) {
		this.cvemarca = cvemarca;
		this.descripcion = descripcion;
		this.activo = activo;
		this.cvemarcam2k = cvemarcam2k;
		this.diasreparacion = diasreparacion;
		this.diasdescuento = diasdescuento;
		this.aplicagarantia = aplicagarantia;
	}

	@Column(name = "CVEMARCA", nullable = false, length = 30)
	public String getCvemarca() {
		return this.cvemarca;
	}

	public void setCvemarca(String cvemarca) {
		this.cvemarca = cvemarca;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	@Column(name = "CVEMARCAM2K", length = 8)
	public String getCvemarcam2k() {
		return this.cvemarcam2k;
	}

	public void setCvemarcam2k(String cvemarcam2k) {
		this.cvemarcam2k = cvemarcam2k;
	}

	@Column(name = "DIASREPARACION", precision = 2, scale = 0)
	public Byte getDiasreparacion() {
		return this.diasreparacion;
	}

	public void setDiasreparacion(Byte diasreparacion) {
		this.diasreparacion = diasreparacion;
	}

	@Column(name = "DIASDESCUENTO", precision = 2, scale = 0)
	public Byte getDiasdescuento() {
		return this.diasdescuento;
	}

	public void setDiasdescuento(Byte diasdescuento) {
		this.diasdescuento = diasdescuento;
	}

	@Column(name = "APLICAGARANTIA", precision = 22, scale = 0)
	public BigDecimal getAplicagarantia() {
		return this.aplicagarantia;
	}

	public void setAplicagarantia(BigDecimal aplicagarantia) {
		this.aplicagarantia = aplicagarantia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatsmarcaId))
			return false;
		CatsmarcaId castOther = (CatsmarcaId) other;

		return ((this.getCvemarca() == castOther.getCvemarca()) || (this.getCvemarca() != null
				&& castOther.getCvemarca() != null && this.getCvemarca().equals(castOther.getCvemarca())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getCvemarcam2k() == castOther.getCvemarcam2k())
						|| (this.getCvemarcam2k() != null && castOther.getCvemarcam2k() != null
								&& this.getCvemarcam2k().equals(castOther.getCvemarcam2k())))
				&& ((this.getDiasreparacion() == castOther.getDiasreparacion())
						|| (this.getDiasreparacion() != null && castOther.getDiasreparacion() != null
								&& this.getDiasreparacion().equals(castOther.getDiasreparacion())))
				&& ((this.getDiasdescuento() == castOther.getDiasdescuento())
						|| (this.getDiasdescuento() != null && castOther.getDiasdescuento() != null
								&& this.getDiasdescuento().equals(castOther.getDiasdescuento())))
				&& ((this.getAplicagarantia() == castOther.getAplicagarantia())
						|| (this.getAplicagarantia() != null && castOther.getAplicagarantia() != null
								&& this.getAplicagarantia().equals(castOther.getAplicagarantia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCvemarca() == null ? 0 : this.getCvemarca().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getCvemarcam2k() == null ? 0 : this.getCvemarcam2k().hashCode());
		result = 37 * result + (getDiasreparacion() == null ? 0 : this.getDiasreparacion().hashCode());
		result = 37 * result + (getDiasdescuento() == null ? 0 : this.getDiasdescuento().hashCode());
		result = 37 * result + (getAplicagarantia() == null ? 0 : this.getAplicagarantia().hashCode());
		return result;
	}

}
