package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatsesporadicocondpagoId generated by hbm2java
 */
@Embeddable
public class CatsesporadicocondpagoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String cveesporadico;
	private String cvecondicionpago;
	private Boolean activo;

	public CatsesporadicocondpagoId() {
	}

	public CatsesporadicocondpagoId(String cveesporadico, String cvecondicionpago) {
		this.cveesporadico = cveesporadico;
		this.cvecondicionpago = cvecondicionpago;
	}

	public CatsesporadicocondpagoId(String cveesporadico, String cvecondicionpago, Boolean activo) {
		this.cveesporadico = cveesporadico;
		this.cvecondicionpago = cvecondicionpago;
		this.activo = activo;
	}

	@Column(name = "CVEESPORADICO", nullable = false, length = 10)
	public String getCveesporadico() {
		return this.cveesporadico;
	}

	public void setCveesporadico(String cveesporadico) {
		this.cveesporadico = cveesporadico;
	}

	@Column(name = "CVECONDICIONPAGO", nullable = false, length = 4)
	public String getCvecondicionpago() {
		return this.cvecondicionpago;
	}

	public void setCvecondicionpago(String cvecondicionpago) {
		this.cvecondicionpago = cvecondicionpago;
	}

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatsesporadicocondpagoId))
			return false;
		CatsesporadicocondpagoId castOther = (CatsesporadicocondpagoId) other;

		return ((this.getCveesporadico() == castOther.getCveesporadico())
				|| (this.getCveesporadico() != null && castOther.getCveesporadico() != null
						&& this.getCveesporadico().equals(castOther.getCveesporadico())))
				&& ((this.getCvecondicionpago() == castOther.getCvecondicionpago())
						|| (this.getCvecondicionpago() != null && castOther.getCvecondicionpago() != null
								&& this.getCvecondicionpago().equals(castOther.getCvecondicionpago())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveesporadico() == null ? 0 : this.getCveesporadico().hashCode());
		result = 37 * result + (getCvecondicionpago() == null ? 0 : this.getCvecondicionpago().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
