package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatspaisId generated by hbm2java
 */
@Embeddable
public class CatspaisId implements java.io.Serializable {

	private String cvepais;
	private String descripcion;
	private BigDecimal activo;
	private String cvepaism2k;

	public CatspaisId() {
	}

	public CatspaisId(String cvepais) {
		this.cvepais = cvepais;
	}

	public CatspaisId(String cvepais, String descripcion, BigDecimal activo, String cvepaism2k) {
		this.cvepais = cvepais;
		this.descripcion = descripcion;
		this.activo = activo;
		this.cvepaism2k = cvepaism2k;
	}

	@Column(name = "CVEPAIS", nullable = false, length = 3)
	public String getCvepais() {
		return this.cvepais;
	}

	public void setCvepais(String cvepais) {
		this.cvepais = cvepais;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	@Column(name = "CVEPAISM2K", length = 3)
	public String getCvepaism2k() {
		return this.cvepaism2k;
	}

	public void setCvepaism2k(String cvepaism2k) {
		this.cvepaism2k = cvepaism2k;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatspaisId))
			return false;
		CatspaisId castOther = (CatspaisId) other;

		return ((this.getCvepais() == castOther.getCvepais()) || (this.getCvepais() != null
				&& castOther.getCvepais() != null && this.getCvepais().equals(castOther.getCvepais())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getCvepaism2k() == castOther.getCvepaism2k())
						|| (this.getCvepaism2k() != null && castOther.getCvepaism2k() != null
								&& this.getCvepaism2k().equals(castOther.getCvepaism2k())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCvepais() == null ? 0 : this.getCvepais().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getCvepaism2k() == null ? 0 : this.getCvepaism2k().hashCode());
		return result;
	}

}
