package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catsproveedor generated by hbm2java
 */
@Entity
@Table(name = "CATSPROVEEDOR", schema = "CERTREG")
public class Catsproveedor implements java.io.Serializable {

	private CatsproveedorId id;

	public Catsproveedor() {
	}

	public Catsproveedor(CatsproveedorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveproveedor", column = @Column(name = "CVEPROVEEDOR", nullable = false, length = 30) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 100) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "pais", column = @Column(name = "PAIS", length = 3) ) })
	public CatsproveedorId getId() {
		return this.id;
	}

	public void setId(CatsproveedorId id) {
		this.id = id;
	}

}
