package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatsproveedorId generated by hbm2java
 */
@Embeddable
public class CatsproveedorId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String cveproveedor;
	private String descripcion;
	private Boolean activo;
	private String pais;

	public CatsproveedorId() {
	}

	public CatsproveedorId(String cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	public CatsproveedorId(String cveproveedor, String descripcion, Boolean activo, String pais) {
		this.cveproveedor = cveproveedor;
		this.descripcion = descripcion;
		this.activo = activo;
		this.pais = pais;
	}

	@Column(name = "CVEPROVEEDOR", nullable = false, length = 30)
	public String getCveproveedor() {
		return this.cveproveedor;
	}

	public void setCveproveedor(String cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "PAIS", length = 3)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatsproveedorId))
			return false;
		CatsproveedorId castOther = (CatsproveedorId) other;

		return ((this.getCveproveedor() == castOther.getCveproveedor()) || (this.getCveproveedor() != null
				&& castOther.getCveproveedor() != null && this.getCveproveedor().equals(castOther.getCveproveedor())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getPais() == castOther.getPais()) || (this.getPais() != null && castOther.getPais() != null
						&& this.getPais().equals(castOther.getPais())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveproveedor() == null ? 0 : this.getCveproveedor().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getPais() == null ? 0 : this.getPais().hashCode());
		return result;
	}

}
