package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatusuarioId generated by hbm2java
 */
@Embeddable
public class CatusuarioId implements java.io.Serializable {

	private int idusuario;
	private String cveusuario;
	private String puesto;
	private String region;
	private String cvejefe;
	private BigDecimal numempleado;
	private String nombrecompleto;
	private String departamento;
	private String gerencia;
	private String telefono;
	private String email;
	private String password;
	private BigDecimal activo;
	private Date fechaalta;
	private Date fechabaja;
	private Date fechamodificacion;

	public CatusuarioId() {
	}

	public CatusuarioId(int idusuario) {
		this.idusuario = idusuario;
	}

	public CatusuarioId(int idusuario, String cveusuario, String puesto, String region, String cvejefe,
			BigDecimal numempleado, String nombrecompleto, String departamento, String gerencia, String telefono,
			String email, String password, BigDecimal activo, Date fechaalta, Date fechabaja, Date fechamodificacion) {
		this.idusuario = idusuario;
		this.cveusuario = cveusuario;
		this.puesto = puesto;
		this.region = region;
		this.cvejefe = cvejefe;
		this.numempleado = numempleado;
		this.nombrecompleto = nombrecompleto;
		this.departamento = departamento;
		this.gerencia = gerencia;
		this.telefono = telefono;
		this.email = email;
		this.password = password;
		this.activo = activo;
		this.fechaalta = fechaalta;
		this.fechabaja = fechabaja;
		this.fechamodificacion = fechamodificacion;
	}

	@Column(name = "IDUSUARIO", nullable = false, precision = 6, scale = 0)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "CVEUSUARIO", length = 8)
	public String getCveusuario() {
		return this.cveusuario;
	}

	public void setCveusuario(String cveusuario) {
		this.cveusuario = cveusuario;
	}

	@Column(name = "PUESTO", length = 20)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@Column(name = "REGION", length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CVEJEFE", length = 8)
	public String getCvejefe() {
		return this.cvejefe;
	}

	public void setCvejefe(String cvejefe) {
		this.cvejefe = cvejefe;
	}

	@Column(name = "NUMEMPLEADO", precision = 22, scale = 0)
	public BigDecimal getNumempleado() {
		return this.numempleado;
	}

	public void setNumempleado(BigDecimal numempleado) {
		this.numempleado = numempleado;
	}

	@Column(name = "NOMBRECOMPLETO", length = 80)
	public String getNombrecompleto() {
		return this.nombrecompleto;
	}

	public void setNombrecompleto(String nombrecompleto) {
		this.nombrecompleto = nombrecompleto;
	}

	@Column(name = "DEPARTAMENTO", length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "GERENCIA", length = 50)
	public String getGerencia() {
		return this.gerencia;
	}

	public void setGerencia(String gerencia) {
		this.gerencia = gerencia;
	}

	@Column(name = "TELEFONO", length = 30)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	@Column(name = "FECHAALTA", length = 7)
	public Date getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

	@Column(name = "FECHABAJA", length = 7)
	public Date getFechabaja() {
		return this.fechabaja;
	}

	public void setFechabaja(Date fechabaja) {
		this.fechabaja = fechabaja;
	}

	@Column(name = "FECHAMODIFICACION", length = 7)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatusuarioId))
			return false;
		CatusuarioId castOther = (CatusuarioId) other;

		return (this.getIdusuario() == castOther.getIdusuario())
				&& ((this.getCveusuario() == castOther.getCveusuario()) || (this.getCveusuario() != null
						&& castOther.getCveusuario() != null && this.getCveusuario().equals(castOther.getCveusuario())))
				&& ((this.getPuesto() == castOther.getPuesto()) || (this.getPuesto() != null
						&& castOther.getPuesto() != null && this.getPuesto().equals(castOther.getPuesto())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getCvejefe() == castOther.getCvejefe()) || (this.getCvejefe() != null
						&& castOther.getCvejefe() != null && this.getCvejefe().equals(castOther.getCvejefe())))
				&& ((this.getNumempleado() == castOther.getNumempleado())
						|| (this.getNumempleado() != null && castOther.getNumempleado() != null
								&& this.getNumempleado().equals(castOther.getNumempleado())))
				&& ((this.getNombrecompleto() == castOther.getNombrecompleto())
						|| (this.getNombrecompleto() != null && castOther.getNombrecompleto() != null
								&& this.getNombrecompleto().equals(castOther.getNombrecompleto())))
				&& ((this.getDepartamento() == castOther.getDepartamento())
						|| (this.getDepartamento() != null && castOther.getDepartamento() != null
								&& this.getDepartamento().equals(castOther.getDepartamento())))
				&& ((this.getGerencia() == castOther.getGerencia()) || (this.getGerencia() != null
						&& castOther.getGerencia() != null && this.getGerencia().equals(castOther.getGerencia())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getFechaalta() == castOther.getFechaalta()) || (this.getFechaalta() != null
						&& castOther.getFechaalta() != null && this.getFechaalta().equals(castOther.getFechaalta())))
				&& ((this.getFechabaja() == castOther.getFechabaja()) || (this.getFechabaja() != null
						&& castOther.getFechabaja() != null && this.getFechabaja().equals(castOther.getFechabaja())))
				&& ((this.getFechamodificacion() == castOther.getFechamodificacion())
						|| (this.getFechamodificacion() != null && castOther.getFechamodificacion() != null
								&& this.getFechamodificacion().equals(castOther.getFechamodificacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuario();
		result = 37 * result + (getCveusuario() == null ? 0 : this.getCveusuario().hashCode());
		result = 37 * result + (getPuesto() == null ? 0 : this.getPuesto().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getCvejefe() == null ? 0 : this.getCvejefe().hashCode());
		result = 37 * result + (getNumempleado() == null ? 0 : this.getNumempleado().hashCode());
		result = 37 * result + (getNombrecompleto() == null ? 0 : this.getNombrecompleto().hashCode());
		result = 37 * result + (getDepartamento() == null ? 0 : this.getDepartamento().hashCode());
		result = 37 * result + (getGerencia() == null ? 0 : this.getGerencia().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getFechaalta() == null ? 0 : this.getFechaalta().hashCode());
		result = 37 * result + (getFechabaja() == null ? 0 : this.getFechabaja().hashCode());
		result = 37 * result + (getFechamodificacion() == null ? 0 : this.getFechamodificacion().hashCode());
		return result;
	}

}
