package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Catusuario generated by hbm2java
 */
@Entity
@Table(name = "CATUSUARIO", schema = "CERTREG")
public class Catusuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private CatusuarioId id;

	public Catusuario() {
	}

	public Catusuario(CatusuarioId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuario", column = @Column(name = "IDUSUARIO", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "cveusuario", column = @Column(name = "CVEUSUARIO", length = 8) ),
			@AttributeOverride(name = "puesto", column = @Column(name = "PUESTO", length = 20) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 2) ),
			@AttributeOverride(name = "cvejefe", column = @Column(name = "CVEJEFE", length = 8) ),
			@AttributeOverride(name = "numempleado", column = @Column(name = "NUMEMPLEADO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "nombrecompleto", column = @Column(name = "NOMBRECOMPLETO", length = 80) ),
			@AttributeOverride(name = "departamento", column = @Column(name = "DEPARTAMENTO", length = 50) ),
			@AttributeOverride(name = "gerencia", column = @Column(name = "GERENCIA", length = 50) ),
			@AttributeOverride(name = "telefono", column = @Column(name = "TELEFONO", length = 30) ),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", length = 50) ),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 40) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fechaalta", column = @Column(name = "FECHAALTA", length = 7) ),
			@AttributeOverride(name = "fechabaja", column = @Column(name = "FECHABAJA", length = 7) ),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7) ) })
	public CatusuarioId getId() {
		return this.id;
	}

	public void setId(CatusuarioId id) {
		this.id = id;
	}

}
