package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CcCtltipomovimiento generated by hbm2java
 */
@Entity
@Table(name = "CC_CTLTIPOMOVIMIENTO", schema = "CERTREG")
public class CcCtltipomovimiento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short idmovto;
	private String descripcion;

	public CcCtltipomovimiento() {
	}

	public CcCtltipomovimiento(short idmovto, String descripcion) {
		this.idmovto = idmovto;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "IDMOVTO", unique = true, nullable = false, precision = 4, scale = 0)
	public short getIdmovto() {
		return this.idmovto;
	}

	public void setIdmovto(short idmovto) {
		this.idmovto = idmovto;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
