package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CcCtlusuarios generated by hbm2java
 */
@Entity
@Table(name = "CC_CTLUSUARIOS", schema = "CERTREG")
public class CcCtlusuarios implements java.io.Serializable {

	private CcCtlusuariosId id;

	public CcCtlusuarios() {
	}

	public CcCtlusuarios(CcCtlusuariosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", nullable = false, length = 16) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", nullable = false, length = 4) ),
			@AttributeOverride(name = "moneda", column = @Column(name = "MONEDA", nullable = false, length = 8) ) })
	public CcCtlusuariosId getId() {
		return this.id;
	}

	public void setId(CcCtlusuariosId id) {
		this.id = id;
	}

}
