package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CcCtltipoestatuscert generated by hbm2java
 */
@Entity
@Table(name = "CC_CTLTIPOESTATUSCERT")
public class CcCtltipoestatuscert implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short idestatus;
	private String descripcion;

	public CcCtltipoestatuscert() {
	}

	public CcCtltipoestatuscert(short idestatus, String descripcion) {
		this.idestatus = idestatus;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "IDESTATUS", unique = true, nullable = false, precision = 4, scale = 0)
	public short getIdestatus() {
		return this.idestatus;
	}

	public void setIdestatus(short idestatus) {
		this.idestatus = idestatus;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
