package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CcTbltarjetacertificado generated by hbm2java
 */
@Entity
@Table(name = "CC_TBLTARJETACERTIFICADO", schema = "CERTREG")
public class CcTbltarjetacertificado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String numcertificado;
	private String numtarjeta;
	private BigDecimal valorrestante;
	private Timestamp fechaactivacion;
	private Timestamp fechaexpiracion;
	private String estatus;
	private String idusuario;

	public CcTbltarjetacertificado() {
	}

	public CcTbltarjetacertificado(String numcertificado, String numtarjeta, BigDecimal valorrestante,
			Timestamp fechaactivacion, String estatus, String idusuario) {
		this.numcertificado = numcertificado;
		this.numtarjeta = numtarjeta;
		this.valorrestante = valorrestante;
		this.fechaactivacion = fechaactivacion;
		this.estatus = estatus;
		this.idusuario = idusuario;
	}

	public CcTbltarjetacertificado(String numcertificado, String numtarjeta, BigDecimal valorrestante,
			Timestamp fechaactivacion, Timestamp fechaexpiracion, String estatus, String idusuario) {
		this.numcertificado = numcertificado;
		this.numtarjeta = numtarjeta;
		this.valorrestante = valorrestante;
		this.fechaactivacion = fechaactivacion;
		this.fechaexpiracion = fechaexpiracion;
		this.estatus = estatus;
		this.idusuario = idusuario;
	}

	@Id

	@Column(name = "NUMCERTIFICADO", unique = true, nullable = false, length = 16)
	public String getNumcertificado() {
		return this.numcertificado;
	}

	public void setNumcertificado(String numcertificado) {
		this.numcertificado = numcertificado;
	}

	@Column(name = "NUMTARJETA", nullable = false, length = 16)
	public String getNumtarjeta() {
		return this.numtarjeta;
	}

	public void setNumtarjeta(String numtarjeta) {
		this.numtarjeta = numtarjeta;
	}

	@Column(name = "VALORRESTANTE", nullable = false, precision = 12)
	public BigDecimal getValorrestante() {
		return this.valorrestante;
	}

	public void setValorrestante(BigDecimal valorrestante) {
		this.valorrestante = valorrestante;
	}

	@Column(name = "FECHAACTIVACION", nullable = false)
	public Timestamp getFechaactivacion() {
		return this.fechaactivacion;
	}

	public void setFechaactivacion(Timestamp fechaactivacion) {
		this.fechaactivacion = fechaactivacion;
	}

	@Column(name = "FECHAEXPIRACION")
	public Timestamp getFechaexpiracion() {
		return this.fechaexpiracion;
	}

	public void setFechaexpiracion(Timestamp fechaexpiracion) {
		this.fechaexpiracion = fechaexpiracion;
	}

	@Column(name = "ESTATUS", nullable = false, length = 1)
	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}

	@Column(name = "IDUSUARIO", nullable = false, length = 10)
	public String getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(String idusuario) {
		this.idusuario = idusuario;
	}

}
