package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CcTblmovimientocertificadoId generated by hbm2java
 */
@Embeddable
public class CcTblmovimientocertificadoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String folio;
	private String numcertificado;
	private String numtarjeta;
	private Timestamp fechaoper;
	private String puntovta;

	public CcTblmovimientocertificadoId() {
	}

	public CcTblmovimientocertificadoId(String folio, String numcertificado, String numtarjeta, Timestamp fechaoper,
			String puntovta) {
		this.folio = folio;
		this.numcertificado = numcertificado;
		this.numtarjeta = numtarjeta;
		this.fechaoper = fechaoper;
		this.puntovta = puntovta;
	}

	@Column(name = "FOLIO", nullable = false, length = 20)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "NUMCERTIFICADO", nullable = false, length = 16)
	public String getNumcertificado() {
		return this.numcertificado;
	}

	public void setNumcertificado(String numcertificado) {
		this.numcertificado = numcertificado;
	}

	@Column(name = "NUMTARJETA", nullable = false, length = 16)
	public String getNumtarjeta() {
		return this.numtarjeta;
	}

	public void setNumtarjeta(String numtarjeta) {
		this.numtarjeta = numtarjeta;
	}

	@Column(name = "FECHAOPER", nullable = false)
	public Timestamp getFechaoper() {
		return this.fechaoper;
	}

	public void setFechaoper(Timestamp fechaoper) {
		this.fechaoper = fechaoper;
	}

	@Column(name = "PUNTOVTA", nullable = false, length = 24)
	public String getPuntovta() {
		return this.puntovta;
	}

	public void setPuntovta(String puntovta) {
		this.puntovta = puntovta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CcTblmovimientocertificadoId))
			return false;
		CcTblmovimientocertificadoId castOther = (CcTblmovimientocertificadoId) other;

		return ((this.getFolio() == castOther.getFolio()) || (this.getFolio() != null && castOther.getFolio() != null
				&& this.getFolio().equals(castOther.getFolio())))
				&& ((this.getNumcertificado() == castOther.getNumcertificado())
						|| (this.getNumcertificado() != null && castOther.getNumcertificado() != null
								&& this.getNumcertificado().equals(castOther.getNumcertificado())))
				&& ((this.getNumtarjeta() == castOther.getNumtarjeta()) || (this.getNumtarjeta() != null
						&& castOther.getNumtarjeta() != null && this.getNumtarjeta().equals(castOther.getNumtarjeta())))
				&& ((this.getFechaoper() == castOther.getFechaoper()) || (this.getFechaoper() != null
						&& castOther.getFechaoper() != null && this.getFechaoper().equals(castOther.getFechaoper())))
				&& ((this.getPuntovta() == castOther.getPuntovta()) || (this.getPuntovta() != null
						&& castOther.getPuntovta() != null && this.getPuntovta().equals(castOther.getPuntovta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result + (getNumcertificado() == null ? 0 : this.getNumcertificado().hashCode());
		result = 37 * result + (getNumtarjeta() == null ? 0 : this.getNumtarjeta().hashCode());
		result = 37 * result + (getFechaoper() == null ? 0 : this.getFechaoper().hashCode());
		result = 37 * result + (getPuntovta() == null ? 0 : this.getPuntovta().hashCode());
		return result;
	}

}
