package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClavessapId generated by hbm2java
 */
@Embeddable
public class ClavessapId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String campo;
	private String clave;
	private String nuevaclave;
	private String descripcion;

	public ClavessapId() {
	}

	public ClavessapId(String campo, String clave, String nuevaclave, String descripcion) {
		this.campo = campo;
		this.clave = clave;
		this.nuevaclave = nuevaclave;
		this.descripcion = descripcion;
	}

	@Column(name = "CAMPO", length = 25)
	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	@Column(name = "CLAVE", length = 50)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "NUEVACLAVE", length = 50)
	public String getNuevaclave() {
		return this.nuevaclave;
	}

	public void setNuevaclave(String nuevaclave) {
		this.nuevaclave = nuevaclave;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClavessapId))
			return false;
		ClavessapId castOther = (ClavessapId) other;

		return ((this.getCampo() == castOther.getCampo()) || (this.getCampo() != null && castOther.getCampo() != null
				&& this.getCampo().equals(castOther.getCampo())))
				&& ((this.getClave() == castOther.getClave()) || (this.getClave() != null
						&& castOther.getClave() != null && this.getClave().equals(castOther.getClave())))
				&& ((this.getNuevaclave() == castOther.getNuevaclave()) || (this.getNuevaclave() != null
						&& castOther.getNuevaclave() != null && this.getNuevaclave().equals(castOther.getNuevaclave())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCampo() == null ? 0 : this.getCampo().hashCode());
		result = 37 * result + (getClave() == null ? 0 : this.getClave().hashCode());
		result = 37 * result + (getNuevaclave() == null ? 0 : this.getNuevaclave().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		return result;
	}

}
