package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Clavessap generated by hbm2java
 */
@Entity
@Table(name = "CLAVESSAP")
public class Clavessap implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private ClavessapId id;

	public Clavessap() {
	}

	public Clavessap(ClavessapId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "campo", column = @Column(name = "CAMPO", length = 25) ),
			@AttributeOverride(name = "clave", column = @Column(name = "CLAVE", length = 50) ),
			@AttributeOverride(name = "nuevaclave", column = @Column(name = "NUEVACLAVE", length = 50) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ) })
	public ClavessapId getId() {
		return this.id;
	}

	public void setId(ClavessapId id) {
		this.id = id;
	}

}
