package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClLotesCertificados generated by hbm2java
 */
@Entity
@Table(name = "CL_LOTES_CERTIFICADOS", schema = "CERTREG")
public class ClLotesCertificados implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private ClLotesCertificadosId id;

	public ClLotesCertificados() {
	}

	public ClLotesCertificados(ClLotesCertificadosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idLote", column = @Column(name = "ID_LOTE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "numtarjetaInicia", column = @Column(name = "NUMTARJETA_INICIA", precision = 22, scale = 0) ),
			@AttributeOverride(name = "numtarjetaFinaliza", column = @Column(name = "NUMTARJETA_FINALIZA", precision = 22, scale = 0) ),
			@AttributeOverride(name = "monto", column = @Column(name = "MONTO", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "FECHA_CREACION", length = 7) ),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 100) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 5) ) })
	public ClLotesCertificadosId getId() {
		return this.id;
	}

	public void setId(ClLotesCertificadosId id) {
		this.id = id;
	}

}
