package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClLotesCertificadosId generated by hbm2java
 */
@Embeddable
public class ClLotesCertificadosId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigDecimal idLote;
	private BigDecimal numtarjetaInicia;
	private BigDecimal numtarjetaFinaliza;
	private BigDecimal monto;
	private Date fechaCreacion;
	private String usuario;
	private String region;

	public ClLotesCertificadosId() {
	}

	public ClLotesCertificadosId(BigDecimal idLote, BigDecimal numtarjetaInicia, BigDecimal numtarjetaFinaliza,
			BigDecimal monto, Date fechaCreacion, String usuario, String region) {
		this.idLote = idLote;
		this.numtarjetaInicia = numtarjetaInicia;
		this.numtarjetaFinaliza = numtarjetaFinaliza;
		this.monto = monto;
		this.fechaCreacion = fechaCreacion;
		this.usuario = usuario;
		this.region = region;
	}

	@Column(name = "ID_LOTE", precision = 22, scale = 0)
	public BigDecimal getIdLote() {
		return this.idLote;
	}

	public void setIdLote(BigDecimal idLote) {
		this.idLote = idLote;
	}

	@Column(name = "NUMTARJETA_INICIA", precision = 22, scale = 0)
	public BigDecimal getNumtarjetaInicia() {
		return this.numtarjetaInicia;
	}

	public void setNumtarjetaInicia(BigDecimal numtarjetaInicia) {
		this.numtarjetaInicia = numtarjetaInicia;
	}

	@Column(name = "NUMTARJETA_FINALIZA", precision = 22, scale = 0)
	public BigDecimal getNumtarjetaFinaliza() {
		return this.numtarjetaFinaliza;
	}

	public void setNumtarjetaFinaliza(BigDecimal numtarjetaFinaliza) {
		this.numtarjetaFinaliza = numtarjetaFinaliza;
	}

	@Column(name = "MONTO", precision = 22, scale = 0)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "FECHA_CREACION", length = 7)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "USUARIO", length = 100)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "REGION", length = 5)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClLotesCertificadosId))
			return false;
		ClLotesCertificadosId castOther = (ClLotesCertificadosId) other;

		return ((this.getIdLote() == castOther.getIdLote()) || (this.getIdLote() != null
				&& castOther.getIdLote() != null && this.getIdLote().equals(castOther.getIdLote())))
				&& ((this.getNumtarjetaInicia() == castOther.getNumtarjetaInicia())
						|| (this.getNumtarjetaInicia() != null && castOther.getNumtarjetaInicia() != null
								&& this.getNumtarjetaInicia().equals(castOther.getNumtarjetaInicia())))
				&& ((this.getNumtarjetaFinaliza() == castOther.getNumtarjetaFinaliza())
						|| (this.getNumtarjetaFinaliza() != null && castOther.getNumtarjetaFinaliza() != null
								&& this.getNumtarjetaFinaliza().equals(castOther.getNumtarjetaFinaliza())))
				&& ((this.getMonto() == castOther.getMonto()) || (this.getMonto() != null
						&& castOther.getMonto() != null && this.getMonto().equals(castOther.getMonto())))
				&& ((this.getFechaCreacion() == castOther.getFechaCreacion())
						|| (this.getFechaCreacion() != null && castOther.getFechaCreacion() != null
								&& this.getFechaCreacion().equals(castOther.getFechaCreacion())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
						&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdLote() == null ? 0 : this.getIdLote().hashCode());
		result = 37 * result + (getNumtarjetaInicia() == null ? 0 : this.getNumtarjetaInicia().hashCode());
		result = 37 * result + (getNumtarjetaFinaliza() == null ? 0 : this.getNumtarjetaFinaliza().hashCode());
		result = 37 * result + (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37 * result + (getFechaCreacion() == null ? 0 : this.getFechaCreacion().hashCode());
		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		return result;
	}

}
