package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Diagnostico generated by hbm2java
 */
@Entity
@Table(name = "DIAGNOSTICO")
public class Diagnostico implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private DiagnosticoId id;

	public Diagnostico() {
	}

	public Diagnostico(DiagnosticoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "folio", column = @Column(name = "FOLIO", nullable = false, length = 13) ),
			@AttributeOverride(name = "idfalla", column = @Column(name = "IDFALLA", precision = 4, scale = 0) ),
			@AttributeOverride(name = "diagnostico", column = @Column(name = "DIAGNOSTICO") ),
			@AttributeOverride(name = "usuariodiagnostico", column = @Column(name = "USUARIODIAGNOSTICO", length = 7) ),
			@AttributeOverride(name = "fechadiagnostico", column = @Column(name = "FECHADIAGNOSTICO", length = 7) ),
			@AttributeOverride(name = "idgarantia", column = @Column(name = "IDGARANTIA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "comengarantia", column = @Column(name = "COMENGARANTIA", length = 100) ),
			@AttributeOverride(name = "fallafuerac", column = @Column(name = "FALLAFUERAC", length = 1) ),
			@AttributeOverride(name = "fechafueracaja", column = @Column(name = "FECHAFUERACAJA", length = 7) ),
			@AttributeOverride(name = "idincumplimiento", column = @Column(name = "IDINCUMPLIMIENTO", precision = 2, scale = 0) ),
			@AttributeOverride(name = "fechaincumplimient", column = @Column(name = "FECHAINCUMPLIMIENT", length = 7) ),
			@AttributeOverride(name = "idcsa", column = @Column(name = "IDCSA", precision = 4, scale = 0) ),
			@AttributeOverride(name = "nommensajero", column = @Column(name = "NOMMENSAJERO", length = 100) ),
			@AttributeOverride(name = "fechaenvio", column = @Column(name = "FECHAENVIO", length = 7) ),
			@AttributeOverride(name = "noguia", column = @Column(name = "NOGUIA", length = 30) ),
			@AttributeOverride(name = "costocotizacion", column = @Column(name = "COSTOCOTIZACION", precision = 6) ),
			@AttributeOverride(name = "idreincidencia", column = @Column(name = "IDREINCIDENCIA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "diascompensacion", column = @Column(name = "DIASCOMPENSACION", precision = 2, scale = 0) ),
			@AttributeOverride(name = "fecharecepcioncsa", column = @Column(name = "FECHARECEPCIONCSA", length = 7) ),
			@AttributeOverride(name = "reparacion", column = @Column(name = "REPARACION") ),
			@AttributeOverride(name = "tiporeparacion", column = @Column(name = "TIPOREPARACION", precision = 3, scale = 0) ),
			@AttributeOverride(name = "fechareparacion", column = @Column(name = "FECHAREPARACION", length = 7) ),
			@AttributeOverride(name = "facturareparacion", column = @Column(name = "FACTURAREPARACION", length = 15) ),
			@AttributeOverride(name = "costo", column = @Column(name = "COSTO", precision = 6) ),
			@AttributeOverride(name = "repexpress", column = @Column(name = "REPEXPRESS", length = 1) ),
			@AttributeOverride(name = "nuevoesnimei", column = @Column(name = "NUEVOESNIMEI", length = 15) ),
			@AttributeOverride(name = "revcontrol", column = @Column(name = "REVCONTROL", length = 1) ),
			@AttributeOverride(name = "fecharecepcion", column = @Column(name = "FECHARECEPCION", length = 7) ),
			@AttributeOverride(name = "fecharevision", column = @Column(name = "FECHAREVISION", length = 7) ),
			@AttributeOverride(name = "nomasesorentrega", column = @Column(name = "NOMASESORENTREGA", length = 60) ),
			@AttributeOverride(name = "usuariorepara", column = @Column(name = "USUARIOREPARA", length = 7) ),
			@AttributeOverride(name = "accesorioscsa", column = @Column(name = "ACCESORIOSCSA", length = 100) ),
			@AttributeOverride(name = "usuarioenvia", column = @Column(name = "USUARIOENVIA", length = 7) ),
			@AttributeOverride(name = "costoiva", column = @Column(name = "COSTOIVA", precision = 6) ),
			@AttributeOverride(name = "userentrega", column = @Column(name = "USERENTREGA", length = 7) ),
			@AttributeOverride(name = "idcsa2", column = @Column(name = "IDCSA2", precision = 4, scale = 0) ),
			@AttributeOverride(name = "noguia2", column = @Column(name = "NOGUIA2", length = 30) ),
			@AttributeOverride(name = "fechaenvio2", column = @Column(name = "FECHAENVIO2", length = 7) ),
			@AttributeOverride(name = "nomensajero2", column = @Column(name = "NOMENSAJERO2", length = 60) ),
			@AttributeOverride(name = "fecharecepcioncsa2", column = @Column(name = "FECHARECEPCIONCSA2", length = 7) ),
			@AttributeOverride(name = "diascompensacion2", column = @Column(name = "DIASCOMPENSACION2", precision = 2, scale = 0) ),
			@AttributeOverride(name = "accesorioscsa2", column = @Column(name = "ACCESORIOSCSA2", length = 100) ),
			@AttributeOverride(name = "idreincidencia2", column = @Column(name = "IDREINCIDENCIA2", precision = 3, scale = 0) ),
			@AttributeOverride(name = "usuarioenvia2", column = @Column(name = "USUARIOENVIA2", length = 7) ),
			@AttributeOverride(name = "fecharecepcion2", column = @Column(name = "FECHARECEPCION2", length = 7) ),
			@AttributeOverride(name = "causanoentrega", column = @Column(name = "CAUSANOENTREGA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "enviadoadesc", column = @Column(name = "ENVIADOADESC", precision = 1, scale = 0) ),
			@AttributeOverride(name = "folioecac", column = @Column(name = "FOLIOECAC", precision = 10, scale = 0) ),
			@AttributeOverride(name = "fallas", column = @Column(name = "FALLAS", length = 100) ),
			@AttributeOverride(name = "producto8", column = @Column(name = "PRODUCTO8", precision = 2, scale = 0) ),
			@AttributeOverride(name = "seriepin", column = @Column(name = "SERIEPIN", length = 14) ),
			@AttributeOverride(name = "facturareparacion2", column = @Column(name = "FACTURAREPARACION2", length = 15) ),
			@AttributeOverride(name = "folioecac2", column = @Column(name = "FOLIOECAC2", precision = 10, scale = 0) ),
			@AttributeOverride(name = "idoficinadeventasr", column = @Column(name = "IDOFICINADEVENTASR", length = 4) ),
			@AttributeOverride(name = "nommensajeror", column = @Column(name = "NOMMENSAJEROR", length = 100) ),
			@AttributeOverride(name = "fechaenvior", column = @Column(name = "FECHAENVIOR", length = 7) ),
			@AttributeOverride(name = "noguiar", column = @Column(name = "NOGUIAR", length = 30) ),
			@AttributeOverride(name = "fecharecepcioncacr", column = @Column(name = "FECHARECEPCIONCACR", length = 7) ),
			@AttributeOverride(name = "usuarioenviacacr", column = @Column(name = "USUARIOENVIACACR", length = 7) ) })
	public DiagnosticoId getId() {
		return this.id;
	}

	public void setId(DiagnosticoId id) {
		this.id = id;
	}

}
