package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Equipodeprestamo generated by hbm2java
 */
@Entity
@Table(name = "EQUIPODEPRESTAMO", schema = "CERTREG")
public class Equipodeprestamo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private EquipodeprestamoId id;

	public Equipodeprestamo() {
	}

	public Equipodeprestamo(EquipodeprestamoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idequipodeprestamo", column = @Column(name = "IDEQUIPODEPRESTAMO", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "idestatusprestamo", column = @Column(name = "IDESTATUSPRESTAMO", precision = 6, scale = 0) ),
			@AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", length = 30) ),
			@AttributeOverride(name = "cvemodelo", column = @Column(name = "CVEMODELO", length = 30) ),
			@AttributeOverride(name = "plataforma", column = @Column(name = "PLATAFORMA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "costo", column = @Column(name = "COSTO", precision = 6) ),
			@AttributeOverride(name = "esnimei", column = @Column(name = "ESNIMEI", length = 15) ),
			@AttributeOverride(name = "tipotel", column = @Column(name = "TIPOTEL", precision = 3, scale = 0) ),
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", length = 4) ),
			@AttributeOverride(name = "idantena", column = @Column(name = "IDANTENA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "idcarcaza", column = @Column(name = "IDCARCAZA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "iddisplay", column = @Column(name = "IDDISPLAY", precision = 3, scale = 0) ),
			@AttributeOverride(name = "idteclado", column = @Column(name = "IDTECLADO", precision = 3, scale = 0) ),
			@AttributeOverride(name = "descedofisico", column = @Column(name = "DESCEDOFISICO", length = 100) ),
			@AttributeOverride(name = "fechaalta", column = @Column(name = "FECHAALTA", length = 7) ),
			@AttributeOverride(name = "usuariocrea", column = @Column(name = "USUARIOCREA", length = 7) ),
			@AttributeOverride(name = "accesorios", column = @Column(name = "ACCESORIOS", length = 100) ) })
	public EquipodeprestamoId getId() {
		return this.id;
	}

	public void setId(EquipodeprestamoId id) {
		this.id = id;
	}

}
