package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EsporadicooficinadeventaId generated by hbm2java
 */
@Embeddable
public class EsporadicooficinadeventaId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String cveesporadico;
	private String cveoficinadeventas;
	private Boolean activo;

	public EsporadicooficinadeventaId() {
	}

	public EsporadicooficinadeventaId(String cveesporadico, String cveoficinadeventas) {
		this.cveesporadico = cveesporadico;
		this.cveoficinadeventas = cveoficinadeventas;
	}

	public EsporadicooficinadeventaId(String cveesporadico, String cveoficinadeventas, Boolean activo) {
		this.cveesporadico = cveesporadico;
		this.cveoficinadeventas = cveoficinadeventas;
		this.activo = activo;
	}

	@Column(name = "CVEESPORADICO", nullable = false, length = 10)
	public String getCveesporadico() {
		return this.cveesporadico;
	}

	public void setCveesporadico(String cveesporadico) {
		this.cveesporadico = cveesporadico;
	}

	@Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4)
	public String getCveoficinadeventas() {
		return this.cveoficinadeventas;
	}

	public void setCveoficinadeventas(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EsporadicooficinadeventaId))
			return false;
		EsporadicooficinadeventaId castOther = (EsporadicooficinadeventaId) other;

		return ((this.getCveesporadico() == castOther.getCveesporadico())
				|| (this.getCveesporadico() != null && castOther.getCveesporadico() != null
						&& this.getCveesporadico().equals(castOther.getCveesporadico())))
				&& ((this.getCveoficinadeventas() == castOther.getCveoficinadeventas())
						|| (this.getCveoficinadeventas() != null && castOther.getCveoficinadeventas() != null
								&& this.getCveoficinadeventas().equals(castOther.getCveoficinadeventas())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveesporadico() == null ? 0 : this.getCveesporadico().hashCode());
		result = 37 * result + (getCveoficinadeventas() == null ? 0 : this.getCveoficinadeventas().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
