package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Esporadicooficinadeventa generated by hbm2java
 */
@Entity
@Table(name = "ESPORADICOOFICINADEVENTA", schema = "CERTREG")
public class Esporadicooficinadeventa implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private EsporadicooficinadeventaId id;

	public Esporadicooficinadeventa() {
	}

	public Esporadicooficinadeventa(EsporadicooficinadeventaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveesporadico", column = @Column(name = "CVEESPORADICO", nullable = false, length = 10) ),
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0) ) })
	public EsporadicooficinadeventaId getId() {
		return this.id;
	}

	public void setId(EsporadicooficinadeventaId id) {
		this.id = id;
	}

}
