package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstatuspermisoId generated by hbm2java
 */
@Embeddable
public class EstatuspermisoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idestatus;
	private int idpermiso;
	private Boolean activo;

	public EstatuspermisoId() {
	}

	public EstatuspermisoId(int idestatus, int idpermiso) {
		this.idestatus = idestatus;
		this.idpermiso = idpermiso;
	}

	public EstatuspermisoId(int idestatus, int idpermiso, Boolean activo) {
		this.idestatus = idestatus;
		this.idpermiso = idpermiso;
		this.activo = activo;
	}

	@Column(name = "IDESTATUS", nullable = false, precision = 6, scale = 0)
	public int getIdestatus() {
		return this.idestatus;
	}

	public void setIdestatus(int idestatus) {
		this.idestatus = idestatus;
	}

	@Column(name = "IDPERMISO", nullable = false, precision = 6, scale = 0)
	public int getIdpermiso() {
		return this.idpermiso;
	}

	public void setIdpermiso(int idpermiso) {
		this.idpermiso = idpermiso;
	}

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstatuspermisoId))
			return false;
		EstatuspermisoId castOther = (EstatuspermisoId) other;

		return (this.getIdestatus() == castOther.getIdestatus()) && (this.getIdpermiso() == castOther.getIdpermiso())
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdestatus();
		result = 37 * result + this.getIdpermiso();
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
