package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EvaluacionId generated by hbm2java
 */
@Embeddable
public class EvaluacionId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idevaluacion;
	private String cveoficinadeventas;
	private Byte mes;
	private Integer anio;
	private String usersup;
	private String usercalif;
	private Byte intentos;
	private Date fechaevaluacion;

	public EvaluacionId() {
	}

	public EvaluacionId(int idevaluacion) {
		this.idevaluacion = idevaluacion;
	}

	public EvaluacionId(int idevaluacion, String cveoficinadeventas, Byte mes, Integer anio, String usersup,
			String usercalif, Byte intentos, Date fechaevaluacion) {
		this.idevaluacion = idevaluacion;
		this.cveoficinadeventas = cveoficinadeventas;
		this.mes = mes;
		this.anio = anio;
		this.usersup = usersup;
		this.usercalif = usercalif;
		this.intentos = intentos;
		this.fechaevaluacion = fechaevaluacion;
	}

	@Column(name = "IDEVALUACION", nullable = false, precision = 6, scale = 0)
	public int getIdevaluacion() {
		return this.idevaluacion;
	}

	public void setIdevaluacion(int idevaluacion) {
		this.idevaluacion = idevaluacion;
	}

	@Column(name = "CVEOFICINADEVENTAS", length = 4)
	public String getCveoficinadeventas() {
		return this.cveoficinadeventas;
	}

	public void setCveoficinadeventas(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	@Column(name = "MES", precision = 2, scale = 0)
	public Byte getMes() {
		return this.mes;
	}

	public void setMes(Byte mes) {
		this.mes = mes;
	}

	@Column(name = "ANIO", precision = 6, scale = 0)
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "USERSUP", length = 7)
	public String getUsersup() {
		return this.usersup;
	}

	public void setUsersup(String usersup) {
		this.usersup = usersup;
	}

	@Column(name = "USERCALIF", length = 7)
	public String getUsercalif() {
		return this.usercalif;
	}

	public void setUsercalif(String usercalif) {
		this.usercalif = usercalif;
	}

	@Column(name = "INTENTOS", precision = 2, scale = 0)
	public Byte getIntentos() {
		return this.intentos;
	}

	public void setIntentos(Byte intentos) {
		this.intentos = intentos;
	}

	@Column(name = "FECHAEVALUACION", length = 7)
	public Date getFechaevaluacion() {
		return this.fechaevaluacion;
	}

	public void setFechaevaluacion(Date fechaevaluacion) {
		this.fechaevaluacion = fechaevaluacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvaluacionId))
			return false;
		EvaluacionId castOther = (EvaluacionId) other;

		return (this.getIdevaluacion() == castOther.getIdevaluacion())
				&& ((this.getCveoficinadeventas() == castOther.getCveoficinadeventas())
						|| (this.getCveoficinadeventas() != null && castOther.getCveoficinadeventas() != null
								&& this.getCveoficinadeventas().equals(castOther.getCveoficinadeventas())))
				&& ((this.getMes() == castOther.getMes()) || (this.getMes() != null && castOther.getMes() != null
						&& this.getMes().equals(castOther.getMes())))
				&& ((this.getAnio() == castOther.getAnio()) || (this.getAnio() != null && castOther.getAnio() != null
						&& this.getAnio().equals(castOther.getAnio())))
				&& ((this.getUsersup() == castOther.getUsersup()) || (this.getUsersup() != null
						&& castOther.getUsersup() != null && this.getUsersup().equals(castOther.getUsersup())))
				&& ((this.getUsercalif() == castOther.getUsercalif()) || (this.getUsercalif() != null
						&& castOther.getUsercalif() != null && this.getUsercalif().equals(castOther.getUsercalif())))
				&& ((this.getIntentos() == castOther.getIntentos()) || (this.getIntentos() != null
						&& castOther.getIntentos() != null && this.getIntentos().equals(castOther.getIntentos())))
				&& ((this.getFechaevaluacion() == castOther.getFechaevaluacion())
						|| (this.getFechaevaluacion() != null && castOther.getFechaevaluacion() != null
								&& this.getFechaevaluacion().equals(castOther.getFechaevaluacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdevaluacion();
		result = 37 * result + (getCveoficinadeventas() == null ? 0 : this.getCveoficinadeventas().hashCode());
		result = 37 * result + (getMes() == null ? 0 : this.getMes().hashCode());
		result = 37 * result + (getAnio() == null ? 0 : this.getAnio().hashCode());
		result = 37 * result + (getUsersup() == null ? 0 : this.getUsersup().hashCode());
		result = 37 * result + (getUsercalif() == null ? 0 : this.getUsercalif().hashCode());
		result = 37 * result + (getIntentos() == null ? 0 : this.getIntentos().hashCode());
		result = 37 * result + (getFechaevaluacion() == null ? 0 : this.getFechaevaluacion().hashCode());
		return result;
	}

}
