package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlujosId generated by hbm2java
 */
@Embeddable
public class FlujosId implements java.io.Serializable {

	private int idestatus;
	private String estatussig;
	private String idsec;
	private String estatusant;

	public FlujosId() {
	}

	public FlujosId(int idestatus) {
		this.idestatus = idestatus;
	}

	public FlujosId(int idestatus, String estatussig, String idsec, String estatusant) {
		this.idestatus = idestatus;
		this.estatussig = estatussig;
		this.idsec = idsec;
		this.estatusant = estatusant;
	}

	@Column(name = "IDESTATUS", nullable = false, precision = 6, scale = 0)
	public int getIdestatus() {
		return this.idestatus;
	}

	public void setIdestatus(int idestatus) {
		this.idestatus = idestatus;
	}

	@Column(name = "ESTATUSSIG", length = 80)
	public String getEstatussig() {
		return this.estatussig;
	}

	public void setEstatussig(String estatussig) {
		this.estatussig = estatussig;
	}

	@Column(name = "IDSEC", length = 6)
	public String getIdsec() {
		return this.idsec;
	}

	public void setIdsec(String idsec) {
		this.idsec = idsec;
	}

	@Column(name = "ESTATUSANT", length = 80)
	public String getEstatusant() {
		return this.estatusant;
	}

	public void setEstatusant(String estatusant) {
		this.estatusant = estatusant;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlujosId))
			return false;
		FlujosId castOther = (FlujosId) other;

		return (this.getIdestatus() == castOther.getIdestatus())
				&& ((this.getEstatussig() == castOther.getEstatussig()) || (this.getEstatussig() != null
						&& castOther.getEstatussig() != null && this.getEstatussig().equals(castOther.getEstatussig())))
				&& ((this.getIdsec() == castOther.getIdsec()) || (this.getIdsec() != null
						&& castOther.getIdsec() != null && this.getIdsec().equals(castOther.getIdsec())))
				&& ((this.getEstatusant() == castOther.getEstatusant())
						|| (this.getEstatusant() != null && castOther.getEstatusant() != null
								&& this.getEstatusant().equals(castOther.getEstatusant())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdestatus();
		result = 37 * result + (getEstatussig() == null ? 0 : this.getEstatussig().hashCode());
		result = 37 * result + (getIdsec() == null ? 0 : this.getIdsec().hashCode());
		result = 37 * result + (getEstatusant() == null ? 0 : this.getEstatusant().hashCode());
		return result;
	}

}
