package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Flujos generated by hbm2java
 */
@Entity
@Table(name = "FLUJOS")
public class Flujos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private FlujosId id;

	public Flujos() {
	}

	public Flujos(FlujosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idestatus", column = @Column(name = "IDESTATUS", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "estatussig", column = @Column(name = "ESTATUSSIG", length = 80) ),
			@AttributeOverride(name = "idsec", column = @Column(name = "IDSEC", length = 6) ),
			@AttributeOverride(name = "estatusant", column = @Column(name = "ESTATUSANT", length = 80) ) })
	public FlujosId getId() {
		return this.id;
	}

	public void setId(FlujosId id) {
		this.id = id;
	}

}
