package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Foliosmasivos generated by hbm2java
 */
@Entity
@Table(name = "FOLIOSMASIVOS", schema = "CERTREG")
public class Foliosmasivos implements java.io.Serializable {

	private FoliosmasivosId id;

	public Foliosmasivos() {
	}

	public Foliosmasivos(FoliosmasivosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "foliomasivo", column = @Column(name = "FOLIOMASIVO", nullable = false, length = 16) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 2) ),
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", length = 4) ),
			@AttributeOverride(name = "numequipos", column = @Column(name = "NUMEQUIPOS", precision = 4, scale = 0) ),
			@AttributeOverride(name = "fechaalta", column = @Column(name = "FECHAALTA", length = 7) ),
			@AttributeOverride(name = "usuarioalta", column = @Column(name = "USUARIOALTA", length = 7) ),
			@AttributeOverride(name = "indicador", column = @Column(name = "INDICADOR", precision = 1, scale = 0) ) })
	public FoliosmasivosId getId() {
		return this.id;
	}

	public void setId(FoliosmasivosId id) {
		this.id = id;
	}

}
