package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Folios generated by hbm2java
 */
@Entity
@Table(name = "FOLIOS", schema = "CERTREG")
public class Folios implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private FoliosId id;

	public Folios() {
	}

	public Folios(FoliosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "folio", column = @Column(name = "FOLIO", nullable = false, length = 13) ),
			@AttributeOverride(name = "nip", column = @Column(name = "NIP", precision = 6, scale = 0) ),
			@AttributeOverride(name = "idestatus", column = @Column(name = "IDESTATUS", precision = 6, scale = 0) ),
			@AttributeOverride(name = "esnimei", column = @Column(name = "ESNIMEI", length = 18) ),
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", length = 4) ),
			@AttributeOverride(name = "region", column = @Column(name = "REGION", length = 2) ),
			@AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", length = 30) ),
			@AttributeOverride(name = "cvemodelo", column = @Column(name = "CVEMODELO", length = 100) ),
			@AttributeOverride(name = "plataforma", column = @Column(name = "PLATAFORMA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "vendido", column = @Column(name = "VENDIDO", length = 60) ),
			@AttributeOverride(name = "fechafacturacion", column = @Column(name = "FECHAFACTURACION", length = 7) ),
			@AttributeOverride(name = "estatusserie", column = @Column(name = "ESTATUSSERIE", length = 60) ),
			@AttributeOverride(name = "numfactura", column = @Column(name = "NUMFACTURA", length = 10) ),
			@AttributeOverride(name = "cveproveedor", column = @Column(name = "CVEPROVEEDOR", length = 30) ),
			@AttributeOverride(name = "comentariosap", column = @Column(name = "COMENTARIOSAP", length = 60) ),
			@AttributeOverride(name = "telefono", column = @Column(name = "TELEFONO", length = 10) ),
			@AttributeOverride(name = "regiontel", column = @Column(name = "REGIONTEL", precision = 2, scale = 0) ),
			@AttributeOverride(name = "iddistribuidor", column = @Column(name = "IDDISTRIBUIDOR", precision = 4, scale = 0) ),
			@AttributeOverride(name = "idtipocliente", column = @Column(name = "IDTIPOCLIENTE", precision = 3, scale = 0) ),
			@AttributeOverride(name = "cliente", column = @Column(name = "CLIENTE", length = 100) ),
			@AttributeOverride(name = "fechaactivacion", column = @Column(name = "FECHAACTIVACION", length = 7) ),
			@AttributeOverride(name = "telcon1", column = @Column(name = "TELCON1", length = 15) ),
			@AttributeOverride(name = "telcon2", column = @Column(name = "TELCON2", length = 15) ),
			@AttributeOverride(name = "ext1", column = @Column(name = "EXT1", length = 7) ),
			@AttributeOverride(name = "ext2", column = @Column(name = "EXT2", length = 7) ),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", length = 120) ),
			@AttributeOverride(name = "iccid", column = @Column(name = "ICCID", length = 19) ),
			@AttributeOverride(name = "falla", column = @Column(name = "FALLA") ),
			@AttributeOverride(name = "accesorios", column = @Column(name = "ACCESORIOS", length = 200) ),
			@AttributeOverride(name = "nota", column = @Column(name = "NOTA", length = 60) ),
			@AttributeOverride(name = "idequipodeprestamo", column = @Column(name = "IDEQUIPODEPRESTAMO", precision = 6, scale = 0) ),
			@AttributeOverride(name = "fechaprestamo", column = @Column(name = "FECHAPRESTAMO", length = 7) ),
			@AttributeOverride(name = "usuarioprestamo", column = @Column(name = "USUARIOPRESTAMO", length = 7) ),
			@AttributeOverride(name = "fechadevolucion", column = @Column(name = "FECHADEVOLUCION", length = 7) ),
			@AttributeOverride(name = "fechaentrega", column = @Column(name = "FECHAENTREGA", length = 7) ),
			@AttributeOverride(name = "usuarioentrega", column = @Column(name = "USUARIOENTREGA", length = 7) ),
			@AttributeOverride(name = "idantena", column = @Column(name = "IDANTENA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "idcarcaza", column = @Column(name = "IDCARCAZA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "iddisplay", column = @Column(name = "IDDISPLAY", precision = 3, scale = 0) ),
			@AttributeOverride(name = "idteclado", column = @Column(name = "IDTECLADO", precision = 3, scale = 0) ),
			@AttributeOverride(name = "descedofisico", column = @Column(name = "DESCEDOFISICO") ),
			@AttributeOverride(name = "fechaalta", column = @Column(name = "FECHAALTA", length = 7) ),
			@AttributeOverride(name = "usuarioalta", column = @Column(name = "USUARIOALTA", length = 7) ),
			@AttributeOverride(name = "nombrefacturasap", column = @Column(name = "NOMBREFACTURASAP", length = 100) ),
			@AttributeOverride(name = "foliopadre", column = @Column(name = "FOLIOPADRE", length = 13) ),
			@AttributeOverride(name = "foliomasivo", column = @Column(name = "FOLIOMASIVO", length = 16) ),
			@AttributeOverride(name = "epoprestamocsa", column = @Column(name = "EPOPRESTAMOCSA", length = 100) ),
			@AttributeOverride(name = "cacseguimiento", column = @Column(name = "CACSEGUIMIENTO", length = 4) ),
			@AttributeOverride(name = "material", column = @Column(name = "MATERIAL", length = 70) ),
			@AttributeOverride(name = "almacen", column = @Column(name = "ALMACEN", length = 55) ),
			@AttributeOverride(name = "mat9000", column = @Column(name = "MAT9000", length = 20) ) })
	public FoliosId getId() {
		return this.id;
	}

	public void setId(FoliosId id) {
		this.id = id;
	}

}
