package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FoliosId generated by hbm2java
 */
@Embeddable
public class FoliosId implements java.io.Serializable {

	private String folio;
	private Integer nip;
	private Integer idestatus;
	private String esnimei;
	private String cveoficinadeventas;
	private String region;
	private String cvemarca;
	private String cvemodelo;
	private Short plataforma;
	private String vendido;
	private Date fechafacturacion;
	private String estatusserie;
	private String numfactura;
	private String cveproveedor;
	private String comentariosap;
	private String telefono;
	private Byte regiontel;
	private Short iddistribuidor;
	private Short idtipocliente;
	private String cliente;
	private Date fechaactivacion;
	private String telcon1;
	private String telcon2;
	private String ext1;
	private String ext2;
	private String email;
	private String iccid;
	private String falla;
	private String accesorios;
	private String nota;
	private Integer idequipodeprestamo;
	private Date fechaprestamo;
	private String usuarioprestamo;
	private Date fechadevolucion;
	private Date fechaentrega;
	private String usuarioentrega;
	private Short idantena;
	private Short idcarcaza;
	private Short iddisplay;
	private Short idteclado;
	private String descedofisico;
	private Date fechaalta;
	private String usuarioalta;
	private String nombrefacturasap;
	private String foliopadre;
	private String foliomasivo;
	private String epoprestamocsa;
	private String cacseguimiento;
	private String material;
	private String almacen;
	private String mat9000;

	public FoliosId() {
	}

	public FoliosId(String folio) {
		this.folio = folio;
	}

	public FoliosId(String folio, Integer nip, Integer idestatus, String esnimei, String cveoficinadeventas,
			String region, String cvemarca, String cvemodelo, Short plataforma, String vendido, Date fechafacturacion,
			String estatusserie, String numfactura, String cveproveedor, String comentariosap, String telefono,
			Byte regiontel, Short iddistribuidor, Short idtipocliente, String cliente, Date fechaactivacion,
			String telcon1, String telcon2, String ext1, String ext2, String email, String iccid, String falla,
			String accesorios, String nota, Integer idequipodeprestamo, Date fechaprestamo, String usuarioprestamo,
			Date fechadevolucion, Date fechaentrega, String usuarioentrega, Short idantena, Short idcarcaza,
			Short iddisplay, Short idteclado, String descedofisico, Date fechaalta, String usuarioalta,
			String nombrefacturasap, String foliopadre, String foliomasivo, String epoprestamocsa,
			String cacseguimiento, String material, String almacen, String mat9000) {
		this.folio = folio;
		this.nip = nip;
		this.idestatus = idestatus;
		this.esnimei = esnimei;
		this.cveoficinadeventas = cveoficinadeventas;
		this.region = region;
		this.cvemarca = cvemarca;
		this.cvemodelo = cvemodelo;
		this.plataforma = plataforma;
		this.vendido = vendido;
		this.fechafacturacion = fechafacturacion;
		this.estatusserie = estatusserie;
		this.numfactura = numfactura;
		this.cveproveedor = cveproveedor;
		this.comentariosap = comentariosap;
		this.telefono = telefono;
		this.regiontel = regiontel;
		this.iddistribuidor = iddistribuidor;
		this.idtipocliente = idtipocliente;
		this.cliente = cliente;
		this.fechaactivacion = fechaactivacion;
		this.telcon1 = telcon1;
		this.telcon2 = telcon2;
		this.ext1 = ext1;
		this.ext2 = ext2;
		this.email = email;
		this.iccid = iccid;
		this.falla = falla;
		this.accesorios = accesorios;
		this.nota = nota;
		this.idequipodeprestamo = idequipodeprestamo;
		this.fechaprestamo = fechaprestamo;
		this.usuarioprestamo = usuarioprestamo;
		this.fechadevolucion = fechadevolucion;
		this.fechaentrega = fechaentrega;
		this.usuarioentrega = usuarioentrega;
		this.idantena = idantena;
		this.idcarcaza = idcarcaza;
		this.iddisplay = iddisplay;
		this.idteclado = idteclado;
		this.descedofisico = descedofisico;
		this.fechaalta = fechaalta;
		this.usuarioalta = usuarioalta;
		this.nombrefacturasap = nombrefacturasap;
		this.foliopadre = foliopadre;
		this.foliomasivo = foliomasivo;
		this.epoprestamocsa = epoprestamocsa;
		this.cacseguimiento = cacseguimiento;
		this.material = material;
		this.almacen = almacen;
		this.mat9000 = mat9000;
	}

	@Column(name = "FOLIO", nullable = false, length = 13)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "NIP", precision = 6, scale = 0)
	public Integer getNip() {
		return this.nip;
	}

	public void setNip(Integer nip) {
		this.nip = nip;
	}

	@Column(name = "IDESTATUS", precision = 6, scale = 0)
	public Integer getIdestatus() {
		return this.idestatus;
	}

	public void setIdestatus(Integer idestatus) {
		this.idestatus = idestatus;
	}

	@Column(name = "ESNIMEI", length = 18)
	public String getEsnimei() {
		return this.esnimei;
	}

	public void setEsnimei(String esnimei) {
		this.esnimei = esnimei;
	}

	@Column(name = "CVEOFICINADEVENTAS", length = 4)
	public String getCveoficinadeventas() {
		return this.cveoficinadeventas;
	}

	public void setCveoficinadeventas(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	@Column(name = "REGION", length = 2)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CVEMARCA", length = 30)
	public String getCvemarca() {
		return this.cvemarca;
	}

	public void setCvemarca(String cvemarca) {
		this.cvemarca = cvemarca;
	}

	@Column(name = "CVEMODELO", length = 100)
	public String getCvemodelo() {
		return this.cvemodelo;
	}

	public void setCvemodelo(String cvemodelo) {
		this.cvemodelo = cvemodelo;
	}

	@Column(name = "PLATAFORMA", precision = 3, scale = 0)
	public Short getPlataforma() {
		return this.plataforma;
	}

	public void setPlataforma(Short plataforma) {
		this.plataforma = plataforma;
	}

	@Column(name = "VENDIDO", length = 60)
	public String getVendido() {
		return this.vendido;
	}

	public void setVendido(String vendido) {
		this.vendido = vendido;
	}

	@Column(name = "FECHAFACTURACION", length = 7)
	public Date getFechafacturacion() {
		return this.fechafacturacion;
	}

	public void setFechafacturacion(Date fechafacturacion) {
		this.fechafacturacion = fechafacturacion;
	}

	@Column(name = "ESTATUSSERIE", length = 60)
	public String getEstatusserie() {
		return this.estatusserie;
	}

	public void setEstatusserie(String estatusserie) {
		this.estatusserie = estatusserie;
	}

	@Column(name = "NUMFACTURA", length = 10)
	public String getNumfactura() {
		return this.numfactura;
	}

	public void setNumfactura(String numfactura) {
		this.numfactura = numfactura;
	}

	@Column(name = "CVEPROVEEDOR", length = 30)
	public String getCveproveedor() {
		return this.cveproveedor;
	}

	public void setCveproveedor(String cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	@Column(name = "COMENTARIOSAP", length = 60)
	public String getComentariosap() {
		return this.comentariosap;
	}

	public void setComentariosap(String comentariosap) {
		this.comentariosap = comentariosap;
	}

	@Column(name = "TELEFONO", length = 10)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "REGIONTEL", precision = 2, scale = 0)
	public Byte getRegiontel() {
		return this.regiontel;
	}

	public void setRegiontel(Byte regiontel) {
		this.regiontel = regiontel;
	}

	@Column(name = "IDDISTRIBUIDOR", precision = 4, scale = 0)
	public Short getIddistribuidor() {
		return this.iddistribuidor;
	}

	public void setIddistribuidor(Short iddistribuidor) {
		this.iddistribuidor = iddistribuidor;
	}

	@Column(name = "IDTIPOCLIENTE", precision = 3, scale = 0)
	public Short getIdtipocliente() {
		return this.idtipocliente;
	}

	public void setIdtipocliente(Short idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	@Column(name = "CLIENTE", length = 100)
	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	@Column(name = "FECHAACTIVACION", length = 7)
	public Date getFechaactivacion() {
		return this.fechaactivacion;
	}

	public void setFechaactivacion(Date fechaactivacion) {
		this.fechaactivacion = fechaactivacion;
	}

	@Column(name = "TELCON1", length = 15)
	public String getTelcon1() {
		return this.telcon1;
	}

	public void setTelcon1(String telcon1) {
		this.telcon1 = telcon1;
	}

	@Column(name = "TELCON2", length = 15)
	public String getTelcon2() {
		return this.telcon2;
	}

	public void setTelcon2(String telcon2) {
		this.telcon2 = telcon2;
	}

	@Column(name = "EXT1", length = 7)
	public String getExt1() {
		return this.ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	@Column(name = "EXT2", length = 7)
	public String getExt2() {
		return this.ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

	@Column(name = "EMAIL", length = 120)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ICCID", length = 19)
	public String getIccid() {
		return this.iccid;
	}

	public void setIccid(String iccid) {
		this.iccid = iccid;
	}

	@Column(name = "FALLA")
	public String getFalla() {
		return this.falla;
	}

	public void setFalla(String falla) {
		this.falla = falla;
	}

	@Column(name = "ACCESORIOS", length = 200)
	public String getAccesorios() {
		return this.accesorios;
	}

	public void setAccesorios(String accesorios) {
		this.accesorios = accesorios;
	}

	@Column(name = "NOTA", length = 60)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "IDEQUIPODEPRESTAMO", precision = 6, scale = 0)
	public Integer getIdequipodeprestamo() {
		return this.idequipodeprestamo;
	}

	public void setIdequipodeprestamo(Integer idequipodeprestamo) {
		this.idequipodeprestamo = idequipodeprestamo;
	}

	@Column(name = "FECHAPRESTAMO", length = 7)
	public Date getFechaprestamo() {
		return this.fechaprestamo;
	}

	public void setFechaprestamo(Date fechaprestamo) {
		this.fechaprestamo = fechaprestamo;
	}

	@Column(name = "USUARIOPRESTAMO", length = 7)
	public String getUsuarioprestamo() {
		return this.usuarioprestamo;
	}

	public void setUsuarioprestamo(String usuarioprestamo) {
		this.usuarioprestamo = usuarioprestamo;
	}

	@Column(name = "FECHADEVOLUCION", length = 7)
	public Date getFechadevolucion() {
		return this.fechadevolucion;
	}

	public void setFechadevolucion(Date fechadevolucion) {
		this.fechadevolucion = fechadevolucion;
	}

	@Column(name = "FECHAENTREGA", length = 7)
	public Date getFechaentrega() {
		return this.fechaentrega;
	}

	public void setFechaentrega(Date fechaentrega) {
		this.fechaentrega = fechaentrega;
	}

	@Column(name = "USUARIOENTREGA", length = 7)
	public String getUsuarioentrega() {
		return this.usuarioentrega;
	}

	public void setUsuarioentrega(String usuarioentrega) {
		this.usuarioentrega = usuarioentrega;
	}

	@Column(name = "IDANTENA", precision = 3, scale = 0)
	public Short getIdantena() {
		return this.idantena;
	}

	public void setIdantena(Short idantena) {
		this.idantena = idantena;
	}

	@Column(name = "IDCARCAZA", precision = 3, scale = 0)
	public Short getIdcarcaza() {
		return this.idcarcaza;
	}

	public void setIdcarcaza(Short idcarcaza) {
		this.idcarcaza = idcarcaza;
	}

	@Column(name = "IDDISPLAY", precision = 3, scale = 0)
	public Short getIddisplay() {
		return this.iddisplay;
	}

	public void setIddisplay(Short iddisplay) {
		this.iddisplay = iddisplay;
	}

	@Column(name = "IDTECLADO", precision = 3, scale = 0)
	public Short getIdteclado() {
		return this.idteclado;
	}

	public void setIdteclado(Short idteclado) {
		this.idteclado = idteclado;
	}

	@Column(name = "DESCEDOFISICO")
	public String getDescedofisico() {
		return this.descedofisico;
	}

	public void setDescedofisico(String descedofisico) {
		this.descedofisico = descedofisico;
	}

	@Column(name = "FECHAALTA", length = 7)
	public Date getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

	@Column(name = "USUARIOALTA", length = 7)
	public String getUsuarioalta() {
		return this.usuarioalta;
	}

	public void setUsuarioalta(String usuarioalta) {
		this.usuarioalta = usuarioalta;
	}

	@Column(name = "NOMBREFACTURASAP", length = 100)
	public String getNombrefacturasap() {
		return this.nombrefacturasap;
	}

	public void setNombrefacturasap(String nombrefacturasap) {
		this.nombrefacturasap = nombrefacturasap;
	}

	@Column(name = "FOLIOPADRE", length = 13)
	public String getFoliopadre() {
		return this.foliopadre;
	}

	public void setFoliopadre(String foliopadre) {
		this.foliopadre = foliopadre;
	}

	@Column(name = "FOLIOMASIVO", length = 16)
	public String getFoliomasivo() {
		return this.foliomasivo;
	}

	public void setFoliomasivo(String foliomasivo) {
		this.foliomasivo = foliomasivo;
	}

	@Column(name = "EPOPRESTAMOCSA", length = 100)
	public String getEpoprestamocsa() {
		return this.epoprestamocsa;
	}

	public void setEpoprestamocsa(String epoprestamocsa) {
		this.epoprestamocsa = epoprestamocsa;
	}

	@Column(name = "CACSEGUIMIENTO", length = 4)
	public String getCacseguimiento() {
		return this.cacseguimiento;
	}

	public void setCacseguimiento(String cacseguimiento) {
		this.cacseguimiento = cacseguimiento;
	}

	@Column(name = "MATERIAL", length = 70)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "ALMACEN", length = 55)
	public String getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(String almacen) {
		this.almacen = almacen;
	}

	@Column(name = "MAT9000", length = 20)
	public String getMat9000() {
		return this.mat9000;
	}

	public void setMat9000(String mat9000) {
		this.mat9000 = mat9000;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FoliosId))
			return false;
		FoliosId castOther = (FoliosId) other;

		return ((this.getFolio() == castOther.getFolio()) || (this.getFolio() != null && castOther.getFolio() != null
				&& this.getFolio().equals(castOther.getFolio())))
				&& ((this.getNip() == castOther.getNip()) || (this.getNip() != null && castOther.getNip() != null
						&& this.getNip().equals(castOther.getNip())))
				&& ((this.getIdestatus() == castOther.getIdestatus()) || (this.getIdestatus() != null
						&& castOther.getIdestatus() != null && this.getIdestatus().equals(castOther.getIdestatus())))
				&& ((this.getEsnimei() == castOther.getEsnimei()) || (this.getEsnimei() != null
						&& castOther.getEsnimei() != null && this.getEsnimei().equals(castOther.getEsnimei())))
				&& ((this.getCveoficinadeventas() == castOther.getCveoficinadeventas())
						|| (this.getCveoficinadeventas() != null && castOther.getCveoficinadeventas() != null
								&& this.getCveoficinadeventas().equals(castOther.getCveoficinadeventas())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getCvemarca() == castOther.getCvemarca()) || (this.getCvemarca() != null
						&& castOther.getCvemarca() != null && this.getCvemarca().equals(castOther.getCvemarca())))
				&& ((this.getCvemodelo() == castOther.getCvemodelo()) || (this.getCvemodelo() != null
						&& castOther.getCvemodelo() != null && this.getCvemodelo().equals(castOther.getCvemodelo())))
				&& ((this.getPlataforma() == castOther.getPlataforma()) || (this.getPlataforma() != null
						&& castOther.getPlataforma() != null && this.getPlataforma().equals(castOther.getPlataforma())))
				&& ((this.getVendido() == castOther.getVendido()) || (this.getVendido() != null
						&& castOther.getVendido() != null && this.getVendido().equals(castOther.getVendido())))
				&& ((this.getFechafacturacion() == castOther.getFechafacturacion())
						|| (this.getFechafacturacion() != null && castOther.getFechafacturacion() != null
								&& this.getFechafacturacion().equals(castOther.getFechafacturacion())))
				&& ((this.getEstatusserie() == castOther.getEstatusserie())
						|| (this.getEstatusserie() != null && castOther.getEstatusserie() != null
								&& this.getEstatusserie().equals(castOther.getEstatusserie())))
				&& ((this.getNumfactura() == castOther.getNumfactura()) || (this.getNumfactura() != null
						&& castOther.getNumfactura() != null && this.getNumfactura().equals(castOther.getNumfactura())))
				&& ((this.getCveproveedor() == castOther.getCveproveedor())
						|| (this.getCveproveedor() != null && castOther.getCveproveedor() != null
								&& this.getCveproveedor().equals(castOther.getCveproveedor())))
				&& ((this.getComentariosap() == castOther.getComentariosap())
						|| (this.getComentariosap() != null && castOther.getComentariosap() != null
								&& this.getComentariosap().equals(castOther.getComentariosap())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getRegiontel() == castOther.getRegiontel()) || (this.getRegiontel() != null
						&& castOther.getRegiontel() != null && this.getRegiontel().equals(castOther.getRegiontel())))
				&& ((this.getIddistribuidor() == castOther.getIddistribuidor())
						|| (this.getIddistribuidor() != null && castOther.getIddistribuidor() != null
								&& this.getIddistribuidor().equals(castOther.getIddistribuidor())))
				&& ((this.getIdtipocliente() == castOther.getIdtipocliente())
						|| (this.getIdtipocliente() != null && castOther.getIdtipocliente() != null
								&& this.getIdtipocliente().equals(castOther.getIdtipocliente())))
				&& ((this.getCliente() == castOther.getCliente()) || (this.getCliente() != null
						&& castOther.getCliente() != null && this.getCliente().equals(castOther.getCliente())))
				&& ((this.getFechaactivacion() == castOther.getFechaactivacion())
						|| (this.getFechaactivacion() != null && castOther.getFechaactivacion() != null
								&& this.getFechaactivacion().equals(castOther.getFechaactivacion())))
				&& ((this.getTelcon1() == castOther.getTelcon1()) || (this.getTelcon1() != null
						&& castOther.getTelcon1() != null && this.getTelcon1().equals(castOther.getTelcon1())))
				&& ((this.getTelcon2() == castOther.getTelcon2()) || (this.getTelcon2() != null
						&& castOther.getTelcon2() != null && this.getTelcon2().equals(castOther.getTelcon2())))
				&& ((this.getExt1() == castOther.getExt1()) || (this.getExt1() != null && castOther.getExt1() != null
						&& this.getExt1().equals(castOther.getExt1())))
				&& ((this.getExt2() == castOther.getExt2()) || (this.getExt2() != null && castOther.getExt2() != null
						&& this.getExt2().equals(castOther.getExt2())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getIccid() == castOther.getIccid()) || (this.getIccid() != null
						&& castOther.getIccid() != null && this.getIccid().equals(castOther.getIccid())))
				&& ((this.getFalla() == castOther.getFalla()) || (this.getFalla() != null
						&& castOther.getFalla() != null && this.getFalla().equals(castOther.getFalla())))
				&& ((this.getAccesorios() == castOther.getAccesorios()) || (this.getAccesorios() != null
						&& castOther.getAccesorios() != null && this.getAccesorios().equals(castOther.getAccesorios())))
				&& ((this.getNota() == castOther.getNota()) || (this.getNota() != null && castOther.getNota() != null
						&& this.getNota().equals(castOther.getNota())))
				&& ((this.getIdequipodeprestamo() == castOther.getIdequipodeprestamo())
						|| (this.getIdequipodeprestamo() != null && castOther.getIdequipodeprestamo() != null
								&& this.getIdequipodeprestamo().equals(castOther.getIdequipodeprestamo())))
				&& ((this.getFechaprestamo() == castOther.getFechaprestamo())
						|| (this.getFechaprestamo() != null && castOther.getFechaprestamo() != null
								&& this.getFechaprestamo().equals(castOther.getFechaprestamo())))
				&& ((this.getUsuarioprestamo() == castOther.getUsuarioprestamo())
						|| (this.getUsuarioprestamo() != null && castOther.getUsuarioprestamo() != null
								&& this.getUsuarioprestamo().equals(castOther.getUsuarioprestamo())))
				&& ((this.getFechadevolucion() == castOther.getFechadevolucion())
						|| (this.getFechadevolucion() != null && castOther.getFechadevolucion() != null
								&& this.getFechadevolucion().equals(castOther.getFechadevolucion())))
				&& ((this.getFechaentrega() == castOther.getFechaentrega())
						|| (this.getFechaentrega() != null && castOther.getFechaentrega() != null
								&& this.getFechaentrega().equals(castOther.getFechaentrega())))
				&& ((this.getUsuarioentrega() == castOther.getUsuarioentrega())
						|| (this.getUsuarioentrega() != null && castOther.getUsuarioentrega() != null
								&& this.getUsuarioentrega().equals(castOther.getUsuarioentrega())))
				&& ((this.getIdantena() == castOther.getIdantena()) || (this.getIdantena() != null
						&& castOther.getIdantena() != null && this.getIdantena().equals(castOther.getIdantena())))
				&& ((this.getIdcarcaza() == castOther.getIdcarcaza()) || (this.getIdcarcaza() != null
						&& castOther.getIdcarcaza() != null && this.getIdcarcaza().equals(castOther.getIdcarcaza())))
				&& ((this.getIddisplay() == castOther.getIddisplay()) || (this.getIddisplay() != null
						&& castOther.getIddisplay() != null && this.getIddisplay().equals(castOther.getIddisplay())))
				&& ((this.getIdteclado() == castOther.getIdteclado()) || (this.getIdteclado() != null
						&& castOther.getIdteclado() != null && this.getIdteclado().equals(castOther.getIdteclado())))
				&& ((this.getDescedofisico() == castOther.getDescedofisico())
						|| (this.getDescedofisico() != null && castOther.getDescedofisico() != null
								&& this.getDescedofisico().equals(castOther.getDescedofisico())))
				&& ((this.getFechaalta() == castOther.getFechaalta()) || (this.getFechaalta() != null
						&& castOther.getFechaalta() != null && this.getFechaalta().equals(castOther.getFechaalta())))
				&& ((this.getUsuarioalta() == castOther.getUsuarioalta())
						|| (this.getUsuarioalta() != null && castOther.getUsuarioalta() != null
								&& this.getUsuarioalta().equals(castOther.getUsuarioalta())))
				&& ((this.getNombrefacturasap() == castOther.getNombrefacturasap())
						|| (this.getNombrefacturasap() != null && castOther.getNombrefacturasap() != null
								&& this.getNombrefacturasap().equals(castOther.getNombrefacturasap())))
				&& ((this.getFoliopadre() == castOther.getFoliopadre()) || (this.getFoliopadre() != null
						&& castOther.getFoliopadre() != null && this.getFoliopadre().equals(castOther.getFoliopadre())))
				&& ((this.getFoliomasivo() == castOther.getFoliomasivo())
						|| (this.getFoliomasivo() != null && castOther.getFoliomasivo() != null
								&& this.getFoliomasivo().equals(castOther.getFoliomasivo())))
				&& ((this.getEpoprestamocsa() == castOther.getEpoprestamocsa())
						|| (this.getEpoprestamocsa() != null && castOther.getEpoprestamocsa() != null
								&& this.getEpoprestamocsa().equals(castOther.getEpoprestamocsa())))
				&& ((this.getCacseguimiento() == castOther.getCacseguimiento())
						|| (this.getCacseguimiento() != null && castOther.getCacseguimiento() != null
								&& this.getCacseguimiento().equals(castOther.getCacseguimiento())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null
						&& castOther.getMaterial() != null && this.getMaterial().equals(castOther.getMaterial())))
				&& ((this.getAlmacen() == castOther.getAlmacen()) || (this.getAlmacen() != null
						&& castOther.getAlmacen() != null && this.getAlmacen().equals(castOther.getAlmacen())))
				&& ((this.getMat9000() == castOther.getMat9000()) || (this.getMat9000() != null
						&& castOther.getMat9000() != null && this.getMat9000().equals(castOther.getMat9000())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result + (getNip() == null ? 0 : this.getNip().hashCode());
		result = 37 * result + (getIdestatus() == null ? 0 : this.getIdestatus().hashCode());
		result = 37 * result + (getEsnimei() == null ? 0 : this.getEsnimei().hashCode());
		result = 37 * result + (getCveoficinadeventas() == null ? 0 : this.getCveoficinadeventas().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getCvemarca() == null ? 0 : this.getCvemarca().hashCode());
		result = 37 * result + (getCvemodelo() == null ? 0 : this.getCvemodelo().hashCode());
		result = 37 * result + (getPlataforma() == null ? 0 : this.getPlataforma().hashCode());
		result = 37 * result + (getVendido() == null ? 0 : this.getVendido().hashCode());
		result = 37 * result + (getFechafacturacion() == null ? 0 : this.getFechafacturacion().hashCode());
		result = 37 * result + (getEstatusserie() == null ? 0 : this.getEstatusserie().hashCode());
		result = 37 * result + (getNumfactura() == null ? 0 : this.getNumfactura().hashCode());
		result = 37 * result + (getCveproveedor() == null ? 0 : this.getCveproveedor().hashCode());
		result = 37 * result + (getComentariosap() == null ? 0 : this.getComentariosap().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getRegiontel() == null ? 0 : this.getRegiontel().hashCode());
		result = 37 * result + (getIddistribuidor() == null ? 0 : this.getIddistribuidor().hashCode());
		result = 37 * result + (getIdtipocliente() == null ? 0 : this.getIdtipocliente().hashCode());
		result = 37 * result + (getCliente() == null ? 0 : this.getCliente().hashCode());
		result = 37 * result + (getFechaactivacion() == null ? 0 : this.getFechaactivacion().hashCode());
		result = 37 * result + (getTelcon1() == null ? 0 : this.getTelcon1().hashCode());
		result = 37 * result + (getTelcon2() == null ? 0 : this.getTelcon2().hashCode());
		result = 37 * result + (getExt1() == null ? 0 : this.getExt1().hashCode());
		result = 37 * result + (getExt2() == null ? 0 : this.getExt2().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getIccid() == null ? 0 : this.getIccid().hashCode());
		result = 37 * result + (getFalla() == null ? 0 : this.getFalla().hashCode());
		result = 37 * result + (getAccesorios() == null ? 0 : this.getAccesorios().hashCode());
		result = 37 * result + (getNota() == null ? 0 : this.getNota().hashCode());
		result = 37 * result + (getIdequipodeprestamo() == null ? 0 : this.getIdequipodeprestamo().hashCode());
		result = 37 * result + (getFechaprestamo() == null ? 0 : this.getFechaprestamo().hashCode());
		result = 37 * result + (getUsuarioprestamo() == null ? 0 : this.getUsuarioprestamo().hashCode());
		result = 37 * result + (getFechadevolucion() == null ? 0 : this.getFechadevolucion().hashCode());
		result = 37 * result + (getFechaentrega() == null ? 0 : this.getFechaentrega().hashCode());
		result = 37 * result + (getUsuarioentrega() == null ? 0 : this.getUsuarioentrega().hashCode());
		result = 37 * result + (getIdantena() == null ? 0 : this.getIdantena().hashCode());
		result = 37 * result + (getIdcarcaza() == null ? 0 : this.getIdcarcaza().hashCode());
		result = 37 * result + (getIddisplay() == null ? 0 : this.getIddisplay().hashCode());
		result = 37 * result + (getIdteclado() == null ? 0 : this.getIdteclado().hashCode());
		result = 37 * result + (getDescedofisico() == null ? 0 : this.getDescedofisico().hashCode());
		result = 37 * result + (getFechaalta() == null ? 0 : this.getFechaalta().hashCode());
		result = 37 * result + (getUsuarioalta() == null ? 0 : this.getUsuarioalta().hashCode());
		result = 37 * result + (getNombrefacturasap() == null ? 0 : this.getNombrefacturasap().hashCode());
		result = 37 * result + (getFoliopadre() == null ? 0 : this.getFoliopadre().hashCode());
		result = 37 * result + (getFoliomasivo() == null ? 0 : this.getFoliomasivo().hashCode());
		result = 37 * result + (getEpoprestamocsa() == null ? 0 : this.getEpoprestamocsa().hashCode());
		result = 37 * result + (getCacseguimiento() == null ? 0 : this.getCacseguimiento().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		result = 37 * result + (getAlmacen() == null ? 0 : this.getAlmacen().hashCode());
		result = 37 * result + (getMat9000() == null ? 0 : this.getMat9000().hashCode());
		return result;
	}

}
