package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Grupopermiso generated by hbm2java
 */
@Entity
@Table(name = "GRUPOPERMISO")
public class Grupopermiso implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private GrupopermisoId id;

	public Grupopermiso() {
	}

	public Grupopermiso(GrupopermisoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idgrupo", column = @Column(name = "IDGRUPO", nullable = false, precision = 22, scale = 0) ),
			@AttributeOverride(name = "idpermiso", column = @Column(name = "IDPERMISO", nullable = false, precision = 22, scale = 0) ) })
	public GrupopermisoId getId() {
		return this.id;
	}

	public void setId(GrupopermisoId id) {
		this.id = id;
	}

}
