package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Histestatus generated by hbm2java
 */
@Entity
@Table(name = "HISTESTATUS")
public class Histestatus implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private HistestatusId id;

	public Histestatus() {
	}

	public Histestatus(HistestatusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "folio", column = @Column(name = "FOLIO", nullable = false, length = 13) ),
			@AttributeOverride(name = "fecha", column = @Column(name = "FECHA", nullable = false, length = 7) ),
			@AttributeOverride(name = "idestatus", column = @Column(name = "IDESTATUS", precision = 6, scale = 0) ),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 7) ),
			@AttributeOverride(name = "comentario", column = @Column(name = "COMENTARIO") ) })
	public HistestatusId getId() {
		return this.id;
	}

	public void setId(HistestatusId id) {
		this.id = id;
	}

}
