package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Histcveoficinadeventas generated by hbm2java
 */
@Entity
@Table(name = "HISTCVEOFICINADEVENTAS")
public class Histcveoficinadeventas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private HistcveoficinadeventasId id;

	public Histcveoficinadeventas() {
	}

	public Histcveoficinadeventas(HistcveoficinadeventasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4) ),
			@AttributeOverride(name = "cveoficinadeventasant", column = @Column(name = "CVEOFICINADEVENTASANT", nullable = false, length = 4) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 2, scale = 0) ) })
	public HistcveoficinadeventasId getId() {
		return this.id;
	}

	public void setId(HistcveoficinadeventasId id) {
		this.id = id;
	}

}
