package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistcveoficinadeventasId generated by hbm2java
 */
@Embeddable
public class HistcveoficinadeventasId implements java.io.Serializable {

	private String cveoficinadeventas;
	private String cveoficinadeventasant;
	private Byte activo;

	public HistcveoficinadeventasId() {
	}

	public HistcveoficinadeventasId(String cveoficinadeventas, String cveoficinadeventasant) {
		this.cveoficinadeventas = cveoficinadeventas;
		this.cveoficinadeventasant = cveoficinadeventasant;
	}

	public HistcveoficinadeventasId(String cveoficinadeventas, String cveoficinadeventasant, Byte activo) {
		this.cveoficinadeventas = cveoficinadeventas;
		this.cveoficinadeventasant = cveoficinadeventasant;
		this.activo = activo;
	}

	@Column(name = "CVEOFICINADEVENTAS", nullable = false, length = 4)
	public String getCveoficinadeventas() {
		return this.cveoficinadeventas;
	}

	public void setCveoficinadeventas(String cveoficinadeventas) {
		this.cveoficinadeventas = cveoficinadeventas;
	}

	@Column(name = "CVEOFICINADEVENTASANT", nullable = false, length = 4)
	public String getCveoficinadeventasant() {
		return this.cveoficinadeventasant;
	}

	public void setCveoficinadeventasant(String cveoficinadeventasant) {
		this.cveoficinadeventasant = cveoficinadeventasant;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistcveoficinadeventasId))
			return false;
		HistcveoficinadeventasId castOther = (HistcveoficinadeventasId) other;

		return ((this.getCveoficinadeventas() == castOther.getCveoficinadeventas())
				|| (this.getCveoficinadeventas() != null && castOther.getCveoficinadeventas() != null
						&& this.getCveoficinadeventas().equals(castOther.getCveoficinadeventas())))
				&& ((this.getCveoficinadeventasant() == castOther.getCveoficinadeventasant())
						|| (this.getCveoficinadeventasant() != null && castOther.getCveoficinadeventasant() != null
								&& this.getCveoficinadeventasant().equals(castOther.getCveoficinadeventasant())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveoficinadeventas() == null ? 0 : this.getCveoficinadeventas().hashCode());
		result = 37 * result + (getCveoficinadeventasant() == null ? 0 : this.getCveoficinadeventasant().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		return result;
	}

}
