package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistestatusId generated by hbm2java
 */
@Embeddable
public class HistestatusId implements java.io.Serializable {

	private String folio;
	private Date fecha;
	private Integer idestatus;
	private String usuario;
	private String comentario;

	public HistestatusId() {
	}

	public HistestatusId(String folio, Date fecha) {
		this.folio = folio;
		this.fecha = fecha;
	}

	public HistestatusId(String folio, Date fecha, Integer idestatus, String usuario, String comentario) {
		this.folio = folio;
		this.fecha = fecha;
		this.idestatus = idestatus;
		this.usuario = usuario;
		this.comentario = comentario;
	}

	@Column(name = "FOLIO", nullable = false, length = 13)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "IDESTATUS", precision = 6, scale = 0)
	public Integer getIdestatus() {
		return this.idestatus;
	}

	public void setIdestatus(Integer idestatus) {
		this.idestatus = idestatus;
	}

	@Column(name = "USUARIO", length = 7)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "COMENTARIO")
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistestatusId))
			return false;
		HistestatusId castOther = (HistestatusId) other;

		return ((this.getFolio() == castOther.getFolio()) || (this.getFolio() != null && castOther.getFolio() != null
				&& this.getFolio().equals(castOther.getFolio())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getIdestatus() == castOther.getIdestatus()) || (this.getIdestatus() != null
						&& castOther.getIdestatus() != null && this.getIdestatus().equals(castOther.getIdestatus())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
						&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getComentario() == castOther.getComentario())
						|| (this.getComentario() != null && castOther.getComentario() != null
								&& this.getComentario().equals(castOther.getComentario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getIdestatus() == null ? 0 : this.getIdestatus().hashCode());
		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + (getComentario() == null ? 0 : this.getComentario().hashCode());
		return result;
	}

}
