package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListavaloresId generated by hbm2java
 */
@Embeddable
public class ListavaloresId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short idlistavalor;
	private String llave;
	private String valor;
	private Byte activo;
	private String usuariomod;
	private Date fechamod;
	private Boolean editable;

	public ListavaloresId() {
	}

	public ListavaloresId(short idlistavalor) {
		this.idlistavalor = idlistavalor;
	}

	public ListavaloresId(short idlistavalor, String llave, String valor, Byte activo, String usuariomod, Date fechamod,
			Boolean editable) {
		this.idlistavalor = idlistavalor;
		this.llave = llave;
		this.valor = valor;
		this.activo = activo;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
		this.editable = editable;
	}

	@Column(name = "IDLISTAVALOR", nullable = false, precision = 3, scale = 0)
	public short getIdlistavalor() {
		return this.idlistavalor;
	}

	public void setIdlistavalor(short idlistavalor) {
		this.idlistavalor = idlistavalor;
	}

	@Column(name = "LLAVE", length = 30)
	public String getLlave() {
		return this.llave;
	}

	public void setLlave(String llave) {
		this.llave = llave;
	}

	@Column(name = "VALOR", length = 100)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "ACTIVO", precision = 2, scale = 0)
	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	@Column(name = "USUARIOMOD", length = 7)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Column(name = "FECHAMOD", length = 7)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "EDITABLE", precision = 1, scale = 0)
	public Boolean getEditable() {
		return this.editable;
	}

	public void setEditable(Boolean editable) {
		this.editable = editable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListavaloresId))
			return false;
		ListavaloresId castOther = (ListavaloresId) other;

		return (this.getIdlistavalor() == castOther.getIdlistavalor())
				&& ((this.getLlave() == castOther.getLlave()) || (this.getLlave() != null
						&& castOther.getLlave() != null && this.getLlave().equals(castOther.getLlave())))
				&& ((this.getValor() == castOther.getValor()) || (this.getValor() != null
						&& castOther.getValor() != null && this.getValor().equals(castOther.getValor())))
				&& ((this.getActivo() == castOther.getActivo()) || (this.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo().equals(castOther.getActivo())))
				&& ((this.getUsuariomod() == castOther.getUsuariomod()) || (this.getUsuariomod() != null
						&& castOther.getUsuariomod() != null && this.getUsuariomod().equals(castOther.getUsuariomod())))
				&& ((this.getFechamod() == castOther.getFechamod()) || (this.getFechamod() != null
						&& castOther.getFechamod() != null && this.getFechamod().equals(castOther.getFechamod())))
				&& ((this.getEditable() == castOther.getEditable()) || (this.getEditable() != null
						&& castOther.getEditable() != null && this.getEditable().equals(castOther.getEditable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdlistavalor();
		result = 37 * result + (getLlave() == null ? 0 : this.getLlave().hashCode());
		result = 37 * result + (getValor() == null ? 0 : this.getValor().hashCode());
		result = 37 * result + (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result + (getUsuariomod() == null ? 0 : this.getUsuariomod().hashCode());
		result = 37 * result + (getFechamod() == null ? 0 : this.getFechamod().hashCode());
		result = 37 * result + (getEditable() == null ? 0 : this.getEditable().hashCode());
		return result;
	}

}
