package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MarcacsaId generated by hbm2java
 */
@Embeddable
public class MarcacsaId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String cvemarca;
	private short idcsa;

	public MarcacsaId() {
	}

	public MarcacsaId(String cvemarca, short idcsa) {
		this.cvemarca = cvemarca;
		this.idcsa = idcsa;
	}

	@Column(name = "CVEMARCA", nullable = false, length = 30)
	public String getCvemarca() {
		return this.cvemarca;
	}

	public void setCvemarca(String cvemarca) {
		this.cvemarca = cvemarca;
	}

	@Column(name = "IDCSA", nullable = false, precision = 4, scale = 0)
	public short getIdcsa() {
		return this.idcsa;
	}

	public void setIdcsa(short idcsa) {
		this.idcsa = idcsa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MarcacsaId))
			return false;
		MarcacsaId castOther = (MarcacsaId) other;

		return ((this.getCvemarca() == castOther.getCvemarca()) || (this.getCvemarca() != null
				&& castOther.getCvemarca() != null && this.getCvemarca().equals(castOther.getCvemarca())))
				&& (this.getIdcsa() == castOther.getIdcsa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCvemarca() == null ? 0 : this.getCvemarca().hashCode());
		result = 37 * result + this.getIdcsa();
		return result;
	}

}
