package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Marcacsa generated by hbm2java
 */
@Entity
@Table(name = "MARCACSA")
public class Marcacsa implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private MarcacsaId id;

	public Marcacsa() {
	}

	public Marcacsa(MarcacsaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", nullable = false, length = 30) ),
			@AttributeOverride(name = "idcsa", column = @Column(name = "IDCSA", nullable = false, precision = 4, scale = 0) ) })
	public MarcacsaId getId() {
		return this.id;
	}

	public void setId(MarcacsaId id) {
		this.id = id;
	}

}
