package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Medicionservicios generated by hbm2java
 */
@Entity
@Table(name = "MEDICIONSERVICIOS")
public class Medicionservicios implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private MedicionserviciosId id;

	public Medicionservicios() {
	}

	public Medicionservicios(MedicionserviciosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idmedicion", column = @Column(name = "IDMEDICION", nullable = false, precision = 10, scale = 0) ),
			@AttributeOverride(name = "idtipomovimiento", column = @Column(name = "IDTIPOMOVIMIENTO", precision = 6, scale = 0) ),
			@AttributeOverride(name = "idusuario", column = @Column(name = "IDUSUARIO", precision = 6, scale = 0) ),
			@AttributeOverride(name = "inicio", column = @Column(name = "INICIO", length = 7) ),
			@AttributeOverride(name = "fin", column = @Column(name = "FIN", length = 7) ),
			@AttributeOverride(name = "referencia", column = @Column(name = "REFERENCIA", length = 30) ) })
	public MedicionserviciosId getId() {
		return this.id;
	}

	public void setId(MedicionserviciosId id) {
		this.id = id;
	}

}
