package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MedicionserviciosId generated by hbm2java
 */
@Embeddable
public class MedicionserviciosId implements java.io.Serializable {

	private long idmedicion;
	private Integer idtipomovimiento;
	private Integer idusuario;
	private Date inicio;
	private Date fin;
	private String referencia;

	public MedicionserviciosId() {
	}

	public MedicionserviciosId(long idmedicion) {
		this.idmedicion = idmedicion;
	}

	public MedicionserviciosId(long idmedicion, Integer idtipomovimiento, Integer idusuario, Date inicio, Date fin,
			String referencia) {
		this.idmedicion = idmedicion;
		this.idtipomovimiento = idtipomovimiento;
		this.idusuario = idusuario;
		this.inicio = inicio;
		this.fin = fin;
		this.referencia = referencia;
	}

	@Column(name = "IDMEDICION", nullable = false, precision = 10, scale = 0)
	public long getIdmedicion() {
		return this.idmedicion;
	}

	public void setIdmedicion(long idmedicion) {
		this.idmedicion = idmedicion;
	}

	@Column(name = "IDTIPOMOVIMIENTO", precision = 6, scale = 0)
	public Integer getIdtipomovimiento() {
		return this.idtipomovimiento;
	}

	public void setIdtipomovimiento(Integer idtipomovimiento) {
		this.idtipomovimiento = idtipomovimiento;
	}

	@Column(name = "IDUSUARIO", precision = 6, scale = 0)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "INICIO", length = 7)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Column(name = "FIN", length = 7)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "REFERENCIA", length = 30)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MedicionserviciosId))
			return false;
		MedicionserviciosId castOther = (MedicionserviciosId) other;

		return (this.getIdmedicion() == castOther.getIdmedicion())
				&& ((this.getIdtipomovimiento() == castOther.getIdtipomovimiento())
						|| (this.getIdtipomovimiento() != null && castOther.getIdtipomovimiento() != null
								&& this.getIdtipomovimiento().equals(castOther.getIdtipomovimiento())))
				&& ((this.getIdusuario() == castOther.getIdusuario()) || (this.getIdusuario() != null
						&& castOther.getIdusuario() != null && this.getIdusuario().equals(castOther.getIdusuario())))
				&& ((this.getInicio() == castOther.getInicio()) || (this.getInicio() != null
						&& castOther.getInicio() != null && this.getInicio().equals(castOther.getInicio())))
				&& ((this.getFin() == castOther.getFin()) || (this.getFin() != null && castOther.getFin() != null
						&& this.getFin().equals(castOther.getFin())))
				&& ((this.getReferencia() == castOther.getReferencia())
						|| (this.getReferencia() != null && castOther.getReferencia() != null
								&& this.getReferencia().equals(castOther.getReferencia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdmedicion();
		result = 37 * result + (getIdtipomovimiento() == null ? 0 : this.getIdtipomovimiento().hashCode());
		result = 37 * result + (getIdusuario() == null ? 0 : this.getIdusuario().hashCode());
		result = 37 * result + (getInicio() == null ? 0 : this.getInicio().hashCode());
		result = 37 * result + (getFin() == null ? 0 : this.getFin().hashCode());
		result = 37 * result + (getReferencia() == null ? 0 : this.getReferencia().hashCode());
		return result;
	}

}
