package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PtoCtlprocesos generated by hbm2java
 */
@Entity
@Table(name = "PTO_CTLPROCESOS", schema = "CERTREG")
public class PtoCtlprocesos implements java.io.Serializable {

	private BigDecimal idproceso;
	private String nombreproceso;
	private String descripcion;
	private Character tipo;

	public PtoCtlprocesos() {
	}

	public PtoCtlprocesos(BigDecimal idproceso) {
		this.idproceso = idproceso;
	}

	public PtoCtlprocesos(BigDecimal idproceso, String nombreproceso, String descripcion, Character tipo) {
		this.idproceso = idproceso;
		this.nombreproceso = nombreproceso;
		this.descripcion = descripcion;
		this.tipo = tipo;
	}

	@Id

	@Column(name = "IDPROCESO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdproceso() {
		return this.idproceso;
	}

	public void setIdproceso(BigDecimal idproceso) {
		this.idproceso = idproceso;
	}

	@Column(name = "NOMBREPROCESO")
	public String getNombreproceso() {
		return this.nombreproceso;
	}

	public void setNombreproceso(String nombreproceso) {
		this.nombreproceso = nombreproceso;
	}

	@Column(name = "DESCRIPCION")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "TIPO", length = 1)
	public Character getTipo() {
		return this.tipo;
	}

	public void setTipo(Character tipo) {
		this.tipo = tipo;
	}

}
