package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PtoCtlpantallaCa generated by hbm2java
 */
@Entity
@Table(name = "PTO_CTLPANTALLA_CA")
public class PtoCtlpantallaCa implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigDecimal idpantalla;
	private String nombre;
	private String descripcion;
	private Set<PtoCtlperfilCa> ptoCtlperfilCas = new HashSet<PtoCtlperfilCa>(0);

	public PtoCtlpantallaCa() {
	}

	public PtoCtlpantallaCa(BigDecimal idpantalla, String nombre) {
		this.idpantalla = idpantalla;
		this.nombre = nombre;
	}

	public PtoCtlpantallaCa(BigDecimal idpantalla, String nombre, String descripcion,
			Set<PtoCtlperfilCa> ptoCtlperfilCas) {
		this.idpantalla = idpantalla;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ptoCtlperfilCas = ptoCtlperfilCas;
	}

	@Id

	@Column(name = "IDPANTALLA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdpantalla() {
		return this.idpantalla;
	}

	public void setIdpantalla(BigDecimal idpantalla) {
		this.idpantalla = idpantalla;
	}

	@Column(name = "NOMBRE", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ptoCtlpantallaCa")
	public Set<PtoCtlperfilCa> getPtoCtlperfilCas() {
		return this.ptoCtlperfilCas;
	}

	public void setPtoCtlperfilCas(Set<PtoCtlperfilCa> ptoCtlperfilCas) {
		this.ptoCtlperfilCas = ptoCtlperfilCas;
	}

}
