package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PtoCtlperfilCaId generated by hbm2java
 */
@Embeddable
public class PtoCtlperfilCaId implements java.io.Serializable {

	private BigDecimal idperfiln;
	private BigDecimal idpantalla;
	private BigDecimal idproceso;

	public PtoCtlperfilCaId() {
	}

	public PtoCtlperfilCaId(BigDecimal idperfiln, BigDecimal idpantalla, BigDecimal idproceso) {
		this.idperfiln = idperfiln;
		this.idpantalla = idpantalla;
		this.idproceso = idproceso;
	}

	@Column(name = "IDPERFILN", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdperfiln() {
		return this.idperfiln;
	}

	public void setIdperfiln(BigDecimal idperfiln) {
		this.idperfiln = idperfiln;
	}

	@Column(name = "IDPANTALLA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdpantalla() {
		return this.idpantalla;
	}

	public void setIdpantalla(BigDecimal idpantalla) {
		this.idpantalla = idpantalla;
	}

	@Column(name = "IDPROCESO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdproceso() {
		return this.idproceso;
	}

	public void setIdproceso(BigDecimal idproceso) {
		this.idproceso = idproceso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PtoCtlperfilCaId))
			return false;
		PtoCtlperfilCaId castOther = (PtoCtlperfilCaId) other;

		return ((this.getIdperfiln() == castOther.getIdperfiln()) || (this.getIdperfiln() != null
				&& castOther.getIdperfiln() != null && this.getIdperfiln().equals(castOther.getIdperfiln())))
				&& ((this.getIdpantalla() == castOther.getIdpantalla()) || (this.getIdpantalla() != null
						&& castOther.getIdpantalla() != null && this.getIdpantalla().equals(castOther.getIdpantalla())))
				&& ((this.getIdproceso() == castOther.getIdproceso()) || (this.getIdproceso() != null
						&& castOther.getIdproceso() != null && this.getIdproceso().equals(castOther.getIdproceso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdperfiln() == null ? 0 : this.getIdperfiln().hashCode());
		result = 37 * result + (getIdpantalla() == null ? 0 : this.getIdpantalla().hashCode());
		result = 37 * result + (getIdproceso() == null ? 0 : this.getIdproceso().hashCode());
		return result;
	}

}
