package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PtoCtlperfiln generated by hbm2java
 */
@Entity
@Table(name = "PTO_CTLPERFILN")
public class PtoCtlperfiln implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigDecimal idperfiln;
	private String idpuesto;
	private String descripcion;
	private BigDecimal idregion;
	private BigDecimal nivelaut;
	private Set<PtoCtlperfilCa> ptoCtlperfilCas = new HashSet<PtoCtlperfilCa>(0);

	public PtoCtlperfiln() {
	}

	public PtoCtlperfiln(BigDecimal idperfiln, String idpuesto, String descripcion, BigDecimal idregion,
			BigDecimal nivelaut) {
		this.idperfiln = idperfiln;
		this.idpuesto = idpuesto;
		this.descripcion = descripcion;
		this.idregion = idregion;
		this.nivelaut = nivelaut;
	}

	public PtoCtlperfiln(BigDecimal idperfiln, String idpuesto, String descripcion, BigDecimal idregion,
			BigDecimal nivelaut, Set<PtoCtlperfilCa> ptoCtlperfilCas) {
		this.idperfiln = idperfiln;
		this.idpuesto = idpuesto;
		this.descripcion = descripcion;
		this.idregion = idregion;
		this.nivelaut = nivelaut;
		this.ptoCtlperfilCas = ptoCtlperfilCas;
	}

	@Id

	@Column(name = "IDPERFILN", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdperfiln() {
		return this.idperfiln;
	}

	public void setIdperfiln(BigDecimal idperfiln) {
		this.idperfiln = idperfiln;
	}

	@Column(name = "IDPUESTO", nullable = false, length = 100)
	public String getIdpuesto() {
		return this.idpuesto;
	}

	public void setIdpuesto(String idpuesto) {
		this.idpuesto = idpuesto;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "IDREGION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdregion() {
		return this.idregion;
	}

	public void setIdregion(BigDecimal idregion) {
		this.idregion = idregion;
	}

	@Column(name = "NIVELAUT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNivelaut() {
		return this.nivelaut;
	}

	public void setNivelaut(BigDecimal nivelaut) {
		this.nivelaut = nivelaut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ptoCtlperfiln")
	public Set<PtoCtlperfilCa> getPtoCtlperfilCas() {
		return this.ptoCtlperfilCas;
	}

	public void setPtoCtlperfilCas(Set<PtoCtlperfilCa> ptoCtlperfilCas) {
		this.ptoCtlperfilCas = ptoCtlperfilCas;
	}

}
