package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PtoCtlpuntosvta generated by hbm2java
 */
@Entity
@Table(name = "PTO_CTLPUNTOSVTA")
public class PtoCtlpuntosvta implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String idpuntovta;
	private String segmentoip;
	private Long rangoinf;
	private Long rangosup;
	private Integer idregion;
	private Long contadorpmp;
	private Integer ivaPorcentaje;
	private String tipopuntovta;

	public PtoCtlpuntosvta() {
	}

	public PtoCtlpuntosvta(String idpuntovta) {
		this.idpuntovta = idpuntovta;
	}

	public PtoCtlpuntosvta(String idpuntovta, String segmentoip, Long rangoinf, Long rangosup, Integer idregion,
			Long contadorpmp, Integer ivaPorcentaje, String tipopuntovta) {
		this.idpuntovta = idpuntovta;
		this.segmentoip = segmentoip;
		this.rangoinf = rangoinf;
		this.rangosup = rangosup;
		this.idregion = idregion;
		this.contadorpmp = contadorpmp;
		this.ivaPorcentaje = ivaPorcentaje;
		this.tipopuntovta = tipopuntovta;
	}

	@Id

	@Column(name = "IDPUNTOVTA", unique = true, nullable = false, length = 30)
	public String getIdpuntovta() {
		return this.idpuntovta;
	}

	public void setIdpuntovta(String idpuntovta) {
		this.idpuntovta = idpuntovta;
	}

	@Column(name = "SEGMENTOIP", length = 11)
	public String getSegmentoip() {
		return this.segmentoip;
	}

	public void setSegmentoip(String segmentoip) {
		this.segmentoip = segmentoip;
	}

	@Column(name = "RANGOINF", precision = 10, scale = 0)
	public Long getRangoinf() {
		return this.rangoinf;
	}

	public void setRangoinf(Long rangoinf) {
		this.rangoinf = rangoinf;
	}

	@Column(name = "RANGOSUP", precision = 10, scale = 0)
	public Long getRangosup() {
		return this.rangosup;
	}

	public void setRangosup(Long rangosup) {
		this.rangosup = rangosup;
	}

	@Column(name = "IDREGION", precision = 5, scale = 0)
	public Integer getIdregion() {
		return this.idregion;
	}

	public void setIdregion(Integer idregion) {
		this.idregion = idregion;
	}

	@Column(name = "CONTADORPMP", precision = 10, scale = 0)
	public Long getContadorpmp() {
		return this.contadorpmp;
	}

	public void setContadorpmp(Long contadorpmp) {
		this.contadorpmp = contadorpmp;
	}

	@Column(name = "IVA_PORCENTAJE", precision = 5, scale = 0)
	public Integer getIvaPorcentaje() {
		return this.ivaPorcentaje;
	}

	public void setIvaPorcentaje(Integer ivaPorcentaje) {
		this.ivaPorcentaje = ivaPorcentaje;
	}

	@Column(name = "TIPOPUNTOVTA", length = 1)
	public String getTipopuntovta() {
		return this.tipopuntovta;
	}

	public void setTipopuntovta(String tipopuntovta) {
		this.tipopuntovta = tipopuntovta;
	}

}
