package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Relacionmarcascsa generated by hbm2java
 */
@Entity
@Table(name = "RELACIONMARCASCSA", schema = "CERTREG")
public class Relacionmarcascsa implements java.io.Serializable {

	private RelacionmarcascsaId id;

	public Relacionmarcascsa() {
	}

	public Relacionmarcascsa(RelacionmarcascsaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cvemarca", column = @Column(name = "CVEMARCA", length = 30) ),
			@AttributeOverride(name = "cveoficinadeventas", column = @Column(name = "CVEOFICINADEVENTAS", length = 4) ),
			@AttributeOverride(name = "vigente", column = @Column(name = "VIGENTE", precision = 1, scale = 0) ) })
	public RelacionmarcascsaId getId() {
		return this.id;
	}

	public void setId(RelacionmarcascsaId id) {
		this.id = id;
	}

}
