package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RelacionPerfiles generated by hbm2java
 */
@Entity
@Table(name = "RELACION_PERFILES")
public class RelacionPerfiles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private RelacionPerfilesId id;

	public RelacionPerfiles() {
	}

	public RelacionPerfiles(RelacionPerfilesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idRelacion", column = @Column(name = "ID_RELACION", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "perfil", column = @Column(name = "PERFIL", length = 80) ),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 2, scale = 0) ),
			@AttributeOverride(name = "clave", column = @Column(name = "CLAVE", length = 15) ) })
	public RelacionPerfilesId getId() {
		return this.id;
	}

	public void setId(RelacionPerfilesId id) {
		this.id = id;
	}

}
