package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReparacionId generated by hbm2java
 */
@Embeddable
public class ReparacionId implements java.io.Serializable {

	private String folio;
	private int cveproducto;

	public ReparacionId() {
	}

	public ReparacionId(String folio, int cveproducto) {
		this.folio = folio;
		this.cveproducto = cveproducto;
	}

	@Column(name = "FOLIO", nullable = false, length = 13)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "CVEPRODUCTO", nullable = false, precision = 6, scale = 0)
	public int getCveproducto() {
		return this.cveproducto;
	}

	public void setCveproducto(int cveproducto) {
		this.cveproducto = cveproducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReparacionId))
			return false;
		ReparacionId castOther = (ReparacionId) other;

		return ((this.getFolio() == castOther.getFolio()) || (this.getFolio() != null && castOther.getFolio() != null
				&& this.getFolio().equals(castOther.getFolio())))
				&& (this.getCveproducto() == castOther.getCveproducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result + this.getCveproducto();
		return result;
	}

}
