package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RespuestasId generated by hbm2java
 */
@Embeddable
public class RespuestasId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idevaluacion;
	private String cvemarca;
	private Byte idcsa;
	private byte idpregunta;
	private byte idsubpregunta;
	private Integer valor;
	private int idrespuesta;

	public RespuestasId() {
	}

	public RespuestasId(int idevaluacion, byte idpregunta, byte idsubpregunta, int idrespuesta) {
		this.idevaluacion = idevaluacion;
		this.idpregunta = idpregunta;
		this.idsubpregunta = idsubpregunta;
		this.idrespuesta = idrespuesta;
	}

	public RespuestasId(int idevaluacion, String cvemarca, Byte idcsa, byte idpregunta, byte idsubpregunta,
			Integer valor, int idrespuesta) {
		this.idevaluacion = idevaluacion;
		this.cvemarca = cvemarca;
		this.idcsa = idcsa;
		this.idpregunta = idpregunta;
		this.idsubpregunta = idsubpregunta;
		this.valor = valor;
		this.idrespuesta = idrespuesta;
	}

	@Column(name = "IDEVALUACION", nullable = false, precision = 6, scale = 0)
	public int getIdevaluacion() {
		return this.idevaluacion;
	}

	public void setIdevaluacion(int idevaluacion) {
		this.idevaluacion = idevaluacion;
	}

	@Column(name = "CVEMARCA", length = 30)
	public String getCvemarca() {
		return this.cvemarca;
	}

	public void setCvemarca(String cvemarca) {
		this.cvemarca = cvemarca;
	}

	@Column(name = "IDCSA", precision = 2, scale = 0)
	public Byte getIdcsa() {
		return this.idcsa;
	}

	public void setIdcsa(Byte idcsa) {
		this.idcsa = idcsa;
	}

	@Column(name = "IDPREGUNTA", nullable = false, precision = 2, scale = 0)
	public byte getIdpregunta() {
		return this.idpregunta;
	}

	public void setIdpregunta(byte idpregunta) {
		this.idpregunta = idpregunta;
	}

	@Column(name = "IDSUBPREGUNTA", nullable = false, precision = 2, scale = 0)
	public byte getIdsubpregunta() {
		return this.idsubpregunta;
	}

	public void setIdsubpregunta(byte idsubpregunta) {
		this.idsubpregunta = idsubpregunta;
	}

	@Column(name = "VALOR", precision = 6, scale = 0)
	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	@Column(name = "IDRESPUESTA", nullable = false, precision = 6, scale = 0)
	public int getIdrespuesta() {
		return this.idrespuesta;
	}

	public void setIdrespuesta(int idrespuesta) {
		this.idrespuesta = idrespuesta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RespuestasId))
			return false;
		RespuestasId castOther = (RespuestasId) other;

		return (this.getIdevaluacion() == castOther.getIdevaluacion())
				&& ((this.getCvemarca() == castOther.getCvemarca()) || (this.getCvemarca() != null
						&& castOther.getCvemarca() != null && this.getCvemarca().equals(castOther.getCvemarca())))
				&& ((this.getIdcsa() == castOther.getIdcsa()) || (this.getIdcsa() != null
						&& castOther.getIdcsa() != null && this.getIdcsa().equals(castOther.getIdcsa())))
				&& (this.getIdpregunta() == castOther.getIdpregunta())
				&& (this.getIdsubpregunta() == castOther.getIdsubpregunta())
				&& ((this.getValor() == castOther.getValor()) || (this.getValor() != null
						&& castOther.getValor() != null && this.getValor().equals(castOther.getValor())))
				&& (this.getIdrespuesta() == castOther.getIdrespuesta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdevaluacion();
		result = 37 * result + (getCvemarca() == null ? 0 : this.getCvemarca().hashCode());
		result = 37 * result + (getIdcsa() == null ? 0 : this.getIdcsa().hashCode());
		result = 37 * result + this.getIdpregunta();
		result = 37 * result + this.getIdsubpregunta();
		result = 37 * result + (getValor() == null ? 0 : this.getValor().hashCode());
		result = 37 * result + this.getIdrespuesta();
		return result;
	}

}
