package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Seguimientogarantia generated by hbm2java
 */
@Entity
@Table(name = "SEGUIMIENTOGARANTIA", schema = "CERTREG")
public class Seguimientogarantia implements java.io.Serializable {

	private SeguimientogarantiaId id;

	public Seguimientogarantia() {
	}

	public Seguimientogarantia(SeguimientogarantiaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "folio", column = @Column(name = "FOLIO", nullable = false, length = 13) ),
			@AttributeOverride(name = "idestatusalmacen", column = @Column(name = "IDESTATUSALMACEN", precision = 6, scale = 0) ),
			@AttributeOverride(name = "tipoenvio", column = @Column(name = "TIPOENVIO", length = 30) ),
			@AttributeOverride(name = "accesorios", column = @Column(name = "ACCESORIOS") ),
			@AttributeOverride(name = "sinaclaracion", column = @Column(name = "SINACLARACION", precision = 2, scale = 0) ),
			@AttributeOverride(name = "fechasinaclaracion", column = @Column(name = "FECHASINACLARACION", length = 7) ),
			@AttributeOverride(name = "sinreemplazo", column = @Column(name = "SINREEMPLAZO", precision = 2, scale = 0) ),
			@AttributeOverride(name = "fechasinreemplazo", column = @Column(name = "FECHASINREEMPLAZO", length = 7) ),
			@AttributeOverride(name = "esnimeireemplazo", column = @Column(name = "ESNIMEIREEMPLAZO", length = 15) ),
			@AttributeOverride(name = "foliosigade", column = @Column(name = "FOLIOSIGADE", precision = 8, scale = 0) ),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO", precision = 3, scale = 0) ),
			@AttributeOverride(name = "cvealmacen", column = @Column(name = "CVEALMACEN", length = 4) ),
			@AttributeOverride(name = "cveproveedor", column = @Column(name = "CVEPROVEEDOR", length = 4) ),
			@AttributeOverride(name = "rechazoalmacen", column = @Column(name = "RECHAZOALMACEN", precision = 3, scale = 0) ),
			@AttributeOverride(name = "rechazoproveedor", column = @Column(name = "RECHAZOPROVEEDOR", precision = 3, scale = 0) ),
			@AttributeOverride(name = "descrechazoalm", column = @Column(name = "DESCRECHAZOALM", length = 250) ),
			@AttributeOverride(name = "descrechazoprov", column = @Column(name = "DESCRECHAZOPROV", length = 250) ),
			@AttributeOverride(name = "idsingarantia", column = @Column(name = "IDSINGARANTIA", precision = 3, scale = 0) ),
			@AttributeOverride(name = "descsingarantia", column = @Column(name = "DESCSINGARANTIA", length = 250) ),
			@AttributeOverride(name = "fecharealenvio", column = @Column(name = "FECHAREALENVIO", length = 7) ),
			@AttributeOverride(name = "idproveedor", column = @Column(name = "IDPROVEEDOR", precision = 4, scale = 0) ),
			@AttributeOverride(name = "traspaso", column = @Column(name = "TRASPASO", precision = 1, scale = 0) ),
			@AttributeOverride(name = "cvemodelonvo", column = @Column(name = "CVEMODELONVO", length = 30) ),
			@AttributeOverride(name = "documentoSap", column = @Column(name = "DOCUMENTO_SAP", length = 30) ),
			@AttributeOverride(name = "materialnvo", column = @Column(name = "MATERIALNVO", length = 20) ) })
	public SeguimientogarantiaId getId() {
		return this.id;
	}

	public void setId(SeguimientogarantiaId id) {
		this.id = id;
	}

}
