package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeguimientogarantiaId generated by hbm2java
 */
@Embeddable
public class SeguimientogarantiaId implements java.io.Serializable {

	private String folio;
	private Integer idestatusalmacen;
	private String tipoenvio;
	private String accesorios;
	private Byte sinaclaracion;
	private Date fechasinaclaracion;
	private Byte sinreemplazo;
	private Date fechasinreemplazo;
	private String esnimeireemplazo;
	private Integer foliosigade;
	private Short tipo;
	private String cvealmacen;
	private String cveproveedor;
	private Short rechazoalmacen;
	private Short rechazoproveedor;
	private String descrechazoalm;
	private String descrechazoprov;
	private Short idsingarantia;
	private String descsingarantia;
	private Date fecharealenvio;
	private Short idproveedor;
	private Boolean traspaso;
	private String cvemodelonvo;
	private String documentoSap;
	private String materialnvo;

	public SeguimientogarantiaId() {
	}

	public SeguimientogarantiaId(String folio) {
		this.folio = folio;
	}

	public SeguimientogarantiaId(String folio, Integer idestatusalmacen, String tipoenvio, String accesorios,
			Byte sinaclaracion, Date fechasinaclaracion, Byte sinreemplazo, Date fechasinreemplazo,
			String esnimeireemplazo, Integer foliosigade, Short tipo, String cvealmacen, String cveproveedor,
			Short rechazoalmacen, Short rechazoproveedor, String descrechazoalm, String descrechazoprov,
			Short idsingarantia, String descsingarantia, Date fecharealenvio, Short idproveedor, Boolean traspaso,
			String cvemodelonvo, String documentoSap, String materialnvo) {
		this.folio = folio;
		this.idestatusalmacen = idestatusalmacen;
		this.tipoenvio = tipoenvio;
		this.accesorios = accesorios;
		this.sinaclaracion = sinaclaracion;
		this.fechasinaclaracion = fechasinaclaracion;
		this.sinreemplazo = sinreemplazo;
		this.fechasinreemplazo = fechasinreemplazo;
		this.esnimeireemplazo = esnimeireemplazo;
		this.foliosigade = foliosigade;
		this.tipo = tipo;
		this.cvealmacen = cvealmacen;
		this.cveproveedor = cveproveedor;
		this.rechazoalmacen = rechazoalmacen;
		this.rechazoproveedor = rechazoproveedor;
		this.descrechazoalm = descrechazoalm;
		this.descrechazoprov = descrechazoprov;
		this.idsingarantia = idsingarantia;
		this.descsingarantia = descsingarantia;
		this.fecharealenvio = fecharealenvio;
		this.idproveedor = idproveedor;
		this.traspaso = traspaso;
		this.cvemodelonvo = cvemodelonvo;
		this.documentoSap = documentoSap;
		this.materialnvo = materialnvo;
	}

	@Column(name = "FOLIO", nullable = false, length = 13)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "IDESTATUSALMACEN", precision = 6, scale = 0)
	public Integer getIdestatusalmacen() {
		return this.idestatusalmacen;
	}

	public void setIdestatusalmacen(Integer idestatusalmacen) {
		this.idestatusalmacen = idestatusalmacen;
	}

	@Column(name = "TIPOENVIO", length = 30)
	public String getTipoenvio() {
		return this.tipoenvio;
	}

	public void setTipoenvio(String tipoenvio) {
		this.tipoenvio = tipoenvio;
	}

	@Column(name = "ACCESORIOS")
	public String getAccesorios() {
		return this.accesorios;
	}

	public void setAccesorios(String accesorios) {
		this.accesorios = accesorios;
	}

	@Column(name = "SINACLARACION", precision = 2, scale = 0)
	public Byte getSinaclaracion() {
		return this.sinaclaracion;
	}

	public void setSinaclaracion(Byte sinaclaracion) {
		this.sinaclaracion = sinaclaracion;
	}

	@Column(name = "FECHASINACLARACION", length = 7)
	public Date getFechasinaclaracion() {
		return this.fechasinaclaracion;
	}

	public void setFechasinaclaracion(Date fechasinaclaracion) {
		this.fechasinaclaracion = fechasinaclaracion;
	}

	@Column(name = "SINREEMPLAZO", precision = 2, scale = 0)
	public Byte getSinreemplazo() {
		return this.sinreemplazo;
	}

	public void setSinreemplazo(Byte sinreemplazo) {
		this.sinreemplazo = sinreemplazo;
	}

	@Column(name = "FECHASINREEMPLAZO", length = 7)
	public Date getFechasinreemplazo() {
		return this.fechasinreemplazo;
	}

	public void setFechasinreemplazo(Date fechasinreemplazo) {
		this.fechasinreemplazo = fechasinreemplazo;
	}

	@Column(name = "ESNIMEIREEMPLAZO", length = 15)
	public String getEsnimeireemplazo() {
		return this.esnimeireemplazo;
	}

	public void setEsnimeireemplazo(String esnimeireemplazo) {
		this.esnimeireemplazo = esnimeireemplazo;
	}

	@Column(name = "FOLIOSIGADE", precision = 8, scale = 0)
	public Integer getFoliosigade() {
		return this.foliosigade;
	}

	public void setFoliosigade(Integer foliosigade) {
		this.foliosigade = foliosigade;
	}

	@Column(name = "TIPO", precision = 3, scale = 0)
	public Short getTipo() {
		return this.tipo;
	}

	public void setTipo(Short tipo) {
		this.tipo = tipo;
	}

	@Column(name = "CVEALMACEN", length = 4)
	public String getCvealmacen() {
		return this.cvealmacen;
	}

	public void setCvealmacen(String cvealmacen) {
		this.cvealmacen = cvealmacen;
	}

	@Column(name = "CVEPROVEEDOR", length = 4)
	public String getCveproveedor() {
		return this.cveproveedor;
	}

	public void setCveproveedor(String cveproveedor) {
		this.cveproveedor = cveproveedor;
	}

	@Column(name = "RECHAZOALMACEN", precision = 3, scale = 0)
	public Short getRechazoalmacen() {
		return this.rechazoalmacen;
	}

	public void setRechazoalmacen(Short rechazoalmacen) {
		this.rechazoalmacen = rechazoalmacen;
	}

	@Column(name = "RECHAZOPROVEEDOR", precision = 3, scale = 0)
	public Short getRechazoproveedor() {
		return this.rechazoproveedor;
	}

	public void setRechazoproveedor(Short rechazoproveedor) {
		this.rechazoproveedor = rechazoproveedor;
	}

	@Column(name = "DESCRECHAZOALM", length = 250)
	public String getDescrechazoalm() {
		return this.descrechazoalm;
	}

	public void setDescrechazoalm(String descrechazoalm) {
		this.descrechazoalm = descrechazoalm;
	}

	@Column(name = "DESCRECHAZOPROV", length = 250)
	public String getDescrechazoprov() {
		return this.descrechazoprov;
	}

	public void setDescrechazoprov(String descrechazoprov) {
		this.descrechazoprov = descrechazoprov;
	}

	@Column(name = "IDSINGARANTIA", precision = 3, scale = 0)
	public Short getIdsingarantia() {
		return this.idsingarantia;
	}

	public void setIdsingarantia(Short idsingarantia) {
		this.idsingarantia = idsingarantia;
	}

	@Column(name = "DESCSINGARANTIA", length = 250)
	public String getDescsingarantia() {
		return this.descsingarantia;
	}

	public void setDescsingarantia(String descsingarantia) {
		this.descsingarantia = descsingarantia;
	}

	@Column(name = "FECHAREALENVIO", length = 7)
	public Date getFecharealenvio() {
		return this.fecharealenvio;
	}

	public void setFecharealenvio(Date fecharealenvio) {
		this.fecharealenvio = fecharealenvio;
	}

	@Column(name = "IDPROVEEDOR", precision = 4, scale = 0)
	public Short getIdproveedor() {
		return this.idproveedor;
	}

	public void setIdproveedor(Short idproveedor) {
		this.idproveedor = idproveedor;
	}

	@Column(name = "TRASPASO", precision = 1, scale = 0)
	public Boolean getTraspaso() {
		return this.traspaso;
	}

	public void setTraspaso(Boolean traspaso) {
		this.traspaso = traspaso;
	}

	@Column(name = "CVEMODELONVO", length = 30)
	public String getCvemodelonvo() {
		return this.cvemodelonvo;
	}

	public void setCvemodelonvo(String cvemodelonvo) {
		this.cvemodelonvo = cvemodelonvo;
	}

	@Column(name = "DOCUMENTO_SAP", length = 30)
	public String getDocumentoSap() {
		return this.documentoSap;
	}

	public void setDocumentoSap(String documentoSap) {
		this.documentoSap = documentoSap;
	}

	@Column(name = "MATERIALNVO", length = 20)
	public String getMaterialnvo() {
		return this.materialnvo;
	}

	public void setMaterialnvo(String materialnvo) {
		this.materialnvo = materialnvo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeguimientogarantiaId))
			return false;
		SeguimientogarantiaId castOther = (SeguimientogarantiaId) other;

		return ((this.getFolio() == castOther.getFolio()) || (this.getFolio() != null && castOther.getFolio() != null
				&& this.getFolio().equals(castOther.getFolio())))
				&& ((this.getIdestatusalmacen() == castOther.getIdestatusalmacen())
						|| (this.getIdestatusalmacen() != null && castOther.getIdestatusalmacen() != null
								&& this.getIdestatusalmacen().equals(castOther.getIdestatusalmacen())))
				&& ((this.getTipoenvio() == castOther.getTipoenvio()) || (this.getTipoenvio() != null
						&& castOther.getTipoenvio() != null && this.getTipoenvio().equals(castOther.getTipoenvio())))
				&& ((this.getAccesorios() == castOther.getAccesorios()) || (this.getAccesorios() != null
						&& castOther.getAccesorios() != null && this.getAccesorios().equals(castOther.getAccesorios())))
				&& ((this.getSinaclaracion() == castOther.getSinaclaracion())
						|| (this.getSinaclaracion() != null && castOther.getSinaclaracion() != null
								&& this.getSinaclaracion().equals(castOther.getSinaclaracion())))
				&& ((this.getFechasinaclaracion() == castOther.getFechasinaclaracion())
						|| (this.getFechasinaclaracion() != null && castOther.getFechasinaclaracion() != null
								&& this.getFechasinaclaracion().equals(castOther.getFechasinaclaracion())))
				&& ((this.getSinreemplazo() == castOther.getSinreemplazo())
						|| (this.getSinreemplazo() != null && castOther.getSinreemplazo() != null
								&& this.getSinreemplazo().equals(castOther.getSinreemplazo())))
				&& ((this.getFechasinreemplazo() == castOther.getFechasinreemplazo())
						|| (this.getFechasinreemplazo() != null && castOther.getFechasinreemplazo() != null
								&& this.getFechasinreemplazo().equals(castOther.getFechasinreemplazo())))
				&& ((this.getEsnimeireemplazo() == castOther.getEsnimeireemplazo())
						|| (this.getEsnimeireemplazo() != null && castOther.getEsnimeireemplazo() != null
								&& this.getEsnimeireemplazo().equals(castOther.getEsnimeireemplazo())))
				&& ((this.getFoliosigade() == castOther.getFoliosigade())
						|| (this.getFoliosigade() != null && castOther.getFoliosigade() != null
								&& this.getFoliosigade().equals(castOther.getFoliosigade())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getCvealmacen() == castOther.getCvealmacen()) || (this.getCvealmacen() != null
						&& castOther.getCvealmacen() != null && this.getCvealmacen().equals(castOther.getCvealmacen())))
				&& ((this.getCveproveedor() == castOther.getCveproveedor())
						|| (this.getCveproveedor() != null && castOther.getCveproveedor() != null
								&& this.getCveproveedor().equals(castOther.getCveproveedor())))
				&& ((this.getRechazoalmacen() == castOther.getRechazoalmacen())
						|| (this.getRechazoalmacen() != null && castOther.getRechazoalmacen() != null
								&& this.getRechazoalmacen().equals(castOther.getRechazoalmacen())))
				&& ((this.getRechazoproveedor() == castOther.getRechazoproveedor())
						|| (this.getRechazoproveedor() != null && castOther.getRechazoproveedor() != null
								&& this.getRechazoproveedor().equals(castOther.getRechazoproveedor())))
				&& ((this.getDescrechazoalm() == castOther.getDescrechazoalm())
						|| (this.getDescrechazoalm() != null && castOther.getDescrechazoalm() != null
								&& this.getDescrechazoalm().equals(castOther.getDescrechazoalm())))
				&& ((this.getDescrechazoprov() == castOther.getDescrechazoprov())
						|| (this.getDescrechazoprov() != null && castOther.getDescrechazoprov() != null
								&& this.getDescrechazoprov().equals(castOther.getDescrechazoprov())))
				&& ((this.getIdsingarantia() == castOther.getIdsingarantia())
						|| (this.getIdsingarantia() != null && castOther.getIdsingarantia() != null
								&& this.getIdsingarantia().equals(castOther.getIdsingarantia())))
				&& ((this.getDescsingarantia() == castOther.getDescsingarantia())
						|| (this.getDescsingarantia() != null && castOther.getDescsingarantia() != null
								&& this.getDescsingarantia().equals(castOther.getDescsingarantia())))
				&& ((this.getFecharealenvio() == castOther.getFecharealenvio())
						|| (this.getFecharealenvio() != null && castOther.getFecharealenvio() != null
								&& this.getFecharealenvio().equals(castOther.getFecharealenvio())))
				&& ((this.getIdproveedor() == castOther.getIdproveedor())
						|| (this.getIdproveedor() != null && castOther.getIdproveedor() != null
								&& this.getIdproveedor().equals(castOther.getIdproveedor())))
				&& ((this.getTraspaso() == castOther.getTraspaso()) || (this.getTraspaso() != null
						&& castOther.getTraspaso() != null && this.getTraspaso().equals(castOther.getTraspaso())))
				&& ((this.getCvemodelonvo() == castOther.getCvemodelonvo())
						|| (this.getCvemodelonvo() != null && castOther.getCvemodelonvo() != null
								&& this.getCvemodelonvo().equals(castOther.getCvemodelonvo())))
				&& ((this.getDocumentoSap() == castOther.getDocumentoSap())
						|| (this.getDocumentoSap() != null && castOther.getDocumentoSap() != null
								&& this.getDocumentoSap().equals(castOther.getDocumentoSap())))
				&& ((this.getMaterialnvo() == castOther.getMaterialnvo())
						|| (this.getMaterialnvo() != null && castOther.getMaterialnvo() != null
								&& this.getMaterialnvo().equals(castOther.getMaterialnvo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result + (getIdestatusalmacen() == null ? 0 : this.getIdestatusalmacen().hashCode());
		result = 37 * result + (getTipoenvio() == null ? 0 : this.getTipoenvio().hashCode());
		result = 37 * result + (getAccesorios() == null ? 0 : this.getAccesorios().hashCode());
		result = 37 * result + (getSinaclaracion() == null ? 0 : this.getSinaclaracion().hashCode());
		result = 37 * result + (getFechasinaclaracion() == null ? 0 : this.getFechasinaclaracion().hashCode());
		result = 37 * result + (getSinreemplazo() == null ? 0 : this.getSinreemplazo().hashCode());
		result = 37 * result + (getFechasinreemplazo() == null ? 0 : this.getFechasinreemplazo().hashCode());
		result = 37 * result + (getEsnimeireemplazo() == null ? 0 : this.getEsnimeireemplazo().hashCode());
		result = 37 * result + (getFoliosigade() == null ? 0 : this.getFoliosigade().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getCvealmacen() == null ? 0 : this.getCvealmacen().hashCode());
		result = 37 * result + (getCveproveedor() == null ? 0 : this.getCveproveedor().hashCode());
		result = 37 * result + (getRechazoalmacen() == null ? 0 : this.getRechazoalmacen().hashCode());
		result = 37 * result + (getRechazoproveedor() == null ? 0 : this.getRechazoproveedor().hashCode());
		result = 37 * result + (getDescrechazoalm() == null ? 0 : this.getDescrechazoalm().hashCode());
		result = 37 * result + (getDescrechazoprov() == null ? 0 : this.getDescrechazoprov().hashCode());
		result = 37 * result + (getIdsingarantia() == null ? 0 : this.getIdsingarantia().hashCode());
		result = 37 * result + (getDescsingarantia() == null ? 0 : this.getDescsingarantia().hashCode());
		result = 37 * result + (getFecharealenvio() == null ? 0 : this.getFecharealenvio().hashCode());
		result = 37 * result + (getIdproveedor() == null ? 0 : this.getIdproveedor().hashCode());
		result = 37 * result + (getTraspaso() == null ? 0 : this.getTraspaso().hashCode());
		result = 37 * result + (getCvemodelonvo() == null ? 0 : this.getCvemodelonvo().hashCode());
		result = 37 * result + (getDocumentoSap() == null ? 0 : this.getDocumentoSap().hashCode());
		result = 37 * result + (getMaterialnvo() == null ? 0 : this.getMaterialnvo().hashCode());
		return result;
	}

}
