package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SettingId generated by hbm2java
 */
@Embeddable
public class SettingId implements java.io.Serializable {

	private BigDecimal idSetting;
	private String llave;
	private String valor;
	private String descripcion;

	public SettingId() {
	}

	public SettingId(BigDecimal idSetting) {
		this.idSetting = idSetting;
	}

	public SettingId(BigDecimal idSetting, String llave, String valor, String descripcion) {
		this.idSetting = idSetting;
		this.llave = llave;
		this.valor = valor;
		this.descripcion = descripcion;
	}

	@Column(name = "ID_SETTING", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSetting() {
		return this.idSetting;
	}

	public void setIdSetting(BigDecimal idSetting) {
		this.idSetting = idSetting;
	}

	@Column(name = "LLAVE", length = 30)
	public String getLlave() {
		return this.llave;
	}

	public void setLlave(String llave) {
		this.llave = llave;
	}

	@Column(name = "VALOR", length = 250)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SettingId))
			return false;
		SettingId castOther = (SettingId) other;

		return ((this.getIdSetting() == castOther.getIdSetting()) || (this.getIdSetting() != null
				&& castOther.getIdSetting() != null && this.getIdSetting().equals(castOther.getIdSetting())))
				&& ((this.getLlave() == castOther.getLlave()) || (this.getLlave() != null
						&& castOther.getLlave() != null && this.getLlave().equals(castOther.getLlave())))
				&& ((this.getValor() == castOther.getValor()) || (this.getValor() != null
						&& castOther.getValor() != null && this.getValor().equals(castOther.getValor())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSetting() == null ? 0 : this.getIdSetting().hashCode());
		result = 37 * result + (getLlave() == null ? 0 : this.getLlave().hashCode());
		result = 37 * result + (getValor() == null ? 0 : this.getValor().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		return result;
	}

}
