package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Setting generated by hbm2java
 */
@Entity
@Table(name = "SETTING", schema = "CERTREG")
public class Setting implements java.io.Serializable {

	private SettingId id;

	public Setting() {
	}

	public Setting(SettingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSetting", column = @Column(name = "ID_SETTING", nullable = false, precision = 22, scale = 0) ),
			@AttributeOverride(name = "llave", column = @Column(name = "LLAVE", length = 30) ),
			@AttributeOverride(name = "valor", column = @Column(name = "VALOR", length = 250) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 50) ) })
	public SettingId getId() {
		return this.id;
	}

	public void setId(SettingId id) {
		this.id = id;
	}

}
