package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Usuariogrupocalificado generated by hbm2java
 */
@Entity
@Table(name = "USUARIOGRUPOCALIFICADO", schema = "CERTREG")
public class Usuariogrupocalificado implements java.io.Serializable {

	private UsuariogrupocalificadoId id;

	public Usuariogrupocalificado() {
	}

	public Usuariogrupocalificado(UsuariogrupocalificadoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuario", column = @Column(name = "IDUSUARIO", nullable = false, precision = 6, scale = 0) ),
			@AttributeOverride(name = "idgrupocalificado", column = @Column(name = "IDGRUPOCALIFICADO", nullable = false, precision = 22, scale = 0) ) })
	public UsuariogrupocalificadoId getId() {
		return this.id;
	}

	public void setId(UsuariogrupocalificadoId id) {
		this.id = id;
	}

}
