package com.claro.gml.persistence.model;
// Generated Dec 3, 2015 6:51:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariogrupocalificadoId generated by hbm2java
 */
@Embeddable
public class UsuariogrupocalificadoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idusuario;
	private BigDecimal idgrupocalificado;

	public UsuariogrupocalificadoId() {
	}

	public UsuariogrupocalificadoId(int idusuario, BigDecimal idgrupocalificado) {
		this.idusuario = idusuario;
		this.idgrupocalificado = idgrupocalificado;
	}

	@Column(name = "IDUSUARIO", nullable = false, precision = 6, scale = 0)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "IDGRUPOCALIFICADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdgrupocalificado() {
		return this.idgrupocalificado;
	}

	public void setIdgrupocalificado(BigDecimal idgrupocalificado) {
		this.idgrupocalificado = idgrupocalificado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariogrupocalificadoId))
			return false;
		UsuariogrupocalificadoId castOther = (UsuariogrupocalificadoId) other;

		return (this.getIdusuario() == castOther.getIdusuario())
				&& ((this.getIdgrupocalificado() == castOther.getIdgrupocalificado())
						|| (this.getIdgrupocalificado() != null && castOther.getIdgrupocalificado() != null
								&& this.getIdgrupocalificado().equals(castOther.getIdgrupocalificado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuario();
		result = 37 * result + (getIdgrupocalificado() == null ? 0 : this.getIdgrupocalificado().hashCode());
		return result;
	}

}
