
package com.claro.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClaroServiceService", targetNamespace = "http://service.ws.claro.com", wsdlLocation = "file:/home/montieln/Downloads/tmp/wsdl/ClaroService.wsdl")
public class ClaroServiceService
    extends Service
{

    private final static URL CLAROSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CLAROSERVICESERVICE_EXCEPTION;
    private final static QName CLAROSERVICESERVICE_QNAME = new QName("http://service.ws.claro.com", "ClaroServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/montieln/Downloads/tmp/wsdl/ClaroService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLAROSERVICESERVICE_WSDL_LOCATION = url;
        CLAROSERVICESERVICE_EXCEPTION = e;
    }

    public ClaroServiceService() {
        super(__getWsdlLocation(), CLAROSERVICESERVICE_QNAME);
    }

    public ClaroServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLAROSERVICESERVICE_QNAME, features);
    }

    public ClaroServiceService(URL wsdlLocation) {
        super(wsdlLocation, CLAROSERVICESERVICE_QNAME);
    }

    public ClaroServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLAROSERVICESERVICE_QNAME, features);
    }

    public ClaroServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClaroServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClaroService
     */
    @WebEndpoint(name = "ClaroService")
    public ClaroService getClaroService() {
        return super.getPort(new QName("http://service.ws.claro.com", "ClaroService"), ClaroService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClaroService
     */
    @WebEndpoint(name = "ClaroService")
    public ClaroService getClaroService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.claro.com", "ClaroService"), ClaroService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLAROSERVICESERVICE_EXCEPTION!= null) {
            throw CLAROSERVICESERVICE_EXCEPTION;
        }
        return CLAROSERVICESERVICE_WSDL_LOCATION;
    }

}
